In [1]:
import polars as pl

In [2]:
df = pl.scan_parquet("corpus/corpus_sample.parquet").select(pl.col("entities_places")).collect()

In [6]:
unique_places = set(df["entities_places"].explode().drop_nulls().to_list())

In [10]:
my_list = list(unique_places)

In [31]:
chunks = [my_list[i:i+20] for i in range(0, len(my_list), 20)]

In [32]:
chunks

[["Char'Naval",
  'Charleston',
  'N.D.L.R.',
  'Palais des colonies',
  'Mari',
  'Rwandais',
  'Beaune',
  'Boavista Porto',
  'Sainte-Anne-des-Plaines',
  'RD17',
  'Martiens',
  'aéroport international de Genève',
  'Belarus',
  'Amazone',
  'Remicourt',
  'Narbonne',
  'Étranglée',
  'Troyes',
  'Gavà',
  'Ecosse'],
 ['commissariat de Montbéliard',
  'Rodez',
  'Luisances',
  'Almaty',
  'Yorkshire',
  "Fresque de l'Étoile bleue",
  "Etat d'Afrique centrale jeudi",
  'Zénith de Paris',
  'Elysée',
  'Riviera vaudoise',
  'Florina',
  'Allier',
  'immeuble Atrium',
  'Michigan',
  'Wenzhou',
  'Chine centrale',
  'Fontainebleau',
  'Est de Paris',
  'Buttes-Chaumont',
  'du Var'],
 ['Valcourt',
  'St-Jérôme',
  'NR',
  'Rapée',
  'Besançon',
  'Partez',
  'Golf noire',
  'Port-Marly',
  'Int',
  'Grande bretagne',
  'Beauzac Conférence',
  'Ath',
  'Palais',
  'Abarki',
  'Lavallois',
  'hôpital Saint- Pierre',
  'ancien France',
  'Battamgang',
  'Région de Brest Tristan',
  'République de Cuba'],
 ['Gendarmerie',
  'La Nouvelle-Orléans',
  'Tél.0235270737',
  'Val d’Oise',
  'rue King-George',
  'Roannaise',
  'HE',
  'Hôtel du Châtelet',
  'Strathclyde',
  'Le Mans',
  'Rif',
  'Vicenza',
  'ministère du Commerce',
  'New York Retournons',
  'Villepinte',
  'Port Authority',
  'Région',
  'Midi',
  'Dortmund',
  'Tama'],
 ['Paris-VIII',
  'mer Egée ANKARA',
  'Bourg-en-Bresse',
  'Taulhac',
  'Tutsie',
  'Klodawa',
  'Météo-France',
  'Columbine',
  'Asg',
  'cathédrale de Westminster',
  'Port Louis',
  "département d'Etat américain",
  'Phalsbourg',
  'Ajaccio',
  'Nouadhibou',
  'le Pays',
  'Etats Unis',
  'boulevard périphérique de',
  'avenue Jean Mermoz',
  'Vanille'],
 ['parc de Thoiry',
  'Insta',
  'Taïwan',
  'Madone',
  'Blaye',
  "Cour d'appel",
  "Bibliothèque d'Étude",
  'Irakiens',
  'Kigali',
  'rue Travot',
  'place Stanislas',
  'Chypre',
  'USA-Congrès',
  'MAGA',
  'boulevard Ney',
  'Vénitienne',
  'bois de Boulogne',
  'Musée Granet',
  'Bosnie',
  'Yola'],
 ["Musée d'art moderne de New York",
  'Égypte',
  'Tigre',
  "L'Italie",
  'Pont-Tournant de Bordeaux',
  'Mortierbrigade',
  'du Flon',
  'théâtre des Cerises',
  'Sexotuto 2',
  'Mourmansk',
  'Alter',
  'Palerme Palerme DE NOTRE',
  'Bosniaques',
  'Tonara',
  'Grands Boulevards',
  'mont Vinson',
  'Montagne magique',
  'Misère',
  'Mondeville',
  'Porte de Versailles'],
 ['Tunisien',
  'Jamaïque',
  'Trinidad',
  'Morchamps-Molinay',
  'Vieux Nice',
  'Grand Saint',
  'Br',
  'Bel-Air',
  'The Edukators',
  'Pyrénées- Orientales',
  'Bangui',
  'au Havre',
  'Appalaches',
  'Molengeek',
  'Haute',
  'Lioudimila',
  'Canal Plus',
  'Aïd-el-Kébir',
  'Principauté',
  'Olympique'],
 ['MontgeneèveProposé',
  'Télégramme',
  'Bégamini',
  'New York',
  'Mervelier',
  'AfSud-mines-social-grève-justice',
  'Trovel',
  'Eure-et-Loir',
  'CM98',
  'Katorza',
  'Emelson',
  "l'État de",
  'Villaverde',
  'Amazonie',
  'ploudalmezeau',
  'Little',
  'Saint-Graal',
  'Lisieux Rendez',
  'Naissances',
  'Via Voltaire'],
 ['Tchéco-slovaquie',
  'rue Lanterne',
  'rue du Moulin',
  'musée Galliera',
  'chambre de Vienne',
  'Ariège',
  'le Belvédère',
  'Las',
  'Salpêtrière',
  'rue de Belfort',
  'Docteur',
  'hôtel Carlton',
  'théâtre de la Réplique',
  'Golan',
  'Roumains',
  'Mont-Tremblant',
  'Romains de « Sacro Gra',
  'Rouyn-Noranda',
  'hôtel de la Tour',
  'ICI Radio-Canada'],
 ['Bisontin',
  'triangle des Bermudes de Longueuil',
  'Stade Montois',
  'Anziza',
  'Santiago',
  'Grand Nord',
  'Famagouste',
  'Vestia',
  'apel.stjoseph.allonville@gmail.com',
  'Lune',
  'Esor',
  'Qatar',
  'Aglaé',
  'Auditorium',
  "État d'Adamawa",
  'Gdansk',
  'Q',
  'Jean-de- Bologne',
  'bagnole',
  'Doyenné'],
 ['Abusée',
  'TVA KM',
  'Rocher',
  'Estepona',
  'Hennebont',
  'Katanga',
  'RÉGION',
  'La Roche-sur-Yon',
  'Secrétaire général',
  'Pôle Simone-Veil',
  'Floirac',
  'Shawinigan',
  'hh/jh',
  'Correctionele',
  'Avenue Léon-Blum',
  'ducs de Bretagne',
  'MaisonYvonne',
  'Matignon',
  'Antibes',
  'Ramadi RAMADI'],
 ['Collectif',
  'XVIII e',
  'Nicaragua',
  'Gyeong-taeb Roh',
  'Angoulême',
  'Tullaye',
  'rue Charlevoix-de-Villers',
  'Léon-Gambetta',
  'Shinjuku',
  "L'Ile",
  'Matonge',
  'Le Pays',
  'Belvédère',
  'Borinage',
  'du Lot-et-Garonne',
  'République populaire',
  'Jade',
  'Fondation Bodmer de Genève',
  'Loire Atlantique',
  'Arabie Saoudite'],
 ['Bo',
  'Cour d’appel du Québec',
  'Cité des Doges',
  'Maison Carignan',
  'Belga',
  'Diapason',
  'Benin City',
  'Indre-et-Loire',
  'Atrium de la Mairie',
  'Tuléar',
  'Schengen',
  'Adler',
  'micro-Etats',
  'Mercredi',
  'Pamandzi',
  'empire du nycthémère',
  'Carré de Soie',
  'Romana',
  'Angles',
  'Italiens'],
 ['théâtre de Poche',
  'Sussex',
  'Mafia russe',
  'Noyon',
  'Raspail',
  'Théâtre du Point rouge',
  'Mambova',
  'Californien',
  'Théâtre des Célestins',
  "descente d'Orphée",
  'Scène',
  'Trieste',
  'subsittut',
  'Atlantic',
  'Maréchal-Bosquet',
  'Sihanoukville',
  'Colayrac',
  'Rostov',
  'Opéra de Rouen',
  'Suédois'],
 ["Cour d'appel de Douai",
  'Puntland',
  'Cimetière-Musée San Pedro',
  'griffonnent',
  'AUC',
  'Prez',
  'Carvinois',
  'RN',
  'François',
  'le Mosellan',
  'Sahel',
  'Esp)-Auxerre',
  'DOUAI',
  'Allemagne',
  'Auckland',
  'Trésor',
  'Chambre basse',
  'Morlaix',
  'Belfort',
  'Giglio'],
 ['Hangar-à-Bananes',
  'JFK',
  'Mars',
  'Fransaskois',
  'Muret',
  'Emiratis',
  'rue de la Prairie',
  'Petit Marais',
  'Intérieur',
  'Vieux Continent',
  'escort',
  'Rillé',
  'Aveyron',
  'Golfe',
  'Atlantique',
  'Colibri',
  'ARCACHON',
  'Suisse PROSTITUTIONLe',
  'Kremlin',
  'Jytomyr'],
 ['place du Caire',
  'Vieux-Lille',
  'rue de la Fosse',
  "Cour d'appel de Lisbonne",
  'Valenciennes-Monaco',
  'Lausanne',
  'Nord-Pas-de-Calais',
  'Mirail',
  'Louhansk',
  'Auchan Poitiers-Sud',
  'Israël-Palestine',
  'Kandé',
  'Vieux',
  'place du Japon',
  'mont Athos',
  'Satellite',
  'Magnée',
  'Registre',
  'Hauts-de-Seine',
  "Pavillon d'éducation communautaire Hochelaga- Maisonneuve"],
 ['Antrain',
  'Loiravec',
  'Azerbaïdjan',
  'vallée du Fraser',
  'Lambersart',
  'Conférences',
  'Philipine Boyard',
  'Saujon',
  'Zurich',
  'Autrichienne Babsie Steger',
  'Chenaux',
  'Buffalo',
  'Rallier',
  'Twilightmais',
  'Café de Paris',
  'Bruxelles- Capitale',
  'Ballamou',
  'Pontypool',
  'Reine-',
  'Bigourdans'],
 ['Sarre',
  'Afronet',
  'port de Neyran',
  'Beni Chiker',
  'Big Town',
  'prison de Fresnes',
  'Ciudad Juarez',
  'Bulgares',
  'Tignes',
  'Thaïlande',
  'Japon',
  'TRANSMIS ART',
  'Hôtel Matignon',
  "cour d'appel de",
  'Herzégovine',
  'Prillaz',
  'Saint-Florent-le Vieil',
  'Ambérieux',
  'rue des Petites Ecuries - Esc',
  'Rio de Janeiro'],
 ['hôtel Nord Pinus',
  'Retraites',
  'Asie',
  'Aerschot',
  "Almaty - l'ancienne capitale du Kazakhstan",
  'Elegu',
  'royaume de France',
  'Scamboville',
  'Frioul',
  'Laval',
  'Ouagadougou',
  'Sierra Leone',
  'université Humboldt',
  'Plan',
  'Rivne',
  'Insoumises',
  'Brest',
  'Saint-Martin-d’Hères',
  'Massachusetts',
  'Medellin'],
 ['Gétigné',
  'Ville de Québec',
  'Crédible',
  'États',
  'Lazaret',
  'Ville sainte',
  'Palais-Égalité',
  'VERDUN',
  'Fouettard',
  'La France',
  'Musée de la photographie à',
  'Marocain',
  'Barétous',
  'Instance',
  'Hokitika',
  'Arradon',
  'Plouzané',
  'LOS ANGELES',
  'avenue de Suffren',
  'Siwepalarhuhpak'],
 ['»Il',
  'Sainte-Anne-des-Monts',
  'Malienne',
  'caserne Sébastien',
  'Cinéma14',
  "L'Asie",
  'Marseille',
  'Mail',
  'Alaska',
  'CRETEIL',
  'Andenne',
  'Villefranche-sur-Saône',
  'Nouvelle-Aquitaine',
  'anti-Pékin',
  'Farda',
  'harmattan',
  'Yakusas',
  'Nebraska',
  'Fondation Martin-Bodmer',
  'K'],
 ['Beutty',
  'Québec',
  'quartier Chourié',
  'Clichy',
  "Saint-Georges d'argent",
  'Mwanza',
  'la Ville',
  'hôpital général de San Francisco',
  'U.ME.SPE',
  'chaussée de Waterloo',
  'Tunisiens',
  'Rebetez',
  'rue de la République',
  'Elm Grove Mel',
  'Lantin',
  'Gosford Park',
  'Roi-Soleil',
  'ISLE-JOURDAIN',
  'Présumées',
  'rue Pasteur'],
 ["Val d'Oise",
  'Médina',
  'Tchadiens',
  'Piques',
  'Bompastor',
  'île-de-France',
  'SRI',
  'porte de Limbourg',
  'Seine-  Saint-Denis',
  'Maegd',
  'Nice girls do it also',
  'opéra de Rouen',
  'lycée Buffon',
  'Massy',
  'Bouffay',
  'Avenue Willy-Brandt',
  'UNIVERSITE DE MONTREAL - 27',
  'Institut Jean-Vigo',
  'coin Stanley',
  'Cour populaire suprême'],
 ['brve',
  'Occidental',
  'rue Francis-de-Pressensé',
  'correspondant - Ne',
  'boulevard de Bonne-Nouvelle',
  'Tour',
  'Larzac',
  'La Mourière',
  'Frivoles',
  'Buenos Aires',
  'Picardie',
  'A/57/546',
  'Musée',
  'CH',
  'rue de la Barbinais',
  'Pôle Nord',
  'Puilboreau',
  'La Havane',
  'Amérique du sud',
  'A61'],
 ['Hôtel du Nord',
  'SEINE-ET-MARNE',
  'Tosa-Klause',
  'Franche-Comté',
  'Congolais',
  'Cavaliere',
  'Haut Valromey',
  'Condés',
  'St-François de Laval',
  'Capitale',
  'Foire de la Sainte-Catherine',
  'Haute- Garonne',
  'M m e Khélifi',
  'Tunisie',
  'ALC-Nice',
  'place des Capucins',
  'call-girl',
  "CPAS d'Ixelles",
  'Café-Théâtre',
  'Paris Texas'],
 ['Tchétchènes',
  'Denali',
  'Université Laval',
  'théâtre Gérard-Philipe',
  'Musée d’Orsay',
  'Saint- Georges-de-Beauce',
  "Cirque d'hiver Bouglione",
  'rue du Parc-Boivin',
  'FEQ',
  'Samusocial bruxellois',
  'France Bleu La Rochelle',
  'Lac-St',
  'C1_10',
  'Abou Dhabi',
  'Iquitos',
  'Ruelle-sur-Touvre',
  'Danaéde',
  'château de Clisson Suivez',
  'PHOTO+VIDEO+INFOGRAPHIE)= PARIS',
  'Tigery'],
 ['Petit-Théâtre',
  'Louvie-Juzon',
  'République du Centre',
  "Musée de l'Air et de l'",
  'Gesprachblättern',
  'Vancouver',
  'Mol',
  'Australie)/Mumbai',
  'Arelate',
  'East End',
  'de Belgique',
  'Gôteborg',
  'scenesenperspective.jmdo.com/',
  'Transmusicales',
  'Medgaz',
  'Hublot',
  'ATYPICAL',
  'Pont 9',
  'place de la Citadelle',
  'RDCongo)'],
 ['Montrouge',
  'Grande Comore',
  'PJF',
  'Loire',
  'Plender',
  'rue de Foucauld',
  'Corée du Nord',
  'boulevard de la Colline',
  'Island',
  'Bulle de zinc',
  'Francfort',
  'Cisjordanie',
  'Suphanburi',
  'quartier de Château-Rouge',
  'boulevard Winston-Churchill',
  'Villeurbanne "Gris',
  'Tatoué',
  'bedaine',
  'Macau',
  'Saint-Florent'],
 ['A 86',
  'Bouche',
  'Pays-de-la-Loire',
  'Columbus Avenue',
  'Zoloé',
  'Prospérités',
  'Turquie',
  'Pickton',
  'Cor',
  'Erythréen',
  'Nutella',
  'Brévannes',
  'Landes',
  'Lézignan-Corbières',
  'basilique de',
  'gendarmerie du',
  'Petite Fleur zurichoise',
  'PHOTO)=',
  'commissariat de Grenoble',
  'Vanuatu'],
 ['Bréhan  Dédicace',
  'Guadalquivir',
  'Pays de Galles',
  'tuinbouwbedrijven',
  'Cavaquinho',
  'passage Jouffroy',
  'Corse du Sud',
  'La Tunisie',
  'g.',
  'parc du Grand-Blottereau',
  'Sommerville',
  'Panama',
  'Baktay',
  'Marcheuses',
  'BRUXELLES',
  'CINÉ JIM',
  'Liberia',
  'Aix',
  'Venezuela',
  'lycée Camille-Sée'],
 ['comté de Nassau',
  'Sivens',
  'Ferney',
  'Hellions',
  'ZAC Paris-Rive gauche',
  'rue Christophe-Colomb',
  'Moscovici',
  'là.(Soudain.)Il',
  'Tributes',
  'M',
  'Porte Dauphine',
  'Américains',
  'théâtre de Penn ar Bed',
  'Albertains',
  'La Source',
  'SynopsisDiffusionsCastingTitre',
  'Châteauneuf-Villevieille',
  'Plateau',
  'Point de repères',
  'Zabadie'],
 ['C1_6',
  'Sibérie',
  'landerneau',
  'Bouloire',
  'chaussée de Helmet',
  'Haina',
  'Crocodoc',
  'asl',
  'Championne(France',
  'Montreux',
  'place de Verdun',
  'Cité de la musique',
  'Trie-la-Ville',
  'place Gerson',
  'Tehran Prostitutes',
  'Bellewaerde',
  'Mandchou',
  'Yser',
  'Anormal',
  '6 E'],
 ['Etats-Unis - 2',
  'Ria-Novosti',
  'Paulo',
  'Corso',
  'lepopulaire.fr',
  'Séminaire',
  'Calaisien',
  'Nantes',
  'hong-kong-l-etrange-message',
  'Cambodge Koma Regree',
  'Au-',
  'Albina',
  'Vannes',
  'Avenue Jean Mermoz',
  'Casino de Deauville',
  'Solvay',
  'Minke',
  'Défigurée',
  'rs',
  'Théâtre de Belleville'],
 ['Louis-Delgrès',
  "Val- d'Oise",
  'Hyper Cacher',
  'rue de Tocqueville',
  "aéroport d'Orly",
  'Capucins',
  'Carrefour Market',
  'Meuse',
  'Cévennes',
  "Cap d'Agde",
  'abmnantes@gmail.com',
  'Chassées',
  'Mollesse',
  'Papouasie-Nouvelle-Guinée',
  'Saint-Galmier',
  'Rueil-Malmaison',
  'Stains',
  'Costières',
  'Montataire',
  'gare de Cluj'],
 ['Moldavie',
  'Tours',
  'Portugal',
  'Moreaux',
  'figuresdoux-dingues',
  'Harlem',
  'Freetown',
  'Nouvelle-Calédonie',
  'République Démocratique du Congo',
  'Diên Biên Phu',
  'Parisien',
  'Région de St',
  'Rostov-sur-le-Don',
  'Lyon 9E',
  'Ciivise 1',
  'La Tuque',
  'Ramdani',
  'Limagne',
  'Kosovo',
  'Abyssinie'],
 ['Créteil',
  'rue Notre-Dame',
  'la Loire',
  'Pèlerinage',
  'Côte Gilmour',
  'pont Olof Palm',
  'Niçois',
  'FECAMP',
  'Plessis-Trévise',
  'Ipswich',
  'Issy-les-Moulineaux',
  'Hôtel Bergé',
  'couvent des conceptionnistes',
  'Zimri-',
  'Fédération française de basket-ball',
  'de Californie',
  'Coincés',
  'Indes néerlandaises',
  'Rillieux-la-Pape',
  'Bibliothèque municipale'],
 ['Altstetten',
  'VK',
  'Outremont-ma- chère',
  'Clermont-Ferrand',
  'IIIe arrondissement de Marseille',
  'Damiette',
  'Kenya',
  'Gironde',
  'République de Chypre',
  'Reggio de Calabre',
  'Hongkong',
  'A/57/548',
  'République des Pyrénées',
  'Clandestins',
  'Corée-du-Sud',
  'Bellechasse',
  'Bier Markt',
  'Auschwitz-Monowitz',
  'Côte',
  'Soudan du Sud'],
 ['Prague',
  'moyenne?Y',
  'Carpentras',
  'Haute-Loire',
  'Crimée',
  'Pretoria',
  'Elouges',
  'de Lille',
  'le Triolet',
  'Vichy-Auschwitz',
  'théâtre de Nîmes',
  'commissariat de Manage',
  'Londres',
  'département de la',
  "l'Espagne",
  'Epernay',
  'Tournefeuille',
  'Arènes',
  'Ville reine',
  'NANTERRE'],
 ['Porto Santo/ Dakar VOLLEY-BALL',
  'quartier Madeleine-Champ-de- Mars',
  'C219',
  'ULB',
  'MPT de Bellevue',
  'ENTREVUE ANNE',
  'Berne',
  'Montreuil',
  'Yssingeaux',
  'Carnegie Hall',
  'XIe',
  'Château-Gaillard',
  'Franceinfo',
  'Pakistan',
  'BOLLAERT',
  'rb-mat/ed/alm',
  'Rivière-des-Prairies',
  'Cour constitutionnelle',
  'rue Arago',
  'Théâtre des Amandiers'],
 ['Ille-et-Vilaine',
  'Est de la France',
  'Institut italien Eurispes',
  'Rivesaltes',
  'Centre- Sud',
  'brie',
  'Sorgues',
  'Filature',
  'la Défense',
  'Oregon',
  'rue Mirlo',
  '(5)',
  'agrafé',
  'Caudan-vous',
  'Sainte-Foy',
  'Lola',
  'FUGUEUSE',
  'Usine Déco',
  'chorale Saint-Pierre',
  'Monastère royal de Brou'],
 ['Ollioules',
  "l'Europe",
  'Westmount',
  'Orly',
  'Europe»et',
  'Bressans',
  'Saint-Marc',
  'Tchétchénie',
  'Durban',
  'METZ',
  'Mer noire',
  'Chambres',
  'Remontez la Canebière',
  'Toutes-Aides',
  'Japonais',
  'Prés-Javais',
  'Vidauban',
  'Hamani',
  'Koma Regree',
  'ORNON'],
 ['Khajurâho',
  'Réentendu',
  'Casa de Nariño',
  'Vienne',
  'Lavitola',
  'Libreville',
  'Pays Basque',
  'Maison carrée',
  'Guérande',
  'Maaarie',
  'Port-de-Bouc',
  'PHOTO+VIDEO+INFOGRAPHIE)=',
  'Abitibi',
  'Bourgeois',
  'mer Ionienne',
  'Vaucouleurs',
  'Organisée',
  'jardin-forêt',
  'Atlantico',
  'Café Voltaire'],
 ['Jugés',
  'église évangélique des Douze Apôtres',
  "Centre-Sud-de-l'Île-de",
  'rue des  Pierres-Blanches',
  'Paris PARIS',
  'La Jonquera',
  'avenue Pierre-Gamel',
  'Théâtre du Léman',
  'Admiratif',
  "Lion'",
  'PSG-Chelsea',
  'Châteauroux',
  'Plan Nord',
  '»En',
  'Hamptons',
  "Marché commun de l'Afrique Orientale",
  'de la Creuse',
  'Walcourt',
  'Versa',
  'Portsmouth'],
 ['New York New York',
  'Matabiau',
  'Essonne',
  'palais des Papes',
  'Bahreïn',
  'Aubervilliers',
  "aéroport d'Oran",
  'Montlucon',
  'Saint-Ulric',
  'Berrien',
  'Départementale',
  'Croix-Rouge suisse',
  'SES TRÈS',
  'Anadyr',
  'rue de la Fontaine Blanche',
  'CLANDESTINITÉ',
  'sgh/ev',
  'rue Adrien-Thierry',
  'séville',
  'N-VA'],
 ['Noode',
  'Cameroun',
  'Montréal-Nord',
  'Docks',
  'Petite Egypte',
  'Turin',
  'Noisy-le-Sec',
  'Mexicain',
  'Rosendaël',
  'Région de Brest',
  'Auxerre',
  "l'Italie",
  'Cap Canaveral',
  'Rosette',
  'Jonzac',
  'SCHUTTERSTOCK',
  'Froc',
  'Nil',
  'Tanger',
  'commissariat de Milan'],
 ['place Graslin',
  'Old-Fashioned Prostitutes',
  'Indes',
  'Kramatorsk',
  'Espagnole',
  'VEVEY',
  'Quartier rouge',
  'Gaza',
  'Courrier Laval',
  'Agenais',
  'Albanieà',
  'CHR Verviers',
  'Afro-américaine',
  'Locri',
  'Lion de Belfort',
  'Nés',
  'l’Amérique',
  'de Norvège',
  'Afrique de l’Ouest',
  'Crau'],
 ['Laharie',
  'Bas',
  'VS',
  'A 6',
  'Ossau',
  'Smersh',
  'Przemysl',
  'Rébénacq',
  'Algérienne',
  'AVIGNON',
  'Réunis',
  'Parvis Saint-Maurice',
  'Bonne Nouvelle',
  'Vieux Paris',
  'Melany',
  'ALSACE',
  'Third Junction',
  'Roche Bobois',
  'de la Meuse',
  'hôpital de Béziers'],
 ['Bâle',
  'Ile de Noirmoutier',
  'Warneton',
  'Udaya Nanayakkara',
  'Canal Ti Zef',
  'T',
  'CROYEZ SURTOUT',
  'Calvados Caen',
  'Claj',
  "Jardins d'Eole",
  'Auberge de La Renouée',
  'Forbach',
  'Réglisse',
  'boulevard du Général-Leclerc',
  'Salons',
  'Mont-Houy',
  'PSG- Valenciennes',
  'Venise',
  'Lien',
  'Monte-Carlo'],
 ['Hypno5e',
  'Nissan-lez-Enserune',
  'lac Victoria',
  'avenue Garon',
  'Pub Corn',
  'Nordiste',
  'gnan-gnan',
  'Soule',
  'Musée de la marine',
  'Quai de Versailles',
  'friperie Frip',
  'Districoupe',
  "bloc de l'Est",
  'Fondo',
  'Vietnam',
  'la Caf',
  'Barbagia',
  'Israël-Histoire',
  'Motril',
  'Saigon'],
 ['Chaussan',
  "cour d'appel de Douai",
  'Gras',
  'Columbia University',
  'Passy',
  'Wallonie',
  'Femmes-8mars-France-voile PARIS',
  'Bordeaux',
  'Sahel - de 2 500 hectares',
  'MPT Brest',
  'Baden-Baden',
  'mansardes',
  'Sri Lanka',
  'Fresnes-sur-Marne',
  'braconnais',
  'Boulogne',
  'Musée du XXIe siècle',
  'route de',
  'Écologie',
  'district Dolly'],
 ['Saint-Yves',
  'DEBATS',
  'VILLENAVE',
  'Escambray',
  '"(3',
  'Nièvre',
  'Casa Nostra',
  'Mont Chenoua',
  'Lyndy Saville',
  'Louvre',
  'porte Saint-Jean',
  'Saint-Christol-lez-Alès',
  'Bâgé-le-Châtel',
  'Riom',
  'Les Vilaines',
  'Tian Anmen',
  'Chalon-sur-Saône',
  'cathédrale de',
  'avenue de Ségur',
  'Copenhague'],
 ['Tournai',
  "Baie d'Ungava",
  'Jean-Jaurès',
  'Péniche',
  'Massif Central',
  'Emirats',
  '25 F',
  'Ris-Orangis',
  'immeuble Mireille',
  '19:06 UTC +01:00',
  'socialisationpour',
  'Gardanne',
  'Thiers- Ambert',
  'Ventspils',
  'rue de la Bergerie',
  "l'Afrique noire",
  'Arabie',
  'Kolbus',
  'du maajoun',
  'Pont-de-Vaux  Braderie de la Croix-'],
 ['Croix-Rouge',
  'Volos',
  'la Corse',
  'Rouennais',
  'ANXIEUSE',
  'Irakien',
  'cathédrale Pierre LAURENT',
  'temoignage@huffingtonpost.fr',
  'Alger',
  'Champ-de-Mars',
  'TRANSMIS CôteIvoire',
  'Saint- Roch',
  'Orgosolo',
  'Estaque',
  'Morgny-la-Pommeraye',
  'Chevalet',
  'Tropoje',
  'Algériennes',
  'Meknès',
  'Pauliste'],
 ['Drôme',
  'Jules-',
  'Israël-religion-judaïsme-kippour',
  'Laon',
  'Khelifi',
  'Woodstock',
  'B',
  'Ekaterinburg',
  'théâtre la Ruche',
  'boulevard Montmartre',
  'SCAC',
  'Antenne',
  'Haasdonk',
  'CLS',
  "salle de l'Estran",
  'F',
  'Bölzer',
  'Baumettes',
  'Ledbury Banff Crips',
  "Conservatoire d'Avignon"],
 ['Gravelles',
  'Industrie',
  '18e arrondissement de Paris',
  'limoges',
  'Tchernihiv',
  'Djemaa el-Fna',
  'pauvretéÌ',
  'Votron',
  'Mahorais',
  'Chinois',
  'Dourdan',
  'rue du Bon-Pasteur',
  'IFT',
  'rue Scribe',
  'hippodrome de Chantilly',
  'XIXe arrondissement',
  'Réfutez',
  'Forecasting',
  'théâtre de La Manicle',
  'Battant'],
 ['Sacré-Coeur de Marie',
  'Fédération française de bâtiment 47',
  'cco',
  'gatinois',
  'Bourgogne',
  'Haut-commissariat',
  'du « Carré',
  'Condamnés',
  'La Ville',
  'Lac',
  'République dominicaine',
  'Eure-et-loir',
  'blog.lefigaro.fr/rioufol',
  'Japon-Chine-Taïwan',
  'Sacré-Coeur',

In [33]:
from anthropic.types.message_create_params import MessageCreateParamsNonStreaming
from anthropic.types.messages.batch_create_params import Request
import anthropic

In [24]:
import os
import time

In [27]:
import re
import json

In [16]:
prompt_system = """Tu es un expert en géographie. Normalise chaque entité de la liste ci-dessous au format lieu, ville, pays. Si une entité est du bruit (non géographique ou non identifiable), retourne None. Réponds uniquement avec la liste originale mappée, sans commentaire.
Réponds en JSON : {'entité_originale': 'normalisation ou null'}"""

In [34]:
request_list = []
for i, chunk in enumerate(chunks):
    request = Request(
            custom_id=str(i),
            params=MessageCreateParamsNonStreaming(
                model="claude-sonnet-4-6",
                max_tokens=2048,
                system=prompt_system,
                messages=[
                    {
                        "role": "user",
                        "content": f"texte: {chunk}",
                    }
                ],
            ),
        )
    
    request_list.append(request)

In [20]:
os.environ["ANTHROPIC_API_KEY"] ='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'
client = anthropic.Client()

In [35]:
message_batch = client.messages.batches.create(requests=request_list)

In [36]:
message_batch

MessageBatch(id='msgbatch_01FXgQaKgu1QmZXdR45eJRzA', archived_at=None, cancel_initiated_at=None, created_at=datetime.datetime(2026, 5, 14, 14, 29, 7, 648018, tzinfo=datetime.timezone.utc), ended_at=None, expires_at=datetime.datetime(2026, 5, 15, 14, 29, 7, 648018, tzinfo=datetime.timezone.utc), processing_status='in_progress', request_counts=MessageBatchRequestCounts(canceled=0, errored=0, expired=0, processing=347, succeeded=0), results_url=None, type='message_batch')

In [37]:
MESSAGE_BATCH_ID = "msgbatch_01FXgQaKgu1QmZXdR45eJRzA"

message_batch_info = None
while True:
    message_batch_info = client.messages.batches.retrieve("msgbatch_01FXgQaKgu1QmZXdR45eJRzA")
    if message_batch_info.processing_status == "ended":
        break

    print(f"Batch {MESSAGE_BATCH_ID} is still processing...")
    time.sleep(30)
print(message_batch_info)

Batch msgbatch_01FXgQaKgu1QmZXdR45eJRzA is still processing...
Batch msgbatch_01FXgQaKgu1QmZXdR45eJRzA is still processing...
Batch msgbatch_01FXgQaKgu1QmZXdR45eJRzA is still processing...
Batch msgbatch_01FXgQaKgu1QmZXdR45eJRzA is still processing...
Batch msgbatch_01FXgQaKgu1QmZXdR45eJRzA is still processing...
Batch msgbatch_01FXgQaKgu1QmZXdR45eJRzA is still processing...
MessageBatch(id='msgbatch_01FXgQaKgu1QmZXdR45eJRzA', archived_at=None, cancel_initiated_at=None, created_at=datetime.datetime(2026, 5, 14, 14, 29, 7, 648018, tzinfo=datetime.timezone.utc), ended_at=datetime.datetime(2026, 5, 14, 14, 32, 5, 953758, tzinfo=TzInfo(0)), expires_at=datetime.datetime(2026, 5, 15, 14, 29, 7, 648018, tzinfo=datetime.timezone.utc), processing_status='ended', request_counts=MessageBatchRequestCounts(canceled=0, errored=0, expired=0, processing=0, succeeded=347), results_url='https://api.anthropic.com/v1/messages/batches/msgbatch_01FXgQaKgu1QmZXdR45eJRzA/results', type='message_batch')

In [28]:
def parse_batch_item(item):
    text = item.result.message.content[0].text
    m = re.search(r"```json\s*(.*?)\s*```", text, re.S)
    json_str = m.group(1) if m else text
    data = json.loads(json_str)
    return data

In [38]:
result_dict_claude = {}
for result in client.messages.batches.results(
    MESSAGE_BATCH_ID,
):
    data = parse_batch_item(result)
    result_dict_claude.update(data)

In [44]:
liste_pays = [r for r in result_dict_claude.items() if r[1] is not None]

In [47]:
len(liste_pays)/60/60

1.1019444444444444

In [50]:
!pip install requests

Collecting requests
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting charset_normalizer<4,>=2 (from requests)
  Using cached charset_normalizer-3.4.7-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
Requirement already satisfied: idna<4,>=2.5 in /home/plume/miniconda3/envs/svm/lib/python3.12/site-packages (from requests) (3.11)
Collecting urllib3<3,>=1.26 (from requests)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: certifi>=2023.5.7 in /home/plume/miniconda3/envs/svm/lib/python3.12/site-packages (from requests) (2026.2.25)
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
Using cached charset_normalizer-3.4.7-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (216 kB)
Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
Installing collected packages: urllib3, charset_normalizer, requests
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [requests]1/3 [charset_normalizer]
Successfully installed charset_normalizer-3.4.7 requests-2.34.2 urllib3-2.7.0

In [99]:
import time
import requests
import pandas as pd

def geocode(name):
    #url = "https://nominatim.openstreetmap.org/search"
    url = "https://nominatim.openhistoricalmap.org/search"
    params = {"q": name, "format": "json", "limit": 1, "addressdetails": 1}
    headers = {"User-Agent": "corpus-research/1.0", "Accept-Language": "fr"}
    r = requests.get(url, params=params, headers=headers)
    data = r.json()
    if not data:
        return None
    d = data[0]
    return {
        "nom": name,
        "lat": float(d["lat"]),
        "lon": float(d["lon"]),
        "pays": d["address"].get("country", ""),
        "code_pays": d["address"].get("country_code", "").upper(),
        "nom_complet": d["display_name"],
    }

In [ ]:
resultats = []
for lieu in liste_pays:
    res = geocode(lieu)
    if res:
        resultats.append(res)
        print(f"✓ {lieu} → {res['pays']}")
    else:
        print(f"✗ {lieu} → non trouvé")
    time.sleep(1.1)  # rate limit Nominatim

df = pd.DataFrame(resultats)
df.to_csv("geocodes.csv", index=False)
df.to_parquet("geocodes.parquet", index=False)

In [52]:
resultats

[{'nom': ('Saint-Étienne-du-Rouvray',
   'Saint-Étienne-du-Rouvray, Saint-Étienne-du-Rouvray, France'),
  'lat': 49.3771726,
  'lon': 1.1095372,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': 'Saint-Étienne-du-Rouvray, Rue de Verdun, Saint-Étienne-du-Rouvray, Rouen, Seine-Maritime, Normandie, France métropolitaine, 76800, France'},
 {'nom': ('Abou Kémal', 'Abu Kamal, Deir ez-Zor, Syrie'),
  'lat': 34.4505521,
  'lon': 40.9170636,
  'pays': 'Syrie',
  'code_pays': 'SY',
  'nom_complet': "Al-Bukamal, Sous-district d'Al-Bukamal, District d'Al-Bukamal, Gouvernorat de Deir ez-Zor, Syrie"},
 {'nom': ('Perros-Guirec', 'Perros-Guirec, Perros-Guirec, France'),
  'lat': 48.8058115,
  'lon': -3.4745671,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': "Centre d'incendie et de secours de Perros-Guirec, Rue Gustave Eiffel, Toul Al Lan, La Clarté, Perros-Guirec, Lannion, Côtes-d'Armor, Bretagne, France métropolitaine, 22700, France"},
 {'nom': ('Saint-Gaudens', 'Saint-Gaudens, Saint-Gaudens, France'),
  'lat': 43.1077682,
  'lon': 0.7247218,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': 'Saint-Gaudens, Haute-Garonne, Occitanie, France métropolitaine, 31800, France'},
 {'nom': ('Carmel', 'Carmel, Californie, États-Unis'),
  'lat': 36.5552656,
  'lon': -121.923278,
  'pays': "États-Unis d'Amérique",
  'code_pays': 'US',
  'nom_complet': "Carmel-by-the-Sea, Monterey County, Californie, États-Unis d'Amérique"},
 {'nom': ('Philippines', 'Philippines, Philippines, Philippines'),
  'lat': 14.2730344,
  'lon': 121.052126,
  'pays': 'Philippines',
  'code_pays': 'PH',
  'nom_complet': 'Amkor Technology Philippines P3, 119, North Science Avenue, F. Tech Philippines Manufacturing, Inc, Biñan, Laguna, Calabarzon, 4024, Philippines'},
 {'nom': ('Lower Mainland', 'Lower Mainland, Vancouver, Canada'),
  'lat': 49.2788488,
  'lon': -123.0702835,
  'pays': 'Canada',
  'code_pays': 'CA',
  'nom_complet': 'Lower Mainland Hardwood Tile and Stone, 636, Commercial Drive, Grandview-Woodland, Vancouver, District régional du Grand Vancouver, Colombie-Britannique, V5L 2W2, Canada'},
 {'nom': ('Chalon', 'Chalon-sur-Saône, Chalon-sur-Saône, France'),
  'lat': 46.7831001,
  'lon': 4.8534326,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': 'Chalon-sur-Saône, Saône-et-Loire, Bourgogne-Franche-Comté, France métropolitaine, 71100, France'},
 {'nom': ('New York underground', 'New York, New York, États-Unis'),
  'lat': 40.7127281,
  'lon': -74.0060152,
  'pays': "États-Unis d'Amérique",
  'code_pays': 'US',
  'nom_complet': "New York, États-Unis d'Amérique"},
 {'nom': ('bibliothèque de Fontevraud',
   "Fontevraud-l'Abbaye, Fontevraud-l'Abbaye, France"),
  'lat': 47.1818252,
  'lon': 0.0498617,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': "Fontevraud-l’Abbaye, Fontevraud-l'Abbaye, Saumur, Maine-et-Loire, Pays de la Loire, France métropolitaine, 49590, France"},
 {'nom': ('MONTLUCON', 'Montluçon, Montluçon, France'),
  'lat': 46.3400296,
  'lon': 2.6073963,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': 'Montluçon, Allier, Auvergne-Rhône-Alpes, France métropolitaine, 03100, France'},
 {'nom': ("Europe de l'Est", "Europe de l'Est"),
  'lat': 48.5934283,
  'lon': 7.7708936,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': "Europe, Avenue de l'Europe, Quartier des XV, Orangerie-Conseil des XV, Strasbourg, Bas-Rhin, Collectivité européenne d'Alsace, Grand Est, France métropolitaine, 67000, France"},
 {'nom': ('Kamogawa', 'Kamogawa, Kamogawa, Japon'),
  'lat': 35.1076645,
  'lon': 140.1037006,
  'pays': 'Japon',
  'code_pays': 'JP',
  'nom_complet': '安房鴨川, 浜波太港線, 横渚, Kamogawa, Préfecture de Chiba, 296-8799, Japon'},
 {'nom': ('Lens', 'Lens, Lens, France'),
  'lat': 50.4291723,
  'lon': 2.8319805,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': 'Lens, Pas-de-Calais, Hauts-de-France, France métropolitaine, 62300, France'},
 {'nom': ('Calcuta', 'Kolkata, Kolkata, Inde'),
  'lat': 22.5726459,
  'lon': 88.3638953,
  'pays': 'Inde',
  'code_pays': 'IN',
  'nom_complet': 'Calcutta, Kolkata Metropolitan Area, Kolkata, Bengale-Occidental, Inde'},
 {'nom': ('rue Saint-Martin', 'Rue Saint-Martin, Paris, France'),
  'lat': 48.8672955,
  'lon': 2.3545759,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': 'Rue Saint-Martin, Quartier des Arts-et-Métiers, Paris 3e Arrondissement, Paris, Île-de-France, France métropolitaine, 75003, France'},
 {'nom': ("green d'Augusta",
   'Augusta National Golf Club, Augusta, États-Unis'),
  'lat': 33.500558,
  'lon': -82.0225816,
  'pays': "États-Unis d'Amérique",
  'code_pays': 'US',
  'nom_complet': "Augusta National Golf Club, 2604, Washington Road, Windsor Court, National Hills, Augusta, Richmond County, Géorgie, 30904, États-Unis d'Amérique"},
 {'nom': ("L'Espagne", 'Espagne, Espagne, Espagne'),
  'lat': 46.0182561,
  'lon': 4.6287997,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': "Château d'Espagne, Route de Riberolles, Espagne, Saint-Julien, Villefranche-sur-Saône, Rhône, Auvergne-Rhône-Alpes, France métropolitaine, 69640, France"},
 {'nom': ('Bruxelles', 'Bruxelles, Bruxelles, Belgique'),
  'lat': 50.8551025,
  'lon': 4.3510915,
  'pays': 'Belgique',
  'code_pays': 'BE',
  'nom_complet': 'Bruxelles, Bruxelles-Capitale, Belgique'},
 {'nom': ('Broadway', 'Broadway, New York, États-Unis'),
  'lat': 40.8957061,
  'lon': -73.896718,
  'pays': "États-Unis d'Amérique",
  'code_pays': 'US',
  'nom_complet': "Broadway, The Bronx, Bronx County, New York, 10471, États-Unis d'Amérique"},
 {'nom': ('Valserine', 'Valserine, Ain, France'),
  'lat': 46.1073717,
  'lon': 5.8307764,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': 'Bellegarde-sur-Valserine, Valserhône, Nantua, Ain, Auvergne-Rhône-Alpes, France métropolitaine, 01200, France'},
 {'nom': ('Odéon', 'Odéon, Paris, France'),
  'lat': 48.8523043,
  'lon': 2.3393706,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': 'Odéon, Boulevard Saint-Germain, Quartier de la Monnaie, Paris 6e Arrondissement, Paris, Île-de-France, France métropolitaine, 75006, France'},
 {'nom': ('Louvigné-du-Désert', 'Louvigné-du-Désert, Fougères, France'),
  'lat': 48.4815182,
  'lon': -1.1231428,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': 'Louvigné-du-Désert, Fougères-Vitré, Ille-et-Vilaine, Bretagne, France métropolitaine, 35420, France'},
 {'nom': ('Finistère', 'Finistère, Quimper, France'),
  'lat': 48.0140084,
  'lon': -4.0925986,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': 'Boulevard du Finistère, Cité administrative, Gourvily, Ty-Nay, Quimper, Finistère, Bretagne, France métropolitaine, 29000, France'},
 {'nom': ('LISBONNE', 'Lisbonne, Lisbonne, Portugal'),
  'lat': 38.7077507,
  'lon': -9.1365919,
  'pays': 'Portugal',
  'code_pays': 'PT',
  'nom_complet': 'Lisbonne, Portugal'},
 {'nom': ('Basilique Saint-Pierre',
   'Basilique Saint-Pierre, Vatican, Vatican'),
  'lat': 41.9021569,
  'lon': 12.4537105,
  'pays': 'Cité du Vatican',
  'code_pays': 'VA',
  'nom_complet': 'Basilique Saint-Pierre, Piazza San Pietro, Cité du Vatican, 00120, Cité du Vatican'},
 {'nom': ('Khabarovsk', 'Khabarovsk, Khabarovsk, Russie'),
  'lat': 48.4812568,
  'lon': 135.0762968,
  'pays': 'Russie',
  'code_pays': 'RU',
  'nom_complet': 'Khabarovsk, городской округ Хабаровск, Kraï de Khabarovsk, District fédéral extrême-oriental, Russie'},
 {'nom': ('Le Havre', 'Le Havre, Le Havre, France'),
  'lat': 49.4938975,
  'lon': 0.1079732,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': 'Le Havre, Seine-Maritime, Normandie, France métropolitaine, France'},
 {'nom': ('Théâtre de Gennevilliers',
   'Théâtre de Gennevilliers, Gennevilliers, France'),
  'lat': 48.9142789,
  'lon': 2.2996941,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': 'Théâtre de Gennevilliers, Avenue des Grésillons, Grésillons, Les Grésillons, Gennevilliers, Nanterre, Hauts-de-Seine, Île-de-France, France métropolitaine, 92230, France'},
 {'nom': ('Montmartre', 'Montmartre, Paris, France'),
  'lat': 48.8854619,
  'lon': 2.3391535,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': 'Montmartre, Paris, Île-de-France, France métropolitaine, France'},
 {'nom': ('Gonesse', 'Gonesse, Gonesse, France'),
  'lat': 48.9786975,
  'lon': 2.4766195,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': "Gonesse, D 170, Gonesse, Sarcelles, Val-d'Oise, Île-de-France, France métropolitaine, 95500, France"},
 {'nom': ('Orlando', 'Orlando, Orlando, États-Unis'),
  'lat': 28.4129036,
  'lon': -81.3094431,
  'pays': "États-Unis d'Amérique",
  'code_pays': 'US',
  'nom_complet': "Orlando International Airport, 1, Jeff Fuqua Boulevard, Orlando International Airport, Orlando, Comté d'Orange, Floride, 32827, États-Unis d'Amérique"},
 {'nom': ('Centrafrique', 'Centrafrique, Bangui, République centrafricaine'),
  'lat': 4.3656303,
  'lon': 18.5874249,
  'pays': 'République centrafricaine',
  'code_pays': 'CF',
  'nom_complet': 'Société de Distribution d’Eau de Centrafrique, Rue de la Moyenne Corniche, Bangui, République centrafricaine'},
 {'nom': ('Woodlands', 'Woodlands, Singapour, Singapour'),
  'lat': 1.436897,
  'lon': 103.786216,
  'pays': 'Singapour',
  'code_pays': 'SG',
  'nom_complet': 'Woodlands, North Region, Singapour'},
 {'nom': ('Gagnoa', "Gagnoa, Gagnoa, Côte d'Ivoire"),
  'lat': 6.1015153,
  'lon': -5.9861817,
  'pays': 'Côte d’Ivoire',
  'code_pays': 'CI',
  'nom_complet': "Aéroport de Gagnoa, Route de l'Aéroport, Guessihio, Gagnoa, Gôh, Gôh-Djiboua, Côte d’Ivoire"},
 {'nom': ("Val de l'Aurence", "Val de l'Aurence, Limoges, France"),
  'lat': 45.8421921,
  'lon': 1.2317888,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': "France services Limoges - Val de l'Aurence, Rue Marcel Vardelle, Corgnac, Le Mas Blanc, Limoges, Haute-Vienne, Nouvelle-Aquitaine, France métropolitaine, 87100, France"},
 {'nom': ('Brésil', 'Brésil, Brasília, Brésil'),
  'lat': -15.7995244,
  'lon': -47.8640951,
  'pays': 'Brésil',
  'code_pays': 'BR',
  'nom_complet': 'Congrès national du Brésil, S1, Brasilia, District fédéral, Région Centre-Ouest, 70160-900, Brésil'},
 {'nom': ("L'Elysée", "Palais de l'Élysée, Paris, France"),
  'lat': 48.8703744,
  'lon': 2.3160687,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': "Palais de l'Élysée, Avenue de Marigny, Quartier de la Madeleine, Paris 8e Arrondissement, Paris, Île-de-France, France métropolitaine, 75008, France"},
 {'nom': ('lycée Thiers', 'Lycée Thiers, Marseille, France'),
  'lat': 43.2964519,
  'lon': 5.3828258,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': "Collège, lycée général et technologique, classes préparatoires aux grandes écoles Thiers, 5, Place du Lycée, Thiers, 1er Arrondissement, Marseille, Bouches-du-Rhône, Provence-Alpes-Côte d'Azur, France métropolitaine, 13001, France"},
 {'nom': ('Mangin île Beaulieu', 'Île Beaulieu, Nantes, France'),
  'lat': 47.209205,
  'lon': -1.5308242,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': 'Île Beaulieu, Île de Nantes, Nantes, Loire-Atlantique, Pays de la Loire, France métropolitaine, France'},
 {'nom': ('Strasbourg', 'Strasbourg, Strasbourg, France'),
  'lat': 48.584614,
  'lon': 7.7507127,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': "Strasbourg, Bas-Rhin, Collectivité européenne d'Alsace, Grand Est, France métropolitaine, France"},
 {'nom': ('Turque', 'Turquie'),
  'lat': 39.294076,
  'lon': 35.2316631,
  'pays': 'Turquie',
  'code_pays': 'TR',
  'nom_complet': 'Turquie'},
 {'nom': ("canal de l'Ourcq", "Canal de l'Ourcq, Paris, France"),
  'lat': 48.8907639,
  'lon': 2.3819888,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': "Canal de l'Ourcq, Rue de l'Ourcq, Quartier de la Villette, Paris 19e Arrondissement, Paris, Île-de-France, France métropolitaine, 75019, France"},
 {'nom': ('Métro Saint-Laurent', 'Station Saint-Laurent, Montréal, Canada'),
  'lat': 45.510261,
  'lon': -73.565706,
  'pays': 'Canada',
  'code_pays': 'CA',
  'nom_complet': 'Station Saint-Laurent (De Maisonneuve / Clark), Boulevard De Maisonneuve Est, Habitations Jeanne-Mance, Ville-Marie, Montréal, Agglomération de Montréal, Montréal (région administrative), Québec, H2X 1J6, Canada'},
 {'nom': ("université d'Orléans", "Université d'Orléans, Orléans, France"),
  'lat': 47.8416678,
  'lon': 1.9366943,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': "Université d'orléans, 10, Rue de Tours, Campus Universitaire, Orléans, Loiret, Centre-Val de Loire, France métropolitaine, 45065, France"},
 {'nom': ('RD du Congo', 'République Démocratique du Congo'),
  'lat': -2.9814344,
  'lon': 23.8222636,
  'pays': 'République démocratique du Congo',
  'code_pays': 'CD',
  'nom_complet': 'République démocratique du Congo'},
 {'nom': ('Victor-Lagrange', 'Victor-Lagrange, Lyon, France'),
  'lat': 45.7447048,
  'lon': 4.8334448,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': 'Rue Victor Lagrange, Les Girondins, Gerland, Lyon 7e Arrondissement, Lyon, Métropole de Lyon, Rhône, Auvergne-Rhône-Alpes, France métropolitaine, 69007, France'},
 {'nom': ('Oregon City', 'Oregon City, Oregon, États-Unis'),
  'lat': 45.3573429,
  'lon': -122.606758,
  'pays': "États-Unis d'Amérique",
  'code_pays': 'US',
  'nom_complet': "Oregon City, Clackamas County, Oregon, 97045, États-Unis d'Amérique"},
 {'nom': ('Tala', 'Tala, Pune, Inde'),
  'lat': 18.2457637,
  'lon': 73.682735,
  'pays': 'Inde',
  'code_pays': 'IN',
  'nom_complet': 'Chandra lake, Velhe, Pune, Maharashtra, Inde'},
 {'nom': ('Arras', 'Arras, Arras, France'),
  'lat': 50.291048,
  'lon': 2.7772211,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': 'Arras, Pas-de-Calais, Hauts-de-France, France métropolitaine, 62000, France'},
 {'nom': ('Elvas', 'Elvas, Elvas, Portugal'),
  'lat': 38.8955156,
  'lon': -7.1422728,
  'pays': 'Portugal',
  'code_pays': 'PT',
  'nom_complet': 'Elvas, Estrada das Fontainhas, Caia, São Pedro e Alcáçova, Elvas, Portalegre, 7350-227, Portugal'},
 {'nom': ('Coudekerque-Branche',
   'Coudekerque-Branche, Coudekerque-Branche, France'),
  'lat': 51.0175188,
  'lon': 2.3751331,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': 'Coudekerque-Branche, Rue du Tonkin, Vieux-Coudekerque, Coudekerque-Branche, Dunkerque, Nord, Hauts-de-France, France métropolitaine, 59210, France'},
 {'nom': ('Lusaka', 'Lusaka, Lusaka, Zambie'),
  'lat': -15.4163395,
  'lon': 28.2818414,
  'pays': 'Zambie',
  'code_pays': 'ZM',
  'nom_complet': 'Lusaka, Lusaka District, Province de Lusaka, 10101, Zambie'},
 {'nom': ('Île Guérandaise', 'Île Guérandaise, Guérande, France'),
  'lat': 47.3373975,
  'lon': -2.4334744,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': "Mission locale de la Presqu'île Guérandaise, Rue Louis Eon, Quartier La Métairie, Léchet, Guérande, Saint-Nazaire, Loire-Atlantique, Pays de la Loire, France métropolitaine, 44350, France"},
 {'nom': ('Ain', 'Ain, Bourg-en-Bresse, France'),
  'lat': 46.2337295,
  'lon': 5.3538775,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': 'France, Meillonnas, Bourg-en-Bresse, Ain, Auvergne-Rhône-Alpes, France métropolitaine, 01370, France'},
 {'nom': ('Auvergne-Rhône-Alpes', 'Auvergne-Rhône-Alpes, Lyon, France'),
  'lat': 45.7665471,
  'lon': 4.8315447,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': 'Temple de la Lanterne, Rue Lanterne, Terreaux, Lyon 1er Arrondissement, Lyon, Métropole de Lyon, Rhône, Auvergne-Rhône-Alpes, France métropolitaine, 69001, France'},
 {'nom': ('argentine', 'Argentine, Buenos Aires, Argentine'),
  'lat': -34.6071553,
  'lon': -58.3711253,
  'pays': 'Argentine',
  'code_pays': 'AR',
  'nom_complet': 'Banco Nación, 326, Bartolomé Mitre, Microcentro, San Nicolás, Buenos Aires, Comuna 1, Ciudad Autónoma de Buenos Aires, 1036, Argentine'},
 {'nom': ('Welfare Island', 'Roosevelt Island, New York, États-Unis'),
  'lat': 40.7613368,
  'lon': -73.9502853,
  'pays': "États-Unis d'Amérique",
  'code_pays': 'US',
  'nom_complet': "Roosevelt Island, Manhattan, New York County, New York, 10044, États-Unis d'Amérique"},
 {'nom': ('Sarthe', 'Sarthe, Pays de la Loire, France'),
  'lat': 48.0269287,
  'lon': 0.2538217,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': 'Sarthe, Pays de la Loire, France métropolitaine, France'},
 {'nom': ('RAMALLAH', 'Ramallah, Ramallah, Palestine'),
  'lat': 31.9158969,
  'lon': 35.1781625,
  'pays': 'الأراضي الفلسطينية',
  'code_pays': 'PS',
  'nom_complet': 'شارع فلسطين, Batin alHawa, Al-Tira, Ramallah, Zone A, Cisjordanie, 606, الأراضي الفلسطينية'},
 {'nom': ('Saint-Lambert-la-Potherie',
   'Saint-Lambert-la-Potherie, Maine-et-Loire, France'),
  'lat': 47.4811787,
  'lon': -0.6786062,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': 'Saint-Lambert-la-Potherie, Angers, Maine-et-Loire, Pays de la Loire, France métropolitaine, 49070, France'},
 {'nom': ('Windsor', 'Windsor, Berkshire, Royaume-Uni'),
  'lat': 51.5070563,
  'lon': -1.5341236,
  'pays': 'Royaume-Uni',
  'code_pays': 'GB',
  'nom_complet': 'Windsor House Stables, Upper Lambourn, Lambourn, West Berkshire, Angleterre, Royaume-Uni'},
 {'nom': ('-Etats-Unis', 'États-Unis'),
  'lat': 39.7837304,
  'lon': -100.445882,
  'pays': "États-Unis d'Amérique",
  'code_pays': 'US',
  'nom_complet': "États-Unis d'Amérique"},
 {'nom': ('Cap Vert', 'Cap-Vert, Cap-Vert'),
  'lat': 16.0000552,
  'lon': -24.0083947,
  'pays': 'Cap-Vert',
  'code_pays': 'CV',
  'nom_complet': 'Cap-Vert'},
 {'nom': ('Saint-Valentin', 'Saint-Valentin, Indre, France'),
  'lat': 46.9513917,
  'lon': 1.8656284,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': 'Saint-Valentin, Issoudun, Indre, Centre-Val de Loire, France métropolitaine, 36100, France'},
 {'nom': ('Bonneville', 'Bonneville, Haute-Savoie, France'),
  'lat': 46.0775797,
  'lon': 6.4086189,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': 'Bonneville, Haute-Savoie, Auvergne-Rhône-Alpes, France métropolitaine, 74130, France'},
 {'nom': ('KANO', 'Kano, Kano, Nigeria'),
  'lat': 11.9939978,
  'lon': 8.5219738,
  'pays': 'Nigéria',
  'code_pays': 'NG',
  'nom_complet': 'Kano, Yakasai, Kano Municipal, État de Kano, 700271, Nigéria'},
 {'nom': ('Loire- Atlantique', 'Loire-Atlantique, Pays de la Loire, France'),
  'lat': 47.3481615,
  'lon': -1.8727461,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': 'Loire-Atlantique, Pays de la Loire, France métropolitaine, France'},
 {'nom': ('rue Oehlenschlægersgade',
   'Oehlenschlægersgade, Copenhague, Danemark'),
  'lat': 55.6698992,
  'lon': 12.5498868,
  'pays': 'Danemark',
  'code_pays': 'DK',
  'nom_complet': 'Oehlenschlægersgade, Vestervold, Vesterbro, Copenhague, Commune de Copenhague, Region Hovedstaden, 1663, Danemark'},
 {'nom': ("porte d'Anvers", "Porte d'Anvers, Bruxelles, Belgique"),
  'lat': 50.8564344,
  'lon': 4.3527123,
  'pays': 'Belgique',
  'code_pays': 'BE',
  'nom_complet': "Porte d'Anvers, Quartier des Quais, Pentagone, Bruxelles, Bruxelles-Capitale, Belgique"},
 {'nom': ('Saguenay', 'Saguenay, Saguenay, Canada'),
  'lat': 48.417654,
  'lon': -71.0521994,
  'pays': 'Canada',
  'code_pays': 'CA',
  'nom_complet': 'Pavillon promotion Saguenay, Rue Chabanel, Université du Québec à Chicoutimi (UQAC), Arrondissement de Chicoutimi, Saguenay, Saguenay–Lac-Saint-Jean, Québec, G7H 2R3, Canada'},
 {'nom': ('Nouméa', 'Nouméa, Nouméa, Nouvelle-Calédonie'),
  'lat': -22.2576128,
  'lon': 166.4729907,
  'pays': 'France',
  'code_pays': 'FR',
  'nom_complet': 'Nouméa Magenta Airport, Rue Roger Gervolino, Green Valley, Aérodrome, Secteur Est, Nouméa, Province Sud, Nouvelle-Calédonie, 98800, France'},
 {'nom': ('Estuaire', 'Estuaire, Libreville, Gabon'),
  'lat': 0.3718202,
  'lon': 9.4607792,
  'pays': 'Gabon',
  'code_pays': 'GA',
  'nom_complet': 'Kia Gabon, Avenue Roi Denis Rapontchombo, Michel Marine, Oloumi, 3ème Arrondissement, Libreville, Estuaire, 2181, Gabon'},
 {'nom': ('Portugal de Salazar', 'Portugal, Lisbonne, Portugal'),
  'lat': 38.750976,

In [53]:
df = pd.DataFrame(resultats)
df.to_csv("corpus/geocodes_tmp.csv", index=False)
df.to_parquet("corpus/geocodes_tmp.parquet", index=False)

In [ ]:
# Trouver l'index où ça a planté
dernier_fait = resultats[-1]["nom"]
idx_reprise = liste_pays.index(dernier_fait) + 1

print(f"Reprise à l'index {idx_reprise} : {liste_pays[idx_reprise]}")

for lieu in liste_pays[idx_reprise:]:
    for tentative in range(3):
        try:
            res = geocode(lieu)
            if res:
                resultats.append(res)
                print(f"✓ {lieu} → {res['pays']}")
            else:
                print(f"✗ {lieu} → non ttest = geocode_geonames(non_trouves[3])rouvé")
            break
        except requests.exceptions.ConnectionError:
            print(f"⚠ Réseau KO, attente 30s (tentative {tentative+1}/3)...")
            time.sleep(30)
    
    time.sleep(1.1)

Reprise à l'index 2386 : ('La Pierre-Saint-Martin', 'La Pierre-Saint-Martin, Pyrénées-Atlantiques, France')
✓ ('La Pierre-Saint-Martin', 'La Pierre-Saint-Martin, Pyrénées-Atlantiques, France') → France
✗ ('Jean-Legendre', 'Théâtre Jean-Legendre, Compiègne, France') → non trouvé
✓ ('Haïtien', 'Haïti, Port-au-Prince, Haïti') → Haïti
✓ ('Mont Fuji', 'Mont Fuji, Shizuoka, Japon') → Japon
✓ ('Pays Foyen', 'Pays Foyen, Sainte-Foy-la-Grande, France') → France
✓ ('Vigen', 'Vigen, Haute-Vienne, France') → France
✗ ('Katenge', 'Katenge, Haut-Katanga, République démocratique du Congo') → non trouvé
✓ ('Braine', 'Braine, Aisne, France') → France
✓ ('Amérique', 'Amérique') →
✓ ('Antraigues-sur-Volane', 'Antraigues-sur-Volane, Ardèche, France') → France
✓ ('Grand Canal', 'Grand Canal, Venise, Italie') → Italie
✓ ('Nouvelle- Zélande', 'Nouvelle-Zélande') → Nouvelle-Zélande
✓ ('16e arrondissement de Paris', '16e arrondissement, Paris, France') → France
✓ ("King's Road", "King's Road, Londres, Royaume-Uni") → Royaume-Uni
✓ ('Munich', 'Munich, Bavière, Allemagne') → Allemagne
✓ ('Ródenas', 'Ródenas, Teruel, Espagne') → Espagne
✓ ('Vaucluse', "Vaucluse, Provence-Alpes-Côte d'Azur, France") → France
✓ ('Notre- Dame du Finistère', 'Notre-Dame du Finistère, Bruxelles, Belgique') → Belgique
✓ ('Tonkin', 'Tonkin, Hanoï, Vietnam') → Viêt Nam
✓ ('Johannesbourg', 'Johannesburg, Johannesburg, Afrique du Sud') → Afrique du Sud
✗ ('Qc J1S', 'J1S, Saint-Hyacinthe, Canada') → non trouvé
✓ ('Saint-Laurent', 'Saint-Laurent, Saint-Laurent, France') → France
✓ ('Stuttgart', 'Stuttgart, Stuttgart, Allemagne') → Allemagne
✓ ('St-Pierre-de-Varengeville', 'Saint-Pierre-de-Varengeville, Rouen, France') → France
✓ ('Nîmes', 'Nîmes, Nîmes, France') → France
✓ ('Béziers', 'Béziers, Béziers, France') → France
✓ ('Dacca', 'Dacca, Dhaka, Bangladesh') → Bangladesh
✗ ('Centre Mémorial des Victimes du Terrorisme de Vitoria', 'Centre Mémorial des Victimes du Terrorisme, Vitoria-Gasteiz, Espagne') → non trouvé
✗ ("Cantons de l'Est", "Cantons de l'Est, Liège, Belgique") → non trouvé
✓ ('château de Fontainebleau', 'Château de Fontainebleau, Fontainebleau, France') → France
✓ ('Saint- Aphrodise', 'Saint-Aphrodise, Béziers, France') → France
✓ ('Sosua', 'Sosúa, Puerto Plata, République dominicaine') → République dominicaine
✓ ('Vaucresson', 'Vaucresson, Vaucresson, France') → France
✓ ('Haut-Rhin', 'Haut-Rhin, Alsace, France') → France
✓ ('Guinée-Bissau', 'Guinée-Bissau, Bissau, Guinée-Bissau') → Guinée-Bissau
✓ ('Paris PARIS', 'Paris, Paris, France') → France
✓ ('La Jonquera', 'La Jonquera, Gérone, Espagne') → Espagne
✓ ('Théâtre du Léman', 'Théâtre du Léman, Genève, Suisse') → Suisse
✓ ('Châteauroux', 'Châteauroux, Indre, France') → France
✓ ('Hamptons', 'The Hamptons, New York, États-Unis') → États-Unis d'Amérique
✓ ('de la Creuse', 'Creuse, Nouvelle-Aquitaine, France') → France
✓ ('Walcourt', 'Walcourt, Namur, Belgique') → Belgique
✓ ('Portsmouth', 'Portsmouth, Hampshire, Royaume-Uni') → Royaume-Uni
✓ ('Montagnac-sur-Lède', 'Montagnac-sur-Lède, Lot-et-Garonne, France') → France
✓ ("Val-d'Or", "Val-d'Or, Québec, Canada") → Canada
✓ ('hôtel des Batignolles', 'Batignolles, Paris, France') → France
✓ ('Grand Montréal', 'Grand Montréal, Québec, Canada') → Canada
✓ ('Bouguenais  Nuit de la lecture  ', 'Bouguenais, Loire-Atlantique, France') → France
✓ ('Angkor Wat', 'Angkor Wat, Siem Reap, Cambodge') → Cambodge
✓ ('Espace Steven Udvar-Hazy', 'Steven F. Udvar-Hazy Center, Chantilly, États-Unis') → États-Unis d'Amérique
✓ ("d'Italie", 'Italie') → Italie
✓ ('Saint- Pétersbourg', 'Saint-Pétersbourg, Saint-Pétersbourg, Russie') → Russie
✓ ('Anatolie', 'Anatolie, Turquie') → Turquie
✓ ('Larsa', 'Larsa, Dhi Qar, Irak') → Irak
✓ ('Porto Rico', 'Porto Rico, Porto Rico, États-Unis') → États-Unis d'Amérique
✓ ('Seraing', 'Seraing, Liège, Belgique') → Belgique
✓ ('Haute-Garonne', 'Haute-Garonne, Occitanie, France') → France
✓ ('Bonsecours', 'Bonsecours, Rouen, France') → France
✓ ('Peshawar', 'Peshawar, Peshawar, Pakistan') → Pakistan
✓ ('Lyssytchansk', 'Lyssytchansk, Lyssytchansk, Ukraine') → Ukraine
✓ ('Sorbonne', 'Sorbonne, Paris, France') → France
✓ ('Dorion', 'Dorion, Vaudreuil-Dorion, Canada') → Canada
✗ ('Nollywood', 'Nollywood, Lagos, Nigeria') → non trouvé
✗ ('Assise', 'Assise, Assise, Italie') → non trouvé
✓ ('rue de Solférino', 'rue de Solférino, Paris, France') → France
✓ ('Vire', 'Vire, Vire-Normandie, France') → France
✓ ('Viarme', 'Place Viarme, Nantes, France') → France
✓ ('La Conciergerie', 'La Conciergerie, Paris, France') → France
✓ ('6 rue Grolée', '6 rue Grolée, Lyon, France') → France
✗ ("l'Asie", 'Asie, null, null') → non trouvé
✓ ('Communauté urbaine de Niamey', 'Communauté urbaine de Niamey, Niamey, Niger') → Niger
✗ ('rue Sainte-Catherine', 'rue Sainte-Catherine, null, null') → non trouvé
✓ ('boulevard Poissonnière', 'boulevard Poissonnière, Paris, France') → France
✓ ('Fransures', 'Fransures, Fransures, France') → France
✓ ('Commanderie de Lavausseau', 'Commanderie de Lavausseau, Lavausseau, France') → France
✓ ('Namur', 'Namur, Namur, Belgique') → Belgique
✗ ('Santa Teresa', 'Santa Teresa, null, null') → non trouvé
✓ ('Kobe', 'Kobe, Kobe, Japon') → Japon
✗ ('place Saint-Denis', 'place Saint-Denis, null, null') → non trouvé
✗ ('Liban', 'Liban, null, Liban') → non trouvé
✓ ('forêt de Niamey', 'forêt de Niamey, Niamey, Niger') → Niger
✗ ('Saint-Michel', 'Saint-Michel, null, null') → non trouvé
✓ ('escort-girls du Carlton de Lille', 'Carlton, Lille, France') → France
✓ ('passage du Havre - friand', 'Passage du Havre, Paris, France') → France
✓ ('Bangladesh', 'Bangladesh, Bangladesh, Bangladesh') → Bangladesh
✓ ('Kilimandjaro', 'Kilimandjaro, Kilimandjaro, Tanzanie') → Tanzanie
✓ ('Darling', 'Darling, Western Cape, Afrique du Sud') → Afrique du Sud
✗ ('fédération des Emirats arabes unis', 'Émirats arabes unis, Émirats arabes unis, Émirats arabes unis') → non trouvé
✓ ('Saint-Hyacinthe', 'Saint-Hyacinthe, Saint-Hyacinthe, Canada') → Canada
✓ ('Kazeroun', 'Kazeroun, Fars, Iran') → Iran
✓ ('Suisse)/DAMAS', 'Damas, Damas, Syrie') → Syrie
✓ ('Téhéran', 'Téhéran, Téhéran, Iran') → Iran
✗ ('Akkad', 'Akkad, Akkad, Irak') → non trouvé
✗ ('Tibéhirine', 'Tibéhirine, Médéa, Algérie') → non trouvé
✗ ('Théâtre du Trident', 'Théâtre du Trident, Québec, Canada') → non trouvé
✓ ('Villa Grimaldi', 'Villa Grimaldi, Santiago, Chili') → Chili
✓ ('Sardes', 'Sardes, Sart, Turquie') → Turquie
✓ ('Lituanie', 'Lituanie, Europe') → Lituanie
✓ ('Alleud', 'Alleud, Brabant wallon, Belgique') → Belgique
✓ ('place de la République', 'Place de la République, Paris, France') → France
✓ ('Rio', 'Rio de Janeiro, Rio de Janeiro, Brésil') → Brésil
✗ ('église Sainte-Marie-des-Anges de Wellington', 'Église Sainte-Marie-des-Anges, Wellington, Nouvelle-Zélande') → non trouvé
✓ ('Belfast', 'Belfast, Belfast, Royaume-Uni') → Royaume-Uni
✓ ('Charleville- Mézières', 'Charleville-Mézières, Ardennes, France') → France
✗ ('place Saint-Pierre', 'Place Saint-Pierre, Rome, Italie') → non trouvé
✓ ('de Besançon', 'Besançon, Doubs, France') → France
✓ ('Sains', 'Sains, Hauts-de-France, France') → France
✓ ('Villejuif', 'Villejuif, Val-de-Marne, France') → France
✓ ('Issoire', 'Issoire, Issoire, France') → France
✓ ('Oka', 'Oka, Oka, Canada') → Canada
✓ ('Plainpalais', 'Plainpalais, Genève, Suisse') → Suisse
✓ ('Volubilis', 'Volubilis, Meknès, Maroc') → Maroc
✓ ('Utley', 'Utley, Texas, États-Unis') → États-Unis d'Amérique
✓ ("Quai d'Orsay", "Quai d'Orsay, Paris, France") → France
✓ ('Sotteville-lès-Rouen', 'Sotteville-lès-Rouen, Rouen, France') → France
✓ ('Caire -', 'Le Caire, Le Caire, Égypte') → Égypte
✓ ('Almeria', 'Almería, Almería, Espagne') → Espagne
✗ ('Everest', 'Mont Everest, Himalaya, Népal/Chine') → non trouvé
✓ ('Saint-Lunaire', 'Saint-Lunaire, Saint-Lunaire, France') → France
✓ ('Bresse', 'Bresse, Bourg-en-Bresse, France') → France
✓ ('TNP de Chaillot', 'Palais de Chaillot, Paris, France') → France
✓ ("Etat d'Edo", "État d'Edo, Benin City, Nigeria") → Nigéria
✓ ('rue Francis-de-Pressensé', 'rue Francis-de-Pressensé, France') → France
✓ ('boulevard de Bonne-Nouvelle', 'boulevard de Bonne-Nouvelle, Paris, France') → France
✓ ('Larzac', 'Larzac, Occitanie, France') → France
✓ ('Buenos Aires', 'Buenos Aires, Buenos Aires, Argentine') → Argentine
✓ ('Picardie', 'Picardie, France') → France
✓ ('rue de la Barbinais', 'rue de la Barbinais, France') → France
✗ ('Pôle Nord', 'Pôle Nord, Arctique') → non trouvé
✓ ('Puilboreau', 'Puilboreau, Nouvelle-Aquitaine, France') → France
✓ ('La Havane', 'La Havane, La Havane, Cuba') → Cuba
✓ ('Amérique du sud', 'Amérique du Sud') →
✓ ('Cameroun', 'Cameroun, Afrique') → Cameroun
✓ ('Montréal-Nord', 'Montréal-Nord, Montréal, Canada') → Canada
✓ ('Turin', 'Turin, Turin, Italie') → Italie
✓ ('Noisy-le-Sec', 'Noisy-le-Sec, Seine-Saint-Denis, France') → France
✓ ('Rosendaël', 'Rosendaël, Dunkerque, France') → France
✓ ('Région de Brest', 'Région de Brest, Brest, France') → Bélarus
✓ ('Auxerre', 'Auxerre, Yonne, France') → France
✓ ("l'Italie", 'Italie, Europe') → Italie
✓ ('Cap Canaveral', 'Cap Canaveral, Floride, États-Unis') → États-Unis d'Amérique
✗ ('Rosette', 'Rosette, Alexandrie, Égypte') → non trouvé
✓ ('Jonzac', 'Jonzac, Charente-Maritime, France') → France
✗ ('Nil', 'Nil, Afrique du Nord-Est') → non trouvé
✓ ('Tanger', 'Tanger, Tanger-Tétouan-Al Hoceïma, Maroc') → Maroc
✓ ('commissariat de Milan', 'Milan, Milan, Italie') → Italie
✓ ('université de Lille', 'Université de Lille, Lille, France') → France
✓ ('Hollywood', 'Hollywood, Los Angeles, États-Unis') → États-Unis d'Amérique
✓ ('Bouligny', 'Bouligny, Meuse, France') → France
✓ ('Grand-Couronne', 'Grand-Couronne, Seine-Maritime, France') → France
✓ ('Ravenne', 'Ravenne, Émilie-Romagne, Italie') → Italie
✓ ('OSWIECIM', 'Oświęcim, Petite-Pologne, Pologne') → Pologne
✓ ('Haute Gironde', 'Haute Gironde, Gironde, France') → France
✓ ('Théâtre de La Fenice', 'Teatro La Fenice, Venise, Italie') → Italie
✓ ('Saint-Genès-de-Castillon', 'Saint-Genès-de-Castillon, Gironde, France') → France
✓ ("cour d'appel de Toulouse", 'Toulouse, Haute-Garonne, France') → France
✓ ('Fréjus', 'Fréjus, Var, France') → France
✓ ('Ille-et-Vilaine', 'Ille-et-Vilaine, Bretagne, France') → France
✓ ('Est de la France', 'Est, France') → France
✓ ('Rivesaltes', 'Rivesaltes, Perpignan, France') → France
✓ ('brie', 'Brie, Île-de-France, France') → France
✓ ('Sorgues', 'Sorgues, Avignon, France') → France
✓ ('la Défense', 'La Défense, Paris, France') → France
✓ ('Oregon', 'Oregon, États-Unis') → États-Unis d'Amérique
✗ ('Sainte-Foy', 'Sainte-Foy, Bordeaux, France') → non trouvé
✓ ('Monastère royal de Brou', 'Monastère royal de Brou, Bourg-en-Bresse, France') → France
✓ ('Grasse', 'Grasse, Alpes-Maritimes, France') → France
✓ ('Lamorlaye', 'Lamorlaye, Oise, France') → France
✓ ('Estavayer-le-Lac', 'Estavayer-le-Lac, Fribourg, Suisse') → Suisse
✓ ('aéroport de Moscou', 'Aéroport de Moscou, Moscou, Russie') → Russie
✓ ('Sainte-Catherine Est', 'Sainte-Catherine-Est, Québec, Canada') → Canada
✓ ('Milizac', 'Milizac, Finistère, France') → France
✗ ('Turkménistan', 'Turkménistan, Asie centrale, Turkménistan') → non trouvé
✓ ('Bellecroix', 'Bellecroix, Metz, France') → France
✗ ('mer du Japon', "Mer du Japon, Asie de l'Est, null") → non trouvé
✓ ('Champagne', 'Champagne, Grand Est, France') → France
✓ ('Saint-Sébastien', 'Saint-Sébastien, Pays basque, Espagne') → Espagne
✓ ('Aprilia', 'Aprilia, Latium, Italie') → Italie
✓ ('- PRETORIA', 'Pretoria, Pretoria, Afrique du Sud') → Afrique du Sud
✓ ('Parc Corot', "Parc Corot, Ville-d'Avray, France") → France
✓ ('Ibiza', 'Ibiza, Ibiza, Espagne') → Espagne
✗ ("l'Amérique", 'null, null, Amérique') → non trouvé
✓ ('Islamabad', 'Islamabad, Islamabad, Pakistan') → Pakistan
✓ ('Brenouille', 'Brenouille, Brenouille, France') → France
✓ ('Palais- Royal', 'Palais-Royal, Paris, France') → France
✓ ('Porte Dorée', 'Porte Dorée, Paris, France') → France
✓ ('Fort-de- la-Briche', 'Fort de la Briche, Saint-Denis, France') → France
✓ ('Seine Saint Denis)', 'Seine-Saint-Denis, Seine-Saint-Denis, France') → France
✓ ('Koweït', 'Koweït, Koweït, Koweït') → Koweït
✓ ('Somaliland', 'Somaliland, Hargeisa, Somaliland') → Somaliland
✓ ('Champ de Mars', 'Champ de Mars, Paris, France') → France
✓ ('Kandahar', 'Kandahar, Kandahar, Afghanistan') → Afghanistan
✓ ('Haute-Savoie', 'Haute-Savoie, Annecy, France') → France
✓ ('Bulgarie', 'Bulgarie, Sofia, Bulgarie') → Bulgarie
✓ ('Ahuntsic', 'Ahuntsic, Montréal, Canada') → Canada
✗ ('Pays Bas', 'Pays-Bas, Amsterdam, Pays-Bas') → non trouvé
✓ ('Colombie-Britannique', 'Colombie-Britannique, Victoria, Canada') → Canada
✓ ('Salon-de-Provence', 'Salon-de-Provence, Salon-de-Provence, France') → France
✓ ('Douaisien', 'Douai, Douai, France') → France
✓ ('Mont-de-Marsan', 'Mont-de-Marsan, Mont-de-Marsan, France') → France
✓ ('Bougue', 'Bougue, Mont-de-Marsan, France') → France
✓ ('Ardennes', 'Ardennes, Charleville-Mézières, France') → France
✓ ('arrondissement Beauport', 'Beauport, Québec, Canada') → Canada
✓ ('A Doullens', 'Doullens, Amiens, France') → France
✓ ('Gingins', 'Gingins, Nyon, Suisse') → Suisse
✓ ('Vendée', 'Vendée, La Roche-sur-Yon, France') → France
✓ ('gare de Dourdan', 'Dourdan, Île-de-France, France') → France
✗ ('place Tahrir', 'Place Tahrir, Le Caire, Égypte') → non trouvé
✓ ('Suisse-enchères-château-Gallé GENEVE', 'Genève, Genève, Suisse') → Suisse
✓ ('Deûle', 'Deûle, Lille, France') → France
✗ ('Charleroi-Central', 'Gare de Charleroi-Central, Charleroi, Belgique') → non trouvé
✓ ('Bayern', 'Bavière, Allemagne') → Allemagne
✓ ("Plans d'Hotonnes", "Plans d'Hotonnes, Auvergne-Rhône-Alpes, France") → France
✓ ('du Gard', 'Gard, Occitanie, France') → France
✓ ('Saône-et-Loire', 'Saône-et-Loire, Bourgogne-Franche-Comté, France') → France
✓ ('Glasgow', 'Glasgow, Écosse, Royaume-Uni') → Royaume-Uni
✓ ('Cahors', 'Cahors, Occitanie, France') → France
✓ ('Hérault', 'Hérault, Occitanie, France') → France
✓ ('Palazzo Grassi', 'Palazzo Grassi, Venise, Italie') → Italie
✓ ('Stenay', 'Stenay, Grand Est, France') → France
✓ ('Fessenheim', 'Fessenheim, Grand Est, France') → France
✓ ('Taj Mahal', 'Taj Mahal, Agra, Inde') → Inde
✓ ('place Gambetta', 'Place Gambetta, Paris, France') → France
✗ ('mer Méditerranée', 'Mer Méditerranée, null, null') → non trouvé
✓ ("palais de l'Elysée", "Palais de l'Élysée, Paris, France") → France
✓ ("cour d'appel de Rouen Illustration(s", "Cour d'appel de Rouen, Rouen, France") → France
✓ ('Villers-Cotterêts', 'Villers-Cotterêts, Villers-Cotterêts, France') → France
✓ ('MJC Ménival', 'MJC Ménival, Lyon, France') → France
✓ ('MONTREUIL', 'Montreuil, Montreuil, France') → France
✓ ('quartier du Sentier', 'Quartier du Sentier, Paris, France') → France
✓ ('Palais Royal', 'Palais-Royal, Paris, France') → France
✓ ('MontgeneèveProposé', 'Montgenèvre, Hautes-Alpes, France') → France
✓ ('New York', 'New York, New York, États-Unis') → États-Unis d'Amérique
✓ ('Mervelier', 'Mervelier, Delémont, Suisse') → Suisse
✓ ('Eure-et-Loir', 'Eure-et-Loir, Centre-Val de Loire, France') → France
✓ ('Katorza', 'Nantes, Loire-Atlantique, France') → France
✓ ('Villaverde', 'Villaverde, Madrid, Espagne') → Espagne
✗ ('Amazonie', 'Amazonie, Amérique du Sud, Brésil') → non trouvé
✓ ('ploudalmezeau', 'Ploudalmézeau, Finistère, France') → France
✓ ('Lisieux Rendez', 'Lisieux, Calvados, France') → France
✓ ('Saint-Gall', 'Saint-Gall, Saint-Gall, Suisse') → Suisse
✓ ('le Saguenay', 'Saguenay, Saguenay, Canada') → Canada
✓ ('Yukon', 'Yukon, Yukon, Canada') → Canada
✓ ('Corfou', 'Corfou, Corfou, Grèce') → Grèce
✓ ('Florange', 'Florange, Florange, France') → France
✓ ('Altaï', 'Altaï, Altaï, Russie') → Russie
✓ ('Saint-Nazaire', 'Saint-Nazaire, Saint-Nazaire, France') → France
✓ ('Cape Town', 'Cape Town, Cape Town, Afrique du Sud') → Afrique du Sud
✓ ('Kelowna', 'Kelowna, Kelowna, Canada') → Canada
✓ ('La Baie', 'La Baie, Saguenay, Canada') → Canada
✓ ('Sainte-Croix', 'Sainte-Croix, Sainte-Croix, Suisse') → Suisse
✓ ('Campigny', 'Campigny, Normandie, France') → France
✓ ("Val-d'Oise", "Val-d'Oise, Île-de-France, France") → France
✓ ('Albanie', 'Albanie, Europe') → Albanie
✓ ('Philadelphie', 'Philadelphie, Pennsylvanie, États-Unis') → États-Unis d'Amérique
✓ ('Châtelet', 'Châtelet, Hainaut, Belgique') → Belgique
✓ ('Athus', 'Athus, Luxembourg, Belgique') → Belgique
✓ ('Salzbourg', 'Salzbourg, Salzbourg, Autriche') → Autriche
✓ ('villa des Gobelins', 'Villa des Gobelins, Paris, France') → France
✓ ('Arcachon', 'Arcachon, Nouvelle-Aquitaine, France') → France
✓ ('Hauts-Pays', 'Hauts-Pays, Hainaut, Belgique') → Belgique
✓ ('Magog', 'Magog, Québec, Canada') → Canada
✓ ('rue Saint-Honoré', 'Rue Saint-Honoré, Paris, France') → France
✓ ('Salaberry-de-Valleyfield', 'Salaberry-de-Valleyfield, Québec, Canada') → Canada
✓ ('rue Marignan', 'Rue Marignan, Paris, France') → France
✓ ('Calixa-Lavallée', 'Calixa-Lavallée, Québec, Canada') → Canada
✓ ('Poitier', 'Poitiers, Nouvelle-Aquitaine, France') → France
✓ ('Belo Monte', 'Belo Monte, Pará, Brésil') → Brésil
✓ ('Gouvieux', 'Gouvieux, Hauts-de-France, France') → France
✓ ('Dôle', 'Dole, Bourgogne-Franche-Comté, France') → France
✓ ('Columbia', 'Columbia, Caroline du Sud, États-Unis') → États-Unis d'Amérique
✓ ('Kansaï', 'Kansai, Osaka, Japon') → Japon
✓ ('Orange', "Orange, Provence-Alpes-Côte d'Azur, France") → France
✓ ('Ontario Est', "Est de l'Ontario, Ontario, Canada") → Canada
✓ ('Annecy', 'Annecy, Auvergne-Rhône-Alpes, France') → France
✗ ('Sumer', 'Sumer, Mésopotamie, Irak') → non trouvé
✓ ('Bellegarde', 'Bellegarde, Ain, France') → France
✓ ('Pacifique', 'Océan Pacifique') →
✓ ('Malemort', 'Malemort-sur-Corrèze, Corrèze, France') → France
✓ ('Mayotte', 'Mayotte, Mayotte, France') → France
✓ ('Nancy St-Pierre', 'Nancy, Meurthe-et-Moselle, France') → France
✓ ('la Bretagne', 'Bretagne, France') → France
✓ ('CIDIFF Meuse', 'Meuse, Grand Est, France') → France
✓ ('château de Clisson', 'Clisson, Loire-Atlantique, France') → France
✓ ('Egypte-gouvernement LE CAIRE', 'Le Caire, Le Caire, Égypte') → Égypte
✓ ('Libercourt', 'Libercourt, Pas-de-Calais, France') → France
✓ ('Cleveland', 'Cleveland, Ohio, États-Unis') → États-Unis d'Amérique
✓ ('la France', 'France') → France
✗ ("pays d'Égypte", 'Égypte, null, Égypte') → non trouvé
✓ ('San Francisco Mafra', 'Mafra, Mafra, Portugal') → Portugal
✗ ('Mosellan', 'Moselle, null, France') → non trouvé
✗ ('Pays- Bas', 'null, null, Pays-Bas') → non trouvé
✗ ('Madaure', 'Madauros, Mdaourouch, Algérie') → non trouvé
✗ ('Clermont-Limagne', 'Clermont-Limagne, Clermont-Limagne, France') → non trouvé
✓ ('Silly', 'Silly, Silly, Belgique') → Belgique
✓ ('Justitiepaleis Brussel', 'Palais de Justice, Bruxelles, Belgique') → Belgique
✓ ('Caluire', 'Caluire-et-Cuire, Lyon, France') → France
✗ ('La Chine', 'null, null, Chine') → non trouvé
✓ ('Belle Epoque lausannoise', 'Lausanne, Lausanne, Suisse') → Suisse
✓ ('Salies-de-Béarn', 'Salies-de-Béarn, Salies-de-Béarn, France') → France
✗ ('Pays de la loire', 'Pays de la Loire, null, France') → non trouvé
✓ ('Théâtre 100 Noms', 'Théâtre 100 Noms, Nantes, France') → France
✓ ('Charonne', 'Charonne, Paris, France') → France
✗ ('Transmusicales de Rennes', 'Transmusicales de Rennes, Rennes, France') → non trouvé
✓ ('Bordeaux-Sud', 'Bordeaux-Sud, Bordeaux, France') → France
✗ ('îles Senkaku', 'îles Senkaku, îles Senkaku, Mer de Chine orientale') → non trouvé
✓ ('Fumel', 'Fumel, Fumel, France') → France
✓ ('Kergoff', 'Kergoff, Bretagne, France') → France
✓ ('Lacanau', 'Lacanau, Lacanau, France') → France
✓ ('la Meuse', 'la Meuse, Meuse, France') → France
✓ ('Inde', 'Inde, Inde, Inde') → Mexique
✓ ('Provincetown', 'Provincetown, Provincetown, États-Unis') → États-Unis d'Amérique
✓ ('Clermont Limagne', 'Clermont Limagne, Clermont-Ferrand, France') → France
✓ ("Sables d'or", "Sables-d'Or-les-Pins, Fréhel, France") → France
✓ ('Rosemont', 'Rosemont, Montréal, Canada') → Canada

In [122]:
df = pd.DataFrame(resultats)
df.to_csv("corpus/geocodes.csv", index=False)
df.to_parquet("corpus/geocodes.parquet", index=False)

In [110]:
liste_pays

[('Saint-Étienne-du-Rouvray',
  'Saint-Étienne-du-Rouvray, Saint-Étienne-du-Rouvray, France'),
 ('Abou Kémal', 'Abu Kamal, Deir ez-Zor, Syrie'),
 ('Perros-Guirec', 'Perros-Guirec, Perros-Guirec, France'),
 ('Saint-Gaudens', 'Saint-Gaudens, Saint-Gaudens, France'),
 ('Carmel', 'Carmel, Californie, États-Unis'),
 ('Philippines', 'Philippines, Philippines, Philippines'),
 ('Lower Mainland', 'Lower Mainland, Vancouver, Canada'),
 ('Chalon', 'Chalon-sur-Saône, Chalon-sur-Saône, France'),
 ('New York underground', 'New York, New York, États-Unis'),
 ('bibliothèque de Fontevraud',
  "Fontevraud-l'Abbaye, Fontevraud-l'Abbaye, France"),
 ('Bordeaux Rive Gauche', 'Bordeaux Rive Gauche, Bordeaux, France'),
 ('MONTLUCON', 'Montluçon, Montluçon, France'),
 ("Europe de l'Est", "Europe de l'Est"),
 ('Kamogawa', 'Kamogawa, Kamogawa, Japon'),
 ('Lens', 'Lens, Lens, France'),
 ('Calcuta', 'Kolkata, Kolkata, Inde'),
 ('rue Saint-Martin', 'Rue Saint-Martin, Paris, France'),
 ("green d'Augusta", 'Augusta National Golf Club, Augusta, États-Unis'),
 ("L'Espagne", 'Espagne, Espagne, Espagne'),
 ('Bruxelles', 'Bruxelles, Bruxelles, Belgique'),
 ('Broadway', 'Broadway, New York, États-Unis'),
 ('Valserine', 'Valserine, Ain, France'),
 ('Odéon', 'Odéon, Paris, France'),
 ('Louvigné-du-Désert', 'Louvigné-du-Désert, Fougères, France'),
 ("Côte d'Ivoire", "Côte d'Ivoire, Afrique de l'Ouest"),
 ('Finistère', 'Finistère, Quimper, France'),
 ('LISBONNE', 'Lisbonne, Lisbonne, Portugal'),
 ('Basilique Saint-Pierre', 'Basilique Saint-Pierre, Vatican, Vatican'),
 ('Khabarovsk', 'Khabarovsk, Khabarovsk, Russie'),
 ('Le Havre', 'Le Havre, Le Havre, France'),
 ('Théâtre de Gennevilliers',
  'Théâtre de Gennevilliers, Gennevilliers, France'),
 ('Montmartre', 'Montmartre, Paris, France'),
 ('Gonesse', 'Gonesse, Gonesse, France'),
 ('Orlando', 'Orlando, Orlando, États-Unis'),
 ('rue Bruat', 'rue Bruat, ville inconnue, France'),
 ('Centrafrique', 'Centrafrique, Bangui, République centrafricaine'),
 ('Woodlands', 'Woodlands, Singapour, Singapour'),
 ('Gagnoa', "Gagnoa, Gagnoa, Côte d'Ivoire"),
 ('la Bolivie', 'Bolivie, Sucre, Bolivie'),
 ('Ekallatum', 'Ekallatum, site antique, Irak'),
 ("Val de l'Aurence", "Val de l'Aurence, Limoges, France"),
 ('Brésil', 'Brésil, Brasília, Brésil'),
 ("L'Elysée", "Palais de l'Élysée, Paris, France"),
 ('lycée Thiers', 'Lycée Thiers, Marseille, France'),
 ('Mangin île Beaulieu', 'Île Beaulieu, Nantes, France'),
 ('Strasbourg', 'Strasbourg, Strasbourg, France'),
 ('Turque', 'Turquie'),
 ("canal de l'Ourcq", "Canal de l'Ourcq, Paris, France"),
 ('Métro Saint-Laurent', 'Station Saint-Laurent, Montréal, Canada'),
 ("université d'Orléans", "Université d'Orléans, Orléans, France"),
 ('RD du Congo', 'République Démocratique du Congo'),
 ('Victor-Lagrange', 'Victor-Lagrange, Lyon, France'),
 ('Oregon City', 'Oregon City, Oregon, États-Unis'),
 ('Tala', 'Tala, Pune, Inde'),
 ('Arras', 'Arras, Arras, France'),
 ('Elvas', 'Elvas, Elvas, Portugal'),
 ('Coudekerque-Branche', 'Coudekerque-Branche, Coudekerque-Branche, France'),
 ('Lusaka', 'Lusaka, Lusaka, Zambie'),
 ('Île Guérandaise', 'Île Guérandaise, Guérande, France'),
 ('Ain', 'Ain, Bourg-en-Bresse, France'),
 ('Donbass', 'Donbass, Donbass, Ukraine'),
 ('Auvergne-Rhône-Alpes', 'Auvergne-Rhône-Alpes, Lyon, France'),
 ('argentine', 'Argentine, Buenos Aires, Argentine'),
 ('Welfare Island', 'Roosevelt Island, New York, États-Unis'),
 ('Sarthe', 'Sarthe, Pays de la Loire, France'),
 ('RAMALLAH', 'Ramallah, Ramallah, Palestine'),
 ('Saint-Lambert-la-Potherie',
  'Saint-Lambert-la-Potherie, Maine-et-Loire, France'),
 ('Windsor', 'Windsor, Berkshire, Royaume-Uni'),
 ('-Etats-Unis', 'États-Unis'),
 ('Cap Vert', 'Cap-Vert, Cap-Vert'),
 ('Saint-Valentin', 'Saint-Valentin, Indre, France'),
 ('Bonneville', 'Bonneville, Haute-Savoie, France'),
 ('KANO', 'Kano, Kano, Nigeria'),
 ('Loire- Atlantique', 'Loire-Atlantique, Pays de la Loire, France'),
 ('rue Oehlenschlægersgade', 'Oehlenschlægersgade, Copenhague, Danemark'),
 ("porte d'Anvers", "Porte d'Anvers, Bruxelles, Belgique"),
 ('Saguenay', 'Saguenay, Saguenay, Canada'),
 ('Nouméa', 'Nouméa, Nouméa, Nouvelle-Calédonie'),
 ('Estuaire', 'Estuaire, Libreville, Gabon'),
 ('Portugal de Salazar', 'Portugal, Lisbonne, Portugal'),
 ('Neuchâtel', 'Neuchâtel, Neuchâtel, Suisse'),
 ('Crouy-sur-Ourcq', 'Crouy-sur-Ourcq, Meaux, France'),
 ('Mayenne', 'Mayenne, Mayenne, France'),
 ('Catalogne', 'Catalogne, Barcelone, Espagne'),
 ('Ohio', 'Ohio, Columbus, États-Unis'),
 ('Maine', 'Maine, Augusta, États-Unis'),
 ('Madrilènes', 'Madrid, Madrid, Espagne'),
 ('Las Palmas', 'Las Palmas, Las Palmas de Gran Canaria, Espagne'),
 ('Saint-Cannat', 'Saint-Cannat, Aix-en-Provence, France'),
 ('précieuse Marbella', 'Marbella, Marbella, Espagne'),
 ('Viré', 'Viré, Saône-et-Loire, France'),
 ('Herat', 'Herat, Herat, Afghanistan'),
 ('esplanade Francois Mitterand',
  'Esplanade François Mitterrand, Paris, France'),
 ('ABEBA', 'Addis-Abeba, Addis-Abeba, Éthiopie'),
 ('La Baule', 'La Baule-Escoublac, Loire-Atlantique, France'),
 ('canton de Neuchâtel', 'Neuchâtel, Canton de Neuchâtel, Suisse'),
 ('Pyrénées', 'Pyrénées, , France/Espagne'),
 ('Lac-Etchemin', 'Lac-Etchemin, Chaudière-Appalaches, Canada'),
 ('Saint-Mesmes', 'Saint-Mesmes, Seine-et-Marne, France'),
 ('Miribel  ', 'Miribel, Ain, France'),
 ('Vilnius', 'Vilnius, Vilnius, Lituanie'),
 ("Marins d'Iroise", "Mer d'Iroise, Finistère, France"),
 ('commissariat de Roanne', 'Roanne, Loire, France'),
 ('Bic', 'Bic, Bas-Saint-Laurent, Canada'),
 ('SAINTES', 'Saintes, Nouvelle-Aquitaine, France'),
 ('Abuja', 'Abuja, Abuja, Nigeria'),
 ('Bade', 'Bade, Bade-Wurtemberg, Allemagne'),
 ('Saut de la Mounine', 'Saut de la Mounine, Lot, France'),
 ('Perrache', 'Perrache, Lyon, France'),
 ('Ambert', 'Ambert, Auvergne-Rhône-Alpes, France'),
 ('Bar-le-Duc', 'Bar-le-Duc, Grand Est, France'),
 ("Penmarc'h.", "Penmarc'h, Bretagne, France"),
 ('Italie', 'Italie'),
 ('Granma', 'Granma, Granma, Cuba'),
 ('Bristol', 'Bristol, Angleterre, Royaume-Uni'),
 ('St-Arnaud', 'Saint-Arnaud, Nouvelle-Galles du Sud, Australie'),
 ('Véragne', 'Véragne, Savoie, France'),
 ('Chalamont', 'Chalamont, Ain, France'),
 ('Binic', "Binic, Côtes-d'Armor, France"),
 ('parvis de Notre-Dame', 'Parvis de Notre-Dame, Paris, France'),
 ('Créteil Rouzerol-Douglas', 'Créteil, Val-de-Marne, France'),
 ('Beaudry', 'Beaudry, Montréal, Canada'),
 ('Ferney-Voltaire', 'Ferney-Voltaire, Ain, France'),
 ('théâtre du Pont-Tournant', 'Théâtre du Pont-Tournant, Bordeaux, France'),
 ('boulevard Dugommier', 'Boulevard Dugommier, Marseille, France'),
 ('Dioulas', 'Dioulas, Brest, France'),
 ("l'Afrique du Sud", 'Afrique du Sud'),
 ('Océanie', 'Océanie'),
 ("l'Afrique", 'Afrique, null, null'),
 ('Tajikistan', 'Tadjikistan'),
 ('Littoral', 'Littoral, Cameroun'),
 ('Le Pays basque', 'Pays basque, Espagne/France'),
 ('Souk Ahras', 'Souk Ahras, Souk Ahras, Algérie'),
 ('Laurentides', 'Laurentides, Québec, Canada'),
 ('Santander', 'Santander, Cantabrie, Espagne'),
 ('Comédie de Lille', 'Lille, Hauts-de-France, France'),
 ('Gijón', 'Gijón, Asturies, Espagne'),
 ('Tour-Eiffel', 'Tour Eiffel, Paris, France'),
 ('Riedisheim', 'Riedisheim, Haut-Rhin, France'),
 ('Trabzon', 'Trabzon, Trabzon, Turquie'),
 ('Afrique du sud', 'Afrique du Sud'),
 ('Kentucky', 'Kentucky, États-Unis'),
 ('Drôme', 'Drôme, Valence, France'),
 ('Laon', 'Laon, Laon, France'),
 ('Woodstock', 'Woodstock, Woodstock, États-Unis'),
 ('Ekaterinburg', 'Ekaterinburg, Ekaterinburg, Russie'),
 ('boulevard Montmartre', 'Boulevard Montmartre, Paris, France'),
 ('Haasdonk', 'Haasdonk, Beveren, Belgique'),
 ('Baumettes', 'Baumettes, Marseille, France'),
 ("Conservatoire d'Avignon", "Conservatoire d'Avignon, Avignon, France"),
 ('Bazar de la Charité', 'Bazar de la Charité, Paris, France'),
 ('rue de la Juiverie', 'rue de la Juiverie, Paris, France'),
 ("hôpital Saint-Jean d'Arras", "hôpital Saint-Jean d'Arras, Arras, France"),
 ('Rochefort ~ Oléron',
  "Rochefort-sur-Mer / Île d'Oléron, Charente-Maritime, France"),
 ('Rome', 'Rome, Rome, Italie'),
 ('Troie', 'Troie, Çanakkale, Turquie'),
 ('aéroport de Roissy',
  'Aéroport Charles-de-Gaulle, Roissy-en-France, France'),
 ('Finlande', 'Finlande, Finlande, Finlande'),
 ('Anticosti', "Île d'Anticosti, Québec, Canada"),
 ('Boussoufa', 'Boussoufa, Médenine, Tunisie'),
 ('Troodos', 'Massif du Troodos, Limassol, Chypre'),
 ("Val- d'Oise", "Val-d'Oise, Île-de-France, France"),
 ('rue de Tocqueville', 'rue de Tocqueville, Paris, France'),
 ("aéroport d'Orly", "Aéroport d'Orly, Orly, France"),
 ('Meuse', 'Meuse, Grand Est, France'),
 ('Cévennes', 'Cévennes, Occitanie, France'),
 ("Cap d'Agde", "Cap d'Agde, Agde, France"),
 ('Papouasie-Nouvelle-Guinée',
  'Papouasie-Nouvelle-Guinée, Port Moresby, Papouasie-Nouvelle-Guinée'),
 ('Saint-Galmier', 'Saint-Galmier, Loire, France'),
 ('Rueil-Malmaison', 'Rueil-Malmaison, Hauts-de-Seine, France'),
 ('Stains', 'Stains, Seine-Saint-Denis, France'),
 ('Montataire', 'Montataire, Oise, France'),
 ('gare de Cluj', 'Gare de Cluj, Cluj-Napoca, Roumanie'),
 ('Ouchy', 'Ouchy, Lausanne, Suisse'),
 ("Noirmoutier-en-l'Île Rendez", "Noirmoutier-en-l'Île, Vendée, France"),
 ('Ville de Laval', 'Laval, Mayenne, France'),
 ('Saint-Yrieix-la-Perche', 'Saint-Yrieix-la-Perche, Haute-Vienne, France'),
 ('Bissau', 'Bissau, Bissau, Guinée-Bissau'),
 ('Hong-Kong', 'Hong Kong, Hong Kong, Chine'),
 ("Goutte-d'Or", "Goutte-d'Or, Paris, France"),
 ('Monza', 'Monza, Monza, Italie'),
 ('Terres-de-Borde', 'Terres-de-Borde, Gironde, France'),
 ('Clairefontaine', 'Clairefontaine-en-Yvelines, Yvelines, France'),
 ('Moncalieri', 'Moncalieri, Turin, Italie'),
 ('musée Grévin', 'Musée Grévin, Paris, France'),
 ('Griffintown', 'Griffintown, Montréal, Canada'),
 ('Bergeracois', 'Bergerac, Dordogne, France'),
 ('Berkendael', 'Berkendael, Saint-Gilles, Belgique'),
 ('Fort Montbarey', 'Fort Montbarey, Brest, France'),
 ('Sagy', "Sagy, Val-d'Oise, France"),
 ('Bangkok', 'Bangkok, Bangkok, Thaïlande'),
 ('Aire-sur-la-Lys', 'Aire-sur-la-Lys, Pas-de-Calais, France'),
 ('Alberta', 'Alberta, Alberta, Canada'),
 ('Mulhouse', 'Mulhouse, Haut-Rhin, France'),
 ('Boulogne  Paris', 'Boulogne-Billancourt, Île-de-France, France'),
 ('Hochelaga-  Maisonneuve', 'Hochelaga-Maisonneuve, Montréal, Canada'),
 ('Hauts-Cantons', 'Hauts-Cantons, Estrie, Canada'),
 ('Montérégie', 'Montérégie, Québec, Canada'),
 ('TETOUAN', 'Tétouan, Tétouan-Al Hoceïma-Taza, Maroc'),
 ('Hubei', 'Hubei, Hubei, Chine'),
 ('Pyongyang', 'Pyongyang, Pyongyang, Corée du Nord'),
 ("l'Elysée", "Palais de l'Élysée, Paris, France"),
 ('Khao San Road', 'Khao San Road, Bangkok, Thaïlande'),
 ('Ndolo', 'Ndolo, Kinshasa, République démocratique du Congo'),
 ('Dar es-', 'Dar es-Salaam, Dar es-Salaam, Tanzanie'),
 ('Genève', 'Genève, Genève, Suisse'),
 ('Reims', 'Reims, Reims, France'),
 ('Vitry', 'Vitry-sur-Seine, Vitry-sur-Seine, France'),
 ('Talence', 'Talence, Bordeaux, France'),
 ('Bénin', 'Bénin, Bénin, Bénin'),
 ('Gomery', 'Gomery, Virton, Belgique'),
 ('Ambérieu', 'Ambérieu-en-Bugey, Ambérieu-en-Bugey, France'),
 ('Polynésie française', 'Polynésie française, Papeete, France'),
 ('baie de Ficajola', 'baie de Ficajola, Piana, France'),
 ('Orvault', 'Orvault, Nantes, France'),
 ('Bangalore', 'Bangalore, Bangalore, Inde'),
 ("île d'Anjouan", "île d'Anjouan, Mutsamudu, Comores"),
 ('Fruit(Canada', 'Canada, Canada, Canada'),
 ('Alpes-Maritimes', 'Alpes-Maritimes, France'),
 ('cathédrale Saint-Étienne', 'Cathédrale Saint-Étienne, Metz, France'),
 ('Var', 'Var, France'),
 ('Sousse', 'Sousse, Sousse, Tunisie'),
 ('Niort', 'Niort, Deux-Sèvres, France'),
 ('Bretagne', 'Bretagne, France'),
 ('Coquelle', 'Coquelles, Pas-de-Calais, France'),
 ('Sablette', 'La Sablette, La Seyne-sur-Mer, France'),
 ('Porto Rotondo', 'Porto Rotondo, Sardaigne, Italie'),
 ('musées du Louvre', 'Musée du Louvre, Paris, France'),
 ('Saint-Chamond', 'Saint-Chamond, Loire, France'),
 ('Taiwan', 'Taïwan, Taïwan'),
 ('mer du Nord', 'Mer du Nord, Europe'),
 ('bayonne', 'Bayonne, Bayonne, France'),
 ('Parthenay', 'Parthenay, Parthenay, France'),
 ('Coursaudière', 'Coursaudière, null, France'),
 ('Sos', 'Sos, Sos, France'),
 ('Hautes-Alpes', 'Hautes-Alpes, null, France'),
 ('Promenades boulevard de la Chalotais',
  'Boulevard de la Chalotais, Rennes, France'),
 ('Courbefy', 'Courbefy, Cheissoux, France'),
 ('Lompret', 'Lompret, Lompret, France'),
 ('musée Gustave-Moreau', 'Musée Gustave-Moreau, Paris, France'),
 ('LIMOGES', 'Limoges, Limoges, France'),
 ('rue Coat-ar-Guéven', 'Rue Coat-ar-Guéven, Brest, France'),
 ('Le Coq', 'Le Coq, De Haan, Belgique'),
 ('Canal de Suez', 'Canal de Suez, null, Égypte'),
 ('Auriol', 'Auriol, Bouches-du-Rhône, France'),
 ('boulevard de Châtenay', 'Boulevard de Châtenay, Paris, France'),
 ('Belcier', 'Belcier, Bordeaux, France'),
 ('Boos', 'Boos, Seine-Maritime, France'),
 ('Strasbourg-Saint-Denis', 'Strasbourg-Saint-Denis, Paris, France'),
 ('lac de Genève', 'Lac de Genève, Genève, Suisse'),
 ('Riviera', "Riviera, Côte d'Azur, France"),
 ('boulevard des Capucines', 'Boulevard des Capucines, Paris, France'),
 ('Le Puy-en-Velay Grande', 'Le Puy-en-Velay, Haute-Loire, France'),
 ('Aude', 'Aude, Occitanie, France'),
 ('Bosnie-Herzégovine', 'Bosnie-Herzégovine, Balkans, Europe'),
 ('Savenay', 'Savenay, Savenay, France'),
 ('centre-Bretagne', 'Centre-Bretagne, Bretagne, France'),
 ('Villa Tugendhat', 'Villa Tugendhat, Brno, République tchèque'),
 ('Iraq', 'Irak, Irak, Irak'),
 ('outre-Manche', 'Outre-Manche, Royaume-Uni, Royaume-Uni'),
 ('Neufchâtel', 'Neufchâtel, Neufchâtel-en-Bray, France'),
 ('Emmaüs Gratte-Ciel', 'Emmaüs Gratte-Ciel, Villeurbanne, France'),
 ("Villeneuve-d'Ascq", "Villeneuve-d'Ascq, Villeneuve-d'Ascq, France"),
 ('château de Vincennes', 'Château de Vincennes, Vincennes, France'),
 ('université Paris-VIII', 'Université Paris-VIII, Saint-Denis, France'),
 ('Shaolin', 'Shaolin, Dengfeng, Chine'),
 ('Lexington', 'Lexington, Lexington, États-Unis'),
 ('île Monsin', 'Île Monsin, Liège, Belgique'),
 ("Musée d'art moderne de New York",
  "Musée d'art moderne de New York, New York, États-Unis"),
 ('Égypte', 'Égypte'),
 ('Tigre', 'Tigre, Buenos Aires, Argentine'),
 ("L'Italie", 'Italie'),
 ('Pont-Tournant de Bordeaux', 'Pont-Tournant, Bordeaux, France'),
 ('du Flon', 'Flon, Lausanne, Suisse'),
 ('Mourmansk', 'Mourmansk, Mourmansk, Russie'),
 ('Palerme Palerme DE NOTRE', 'Palerme, Palerme, Italie'),
 ('Tonara', 'Tonara, Nuoro, Italie'),
 ('Grands Boulevards', 'Grands Boulevards, Paris, France'),
 ('mont Vinson', 'Mont Vinson, Antarctique'),
 ('Mondeville', 'Mondeville, Caen, France'),
 ('Porte de Versailles', 'Porte de Versailles, Paris, France'),
 ('Valenciennes', 'Valenciennes, Valenciennes, France'),
 ('Nantua', 'Nantua, Nantua, France'),
 ('rue Doudeauville', 'rue Doudeauville, Paris, France'),
 ('Galfingue', 'Galfingue, Mulhouse, France'),
 ('Tibet', 'Tibet, Tibet, Chine'),
 ('221B Baker Street', '221B Baker Street, Londres, Royaume-Uni'),
 ('Bree', 'Bree, Bree, Belgique'),
 ('Cambodge', 'Cambodge, Phnom Penh, Cambodge'),
 ('Pattani', 'Pattani, Pattani, Thaïlande'),
 ('Ouganda', 'Ouganda, Kampala, Ouganda'),
 ('Berkeley', 'Berkeley, Berkeley, États-Unis'),
 ('Mons', 'Mons, Mons, Belgique'),
 ('Cantal', 'Cantal, Aurillac, France'),
 ('Altstetten', 'Altstetten, Zurich, Suisse'),
 ('Clermont-Ferrand', 'Clermont-Ferrand, Clermont-Ferrand, France'),
 ('IIIe arrondissement de Marseille', '3e arrondissement, Marseille, France'),
 ('Damiette', 'Damiette, Damiette, Égypte'),
 ('Kenya', 'Kenya, Kenya, Kenya'),
 ('Gironde', 'Gironde, Bordeaux, France'),
 ('République de Chypre', 'Chypre, Nicosie, Chypre'),
 ('Reggio de Calabre', 'Reggio de Calabre, Reggio de Calabre, Italie'),
 ('Hongkong', 'Hong Kong, Hong Kong, Chine'),
 ('Corée-du-Sud', 'Corée du Sud, Séoul, Corée du Sud'),
 ('Bellechasse', 'Bellechasse, Québec, Canada'),
 ('Auschwitz-Monowitz', 'Auschwitz-Monowitz, Oświęcim, Pologne'),
 ('Soudan du Sud', 'Soudan du Sud, Djouba, Soudan du Sud'),
 ('Misrata', 'Misrata, Misrata, Libye'),
 ("Saint-Médard-d'Eyrans", "Saint-Médard-d'Eyrans, Bordeaux, France"),
 ('Séminaire Saint- Joseph de Trois-Rivières',
  'Séminaire Saint-Joseph de Trois-Rivières, Trois-Rivières, Canada'),
 ('Élysée', "Palais de l'Élysée, Paris, France"),
 ('Pic Saint-Louis-Gangeois', 'Pic Saint-Louis, Ganges, France'),
 ('Rize', 'Rize, Rize, Turquie'),
 ('Downtown Eastside', 'Downtown Eastside, Vancouver, Canada'),
 ('Cuba - ils', 'Cuba'),
 ('Fribourg', 'Fribourg, Fribourg, Suisse'),
 ('Grand Nancy', 'Nancy, Nancy, France'),
 ('Wuhan', 'Wuhan, Wuhan, Chine'),
 ('Cluj', 'Cluj-Napoca, Cluj-Napoca, Roumanie'),
 ('Béarn  ', 'Béarn, Pau, France'),
 ('Barbizon', 'Barbizon, Barbizon, France'),
 ('rue des Petits-Carreaux', 'Rue des Petits-Carreaux, Paris, France'),
 ('Saint-Genis-Laval Foire', 'Saint-Genis-Laval, Saint-Genis-Laval, France'),
 ('Rapides de Bourgogne', 'Rapides de Bourgogne, Bourgogne, France'),
 ('Gérone', 'Gérone, Gérone, Espagne'),
 ('Alco', 'Alco, Montpellier, France'),
 ('Vinalmont', 'Vinalmont, Huy, Belgique'),
 ('Mercoeur', 'Mercoeur, Corrèze, France'),
 ('île de la Cité', 'Île de la Cité, Paris, France'),
 ('Lavalloise', 'Laval, Québec, Canada'),
 ('Transylvanie', 'Transylvanie, Cluj-Napoca, Roumanie'),
 ('Dnipro', 'Dnipro, Dnipropetrovsk, Ukraine'),
 ('Gravelbourg', 'Gravelbourg, Saskatchewan, Canada'),
 ('Koninklijk Paleis', 'Palais Royal, Amsterdam, Pays-Bas'),
 ('Niger', 'Niger, Niamey, Niger'),
 ("Musée d'Art Mori", 'Mori Art Museum, Tokyo, Japon'),
 ('Lausannoise', 'Lausanne, Vaud, Suisse'),
 ('Pré Catelan', 'Pré Catelan, Paris, France'),
 ('Latrobe', 'Latrobe, Pennsylvanie, États-Unis'),
 ('Anglet', 'Anglet, Anglet, France'),
 ('Etats- Unis', 'États-Unis, États-Unis, États-Unis'),
 ('Saint-Molf', 'Saint-Molf, Saint-Molf, France'),
 ('Seattle', 'Seattle, Seattle, États-Unis'),
 ('Cap Corse', 'Cap Corse, Cap Corse, France'),
 ('gare Perrache', 'Gare de Lyon-Perrache, Lyon, France'),
 ('Marshalsea', 'Marshalsea, Londres, Royaume-Uni'),
 ('Huy', 'Huy, Huy, Belgique'),
 ('Jérusalem', 'Jérusalem, Jérusalem, Israël'),
 ('Porte Maillot', 'Porte Maillot, Paris, France'),
 ('Karatchaïevo-Tcherkessie',
  'Karatchaïevo-Tcherkessie, Karatchaïevo-Tcherkessie, Russie'),
 ('Iles Marshall-', 'Îles Marshall, Majuro, Îles Marshall'),
 ('Bobigny', 'Bobigny, Bobigny, France'),
 ('Valcourt', 'Valcourt, Québec, Canada'),
 ('St-Jérôme', 'Saint-Jérôme, Québec, Canada'),
 ('Rapée', 'Quai de la Rapée, Paris, France'),
 ('Besançon', 'Besançon, Bourgogne-Franche-Comté, France'),
 ('Port-Marly', 'Le Port-Marly, Île-de-France, France'),
 ('Grande bretagne', 'Grande-Bretagne, Royaume-Uni'),
 ('Beauzac Conférence', 'Beauzac, Auvergne-Rhône-Alpes, France'),
 ('Ath', 'Ath, Wallonie, Belgique'),
 ('Lavallois', 'Laval, Québec, Canada'),
 ('hôpital Saint- Pierre', 'Hôpital Saint-Pierre, Bruxelles, Belgique'),
 ('Battamgang', 'Battambang, Battambang, Cambodge'),
 ('Région de Brest Tristan', 'Brest, Bretagne, France'),
 ('République de Cuba', 'Cuba'),
 ('boulevard Général-Jacques', 'Boulevard Général-Jacques, Ixelles, Belgique'),
 ('Flandre', 'Flandre, Belgique'),
 ('Orne', 'Orne, Normandie, France'),
 ('Arles', "Arles, Provence-Alpes-Côte d'Azur, France"),
 ('Prudhomat', 'Prudhomat, Occitanie, France'),
 ('place Saint-Jean Lyon 9E Brocante Organisée par la',
  'Place Saint-Jean, Lyon 9e, France'),
 ('Palestine', 'Palestine, Moyen-Orient'),
 ('Narathiwat', 'Narathiwat, Narathiwat, Thaïlande'),
 ('le Perche', 'Le Perche, Normandie, France'),
 ('rue Sainte- Catherine', 'rue Sainte-Catherine, Bordeaux, France'),
 ('Gurs', 'Gurs, Pyrénées-Atlantiques, France'),
 ('FRA', 'France'),
 ('Rennaise', 'Rennes, Ille-et-Vilaine, France'),
 ('Val-de-Marne', 'Val-de-Marne, Île-de-France, France'),
 ('chapelle Notre-Dame du Vincin',
  'chapelle Notre-Dame du Vincin, Arradon, France'),
 ('Israël', 'Israël'),
 ('Miami', 'Miami, Floride, États-Unis'),
 ('Condé-en-Brie', 'Condé-en-Brie, Aisne, France'),

In [112]:
non_trouves

[('Bordeaux Rive Gauche', 'Bordeaux Rive Gauche, Bordeaux, France'),
 ('rue Bruat', 'rue Bruat, ville inconnue, France'),
 ('Ekallatum', 'Ekallatum, site antique, Irak'),
 ('esplanade Francois Mitterand',
  'Esplanade François Mitterrand, Paris, France'),
 ('Saut de la Mounine', 'Saut de la Mounine, Lot, France'),
 ('rue de la Juiverie', 'rue de la Juiverie, Paris, France'),
 ("hôpital Saint-Jean d'Arras", "hôpital Saint-Jean d'Arras, Arras, France"),
 ('Rochefort ~ Oléron',
  "Rochefort-sur-Mer / Île d'Oléron, Charente-Maritime, France"),
 ('Boussoufa', 'Boussoufa, Médenine, Tunisie'),
 ('gare de Cluj', 'Gare de Cluj, Cluj-Napoca, Roumanie'),
 ('Berkendael', 'Berkendael, Saint-Gilles, Belgique'),
 ('baie de Ficajola', 'baie de Ficajola, Piana, France'),
 ('Promenades boulevard de la Chalotais',
  'Boulevard de la Chalotais, Rennes, France'),
 ('boulevard de Châtenay', 'Boulevard de Châtenay, Paris, France'),
 ('outre-Manche', 'Outre-Manche, Royaume-Uni, Royaume-Uni'),
 ("Musée d'art moderne de New York",
  "Musée d'art moderne de New York, New York, États-Unis"),
 ('mont Vinson', 'Mont Vinson, Antarctique'),
 ('Pic Saint-Louis-Gangeois', 'Pic Saint-Louis, Ganges, France'),
 ('place Saint-Jean Lyon 9E Brocante Organisée par la',
  'Place Saint-Jean, Lyon 9e, France'),
 ('chapelle Notre-Dame du Vincin',
  'chapelle Notre-Dame du Vincin, Arradon, France'),
 ('Boulevard Lucien-Arnault', 'Boulevard Lucien-Arnault, Vincennes, France'),
 ('gare de Przemysl', 'Gare de Przemyśl, Przemyśl, Pologne'),
 ('théâtre de La Manicle', 'Théâtre de La Manicle, Besançon, France'),
 ('Casino Barrière de Deauville', 'Casino Barrière, Deauville, France'),
 ('rue de Savenay', 'rue de Savenay, Paris, France'),
 ('RDCongo)',
  'République Démocratique du Congo, null, République Démocratique du Congo'),
 ('Alpes suisses', 'Alpes suisses, Suisse'),
 ('Cartoucherie de Vincennes', 'Cartoucherie de Vincennes, Vincennes, France'),
 ('Haute Cour de Justice de Londres',
  'Haute Cour de Justice, Londres, Royaume-Uni'),
 ('Tchéco-slovaquie', 'Tchécoslovaquie, null, Tchécoslovaquie'),
 ("rue Chabot-d'Allier", "rue Chabot-d'Allier, Vichy, France"),
 ('vallée du Flon', 'Vallée du Flon, Lausanne, Suisse'),
 ('émirats du Golfe', 'Émirats du Golfe, Péninsule arabique, Moyen-Orient'),
 ('diocèse de Toulouse', 'diocèse de Toulouse, Toulouse, France'),
 ('Rif marocain', 'Rif, Nord du Maroc, Maroc'),
 ('Erythrée', 'Érythrée, Érythrée, Érythrée'),
 ('parc Delessert', 'Parc Delessert, Paris, France'),
 ('Boulogne- Levallois',
  'Boulogne-Billancourt / Levallois-Perret, Île-de-France, France'),
 ('Territoires palestiniens', 'Territoires palestiniens, null, Palestine'),
 ('rue Basse-Porte', 'rue Basse-Porte, null, null'),
 ('théâtre des Jacobins', 'Théâtre des Jacobins, Toulouse, France'),
 ('forêt de Posada', 'Forêt de Posada, Posada, Italie'),
 ('Théâtre de Babylone', 'Théâtre de Babylone, Paris, France'),
 ('lycée Saint-Yves', 'lycée Saint-Yves, Rennes, France'),
 ('plateau du Golan', 'plateau du Golan, Golan, Syrie/Israël'),
 ('boulevard du Grand-Cerf', 'Boulevard du Grand-Cerf, Paris, France'),
 ('Kierling A Vienne', 'Kierling, Vienne, Autriche'),
 ('Sûreté urbaine de Lille', 'Sûreté urbaine, Lille, France'),
 ('Milan ROME', 'Milan/Rome, null, Italie'),
 ('désert mauritanien', 'Désert, Mauritanie, Mauritanie'),
 ("mer d'Aden", "Mer d'Aden, null, null"),
 ('Extrême-Orient russe', 'Extrême-Orient russe, Russie'),
 ('Océan de la Tranquillité', 'Mer de la Tranquillité, Lune'),
 ('Château Lamontagne',
  'Château Lamontagne, Saint-Yrieix-sur-Charente, France'),
 ('forêt de Galfingue', 'Forêt de Galfingue, Galfingue, France'),
 ('Musée des beaux-arts du Locle',
  'Musée des beaux-arts du Locle, Le Locle, Suisse'),
 ('Gois  Basse mer', 'Passage du Gois, Noirmoutier, France'),
 ('université de Versailles Saint-Quentin',
  'Université de Versailles Saint-Quentin-en-Yvelines, Versailles, France'),
 ('Fallouja', 'Fallouja, Fallouja, Irak'),
 ('République populaire de Louhansk',
  'République populaire de Louhansk, Louhansk, Ukraine'),
 ('Bahia Golf Beach', 'Bahia Golf Beach, Agadir, Maroc'),
 ('quartier de Sonagachi', 'Sonagachi, Kolkata, Inde'),
 ('Radwanli', 'Radwanli, Radwanli, Syrie'),
 ('rue Travot', 'Rue Travot, Paris, France'),
 ('Bourse de Bangkok', 'Bourse de Bangkok, Bangkok, Thaïlande'),
 ('Chambre des communes', 'Chambre des communes, Londres, Royaume-Uni'),
 ('avenue de la Canebière', 'avenue de la Canebière, Marseille, France'),
 ('Elbrouz', 'Mont Elbrouz, Kabardino-Balkarie, Russie'),
 ('Jardin royal des plantes médicinales',
  'Jardin royal des plantes médicinales, Londres, Royaume-Uni'),
 ("REVOLTES DE L'ÎLE DU DIABLE",
  'Île du Diable, Île du Diable, Guyane française'),
 ('Province du Brabant flamand - n.a.v',
  'Province du Brabant flamand, Louvain, Belgique'),
 ('Petaux', 'Petaux, Orne, France'),
 ("Cour d'appel de Lisbonne", "Cour d'appel de Lisbonne, Lisbonne, Portugal"),
 ('Cascades du Hérisson', 'Cascades du Hérisson, Clairvaux-les-Lacs, France'),
 ('Suisse alémanique', 'Suisse alémanique, Suisse'),
 ('Promenade nantaise', 'Promenade nantaise, Nantes, France'),
 ('Dausque', 'Dusque, Andalousie, Espagne'),
 ('mont Pirin', 'Mont Pirin, Blagoevgrad, Bulgarie'),
 ("jardin Jeanne d'Arc", "Jardin Jeanne d'Arc, Paris, France"),
 ('Loire  Nord Littoral', 'Loire Nord Littoral, France'),
 ('Indochine française',
  'Indochine française, Asie du Sud-Est, France (ancienne colonie)'),
 ('Gironde Libournais Blayais', 'Libournais Blayais, Gironde, France'),
 ("Saint-Georges d'argent",
  "Saint-Georges-d'Argent, Auvergne-Rhône-Alpes, France"),
 ('5e circonscription des Alpes-Maritimes',
  '5e circonscription des Alpes-Maritimes, Alpes-Maritimes, France'),
 ("Cirque d'hiver Bouglione", "Cirque d'Hiver Bouglione, Paris, France"),
 ('Uotsurijima', 'Uotsurijima, Îles Senkaku, Japon'),
 ('bâtiment Baltard', 'Bâtiment Baltard, Paris, France'),
 ('Centre Pompidou)à Tokyo', 'Centre Pompidou, Tokyo, Japon'),
 ('Amérique Latine', 'Amérique Latine, null, null'),
 ('rue Fernand-Chapsal', 'rue Fernand-Chapsal, null, France'),
 ('rue Laurier', 'rue Laurier, null, null'),
 ('cathédrale de Trondheim', 'cathédrale de Nidaros, Trondheim, Norvège'),
 ('Tranié', 'Tranié, Tranié, France'),
 ('royaume des Deux-Siciles', 'Royaume des Deux-Siciles, Naples, Italie'),
 ('Extrême-Orient', "Extrême-Orient, Asie de l'Est, Asie"),
 ('Etat de Rio de Janeiro', 'État de Rio de Janeiro, Rio de Janeiro, Brésil'),
 ('lac du bois de Boulogne', 'Lac du Bois de Boulogne, Paris, France'),
 ('rue Charlevoix-de-Villers', 'rue Charlevoix-de-Villers, Paris, France'),
 ('Palais des colonies', 'Palais des colonies, Bruxelles, Belgique'),
 ('centrale nucléaire de Marcoule',
  'Centrale nucléaire de Marcoule, Marcoule, France'),
 ('Couvent rouge de Reval', 'Couvent rouge, Tallinn, Estonie'),
 ('Baionarena', 'Baionarena, Bilbao, Espagne'),
 ('château du Glandier', 'Château du Glandier, Corrèze, France'),
 ('TRANSMIS CôteIvoire', "Côte d'Ivoire, null, Côte d'Ivoire"),
 ('Cimetière-Musée San Pedro',
  'Cimetière-Musée San Pedro, Medellín, Colombie'),
 ('Slantchev briag', 'Slantchev Bryag, Burgas, Bulgarie'),
 ('hôtel de police de Montbéliard', 'Hôtel de police, Montbéliard, France'),
 ('porte de Heusy', 'Porte de Heusy, Verviers, Belgique'),
 ('chambre des Communes', 'Chambre des communes, Londres, Royaume-Uni'),
 ('Montalier', 'Montalier, Ain, France'),
 ('Porto Santo/ Dakar VOLLEY-BALL', 'Porto Santo, Dakar, Sénégal'),
 ('quartier Madeleine-Champ-de- Mars',
  'Quartier Madeleine-Champ-de-Mars, Paris, France'),
 ('Pré-Gauchet', 'Pré-Gauchet, Genève, Suisse'),
 ('Afrique subsaharienne',
  'Afrique subsaharienne, Afrique subsaharienne, Afrique'),
 ('Qc J1S', 'J1S, Saint-Hyacinthe, Canada'),
 ('Centre Mémorial des Victimes du Terrorisme de Vitoria',
  'Centre Mémorial des Victimes du Terrorisme, Vitoria-Gasteiz, Espagne'),
 ("Cantons de l'Est", "Cantons de l'Est, Liège, Belgique"),
 ('Nollywood', 'Nollywood, Lagos, Nigeria'),
 ('fédération des Emirats arabes unis',
  'Émirats arabes unis, Émirats arabes unis, Émirats arabes unis'),
 ('Théâtre du Trident', 'Théâtre du Trident, Québec, Canada'),
 ('église Sainte-Marie-des-Anges de Wellington',
  'Église Sainte-Marie-des-Anges, Wellington, Nouvelle-Zélande'),
 ('Charleroi-Central', 'Gare de Charleroi-Central, Charleroi, Belgique'),
 ('Mosellan', 'Moselle, null, France'),
 ('Clermont-Limagne', 'Clermont-Limagne, Clermont-Limagne, France'),
 ('Transmusicales de Rennes', 'Transmusicales de Rennes, Rennes, France'),
 ('îles Senkaku', 'îles Senkaku, îles Senkaku, Mer de Chine orientale'),
 ('Théâtre du Soleil', 'Théâtre du Soleil, Vincennes, France'),
 ('Elbow River Healing Lodge', 'Elbow River Healing Lodge, Calgary, Canada'),
 ("MJC de l'Harteloire", "MJC de l'Harteloire, Brest, France"),
 ('ZAC Paris-Rive gauche', 'ZAC Paris-Rive Gauche, Paris, France'),
 ('Oulamara', 'Oulamara, Algérie'),
 ('Orchestre de Picardie', 'Picardie, null, France'),
 ('Khouzestan', 'Khouzestan, Khouzestan, Iran'),
 ('Mandchou', 'Mandchourie, , Chine'),
 ('Corées', 'Corée, Asie'),
 ('Mokhran', 'Mokhran, Baloutchistan, Iran'),
 ('Plourin-Ploudalmézeau', 'Plourin-Ploudalmézeau, Brest, France'),
 ('église évangélique de Froges(Isère',
  'Église évangélique de Froges, Froges, France'),
 ('mer de Tasmanie', 'mer de Tasmanie, Océan Pacifique Sud'),
 ('Albanieà', 'null, null, Albanie'),
 ('Ostie', 'Ostie, Rome, Italie'),
 ('grand barrage de Sivens TOULOUSE', 'Sivens, Toulouse, France'),
 ('université de  Lille III', 'Université de Lille III, Lille, France'),
 ('Vaurien', 'Vaurien, Cergy, France'),
 ('Suburre', 'Subure, Rome, Italie'),
 ('Sahel - de 2 500 hectares', "Sahel, Afrique de l'Ouest, Afrique"),
 ('Tosa-Klause', 'Tosa-Klause, Ötztal, Autriche'),
 ('Strasberg', 'Strasberg, Bas-Rhin, France'),
 ('Prillaz', 'Prillaz, Grolley, Suisse'),
 ('Théâtre Claude Volter', 'Théâtre Claude Volter, Ixelles, Belgique'),
 ('Mont-sur-Marchiennes', 'Mont-sur-Marchiennes, Douai, France'),
 ('rue Rodo', 'Rue Rodo, null, null'),
 ('hôpital Louis-H. Lafontaine',
  'Hôpital Louis-H. Lafontaine, Montréal, Canada'),
 ('Noirceuil', 'Noirceuil, Noirceuil, Belgique'),
 ('Nouvelle République du Centre-Ouest  ',
  'Nouvelle République du Centre-Ouest, Tours, France'),
 ('avenue Joffre', 'Avenue Joffre, null, null'),
 ('Bouquy', 'Bouquy, Beautiran, France'),
 ('rue des  Verreries', 'Rue des Verreries, Montpellier, France'),
 ('autoroute E40', 'Autoroute E40, Europe'),
 ('Thiers- Ambert', 'Thiers-Ambert, Thiers, France'),
 ("l'Afrique noire", 'Afrique subsaharienne, Afrique'),
 ('Afrique noire', 'Afrique subsaharienne, null, Afrique'),
 ('Riviera vaudoise', 'Riviera vaudoise, Vaud, Suisse'),
 ('Olympic Center Ventspils', 'Olympic Center Ventspils, Ventspils, Lettonie'),
 ('Sainte-Pélagie', 'Sainte-Pélagie, Paris, France'),
 ('fleuve Xingu', 'fleuve Xingu, null, Brésil'),
 ('rue Bias', 'Rue Bias, Paris, France'),
 ('États allemands', 'États allemands, Allemagne'),
 ('rue du Commandant-Drogou', 'rue du Commandant-Drogou, null, France'),
 ('Plateau iranien', 'Plateau iranien, null, Iran'),
 ('rue des Carmélites', 'rue des Carmélites, null, France'),
 ('TC Bruxelles', 'Tribunal de Commerce, Bruxelles, Belgique'),
 ("Cour d'assises de l'Ain",
  "Cour d'assises de l'Ain, Bourg-en-Bresse, France"),
 ('passage Colbert', 'Passage Colbert, Paris, France'),
 ('Luisanciers', 'Luisanciers, Jura, France'),
 ('rue Lesueur', 'rue Lesueur, Paris, France'),
 ('Nouvelle République du Centre-Ouest',
  'Nouvelle République du Centre-Ouest, Tours, France'),
 ('avenue Xavier-Rineau', 'Avenue Xavier-Rineau, Bouguenais, France'),
 ('Est de la République démocratique du Congo',
  'Est de la République démocratique du Congo, null, République démocratique du Congo'),
 ('rue des Vignolles', 'Rue des Vignolles, Paris, France'),
 ('Alpes françaises', 'Alpes françaises, null, France'),
 ('Cité des Doges', 'Cité des Doges, Venise, Italie'),
 ('rue Ermengaud', 'Rue Ermengaud, Nîmes, France')]

In [114]:
resultats[-1]

{'nom': 'Rue Ermengaud, Nîmes, France',
 'lat': 43.8374249,
 'lon': 4.3600687,
 'pays': 'France',
 'code_pays': 'FR',
 'nom_complet': 'Nîmes, Gard, Occitanie, France métropolitaine, France',
 'source': 'nominatim_struct'}

In [133]:
# Identifier ce qui manque
noms_trouves = {r["nom"][1] for r in resultats}
non_trouves = [lieu for lieu in liste_pays if lieu[1] not in noms_trouves]
len(non_trouves)

5

In [134]:
non_trouves

[('rue Basse-Porte', 'rue Basse-Porte, null, null'),
 ('rue Laurier', 'rue Laurier, null, null'),
 ('rue Rodo', 'Rue Rodo, null, null'),
 ('avenue Joffre', 'Avenue Joffre, null, null'),
 ('autoroute E40', 'Autoroute E40, Europe')]

In [73]:
def geocode_geonames(name, username="poids_plume"):
    url = "http://api.geonames.org/searchJSON"
    params = {
        "q": name,
        "maxRows": 1,
        "username": username,
        "lang": "fr"
    }
    r = requests.get(url, params=params, timeout=10)
    data = r.json()
    print(data)
    if not data.get("geonames"):
        return None
    d = data["geonames"][0]
    return {
        "nom": name,
        "lat": float(d["lat"]),
        "lon": float(d["lng"]),
        "pays": d.get("countryName", ""),
        "code_pays": d.get("countryCode", ""),
        "nom_complet": d.get("toponymName", ""),
    }

In [96]:
for lieu in non_trouves:
    for tentative in range(3):
        try:
            res = geocode_geonames(lieu)
            if res:
                resultats.append(res)
                print(f"✓ {lieu} → {res['pays']}")
            else:
                print(f"✗ {lieu} → non trouvé")
            break
        except requests.exceptions.ConnectionError:
            print(f"⚠ Réseau KO, attente 30s (tentative {tentative+1}/3)...")
            time.sleep(30)
    
    time.sleep(1.1)

{'totalResultsCount': 0, 'geonames': []}
✗ ('Bordeaux Rive Gauche', 'Bordeaux Rive Gauche, Bordeaux, France') → non trouvé
{'totalResultsCount': 10, 'geonames': [{'adminCode1': '00', 'lng': '-5.5', 'geonameId': 2287781, 'toponymName': 'Republic of Côte d’Ivoire', 'countryId': '2287781', 'fcl': 'A', 'population': 25069229, 'countryCode': 'CI', 'name': "Côte d'Ivoire", 'fclName': 'country, state, region,...', 'countryName': "Côte d'Ivoire", 'fcodeName': 'independent political entity', 'adminName1': '', 'lat': '8', 'fcode': 'PCLI'}]}
✓ ("Côte d'Ivoire", "Côte d'Ivoire, Afrique de l'Ouest") → Côte d'Ivoire
{'totalResultsCount': 0, 'geonames': []}
✗ ('rue Bruat', 'rue Bruat, ville inconnue, France') → non trouvé
{'totalResultsCount': 11193, 'geonames': [{'adminCode1': '04', 'lng': '-68.15', 'geonameId': 3911925, 'toponymName': 'La Paz', 'countryId': '3923057', 'fcl': 'P', 'population': 2004652, 'countryCode': 'BO', 'name': 'La Paz', 'fclName': 'city, village,...', 'adminCodes1': {'ISO3166_2': 'L'}, 'countryName': 'Bolivie', 'fcodeName': 'seat of government of a political entity', 'adminName1': 'La Paz', 'lat': '-16.5', 'fcode': 'PPLG'}]}
✓ ('la Bolivie', 'Bolivie, Sucre, Bolivie') → Bolivie
{'totalResultsCount': 0, 'geonames': []}
✗ ('Ekallatum', 'Ekallatum, site antique, Irak') → non trouvé
{'totalResultsCount': 19, 'geonames': [{'adminCode1': '00', 'lng': '38.5', 'geonameId': 709718, 'toponymName': 'Donets Basin', 'countryId': '690791', 'fcl': 'L', 'population': 0, 'countryCode': 'UA', 'name': 'Donbass', 'fclName': 'parks,area, ...', 'countryName': 'Ukraine', 'fcodeName': 'region', 'adminName1': '', 'lat': '48.5', 'fcode': 'RGN'}]}
✓ ('Donbass', 'Donbass, Donbass, Ukraine') → Ukraine
{'totalResultsCount': 0, 'geonames': []}
✗ ('esplanade Francois Mitterand', 'Esplanade François Mitterrand, Paris, France') → non trouvé
{'totalResultsCount': 0, 'geonames': []}
✗ ('Saut de la Mounine', 'Saut de la Mounine, Lot, France') → non trouvé
{'totalResultsCount': 56, 'geonames': [{'adminCode1': '00', 'lng': '172.86667', 'geonameId': 2183034, 'toponymName': 'Saint Arnaud Range', 'countryId': '2186224', 'fcl': 'T', 'population': 0, 'countryCode': 'NZ', 'name': 'Saint Arnaud Range', 'fclName': 'mountain,hill,rock,... ', 'countryName': 'Nouvelle-Zélande', 'fcodeName': 'mountains', 'adminName1': '', 'lat': '-41.9', 'fcode': 'MTS'}]}
✓ ('St-Arnaud', 'Saint-Arnaud, Nouvelle-Galles du Sud, Australie') → Nouvelle-Zélande
{'totalResultsCount': 1, 'geonames': [{'adminCode1': '08', 'lng': '7.65', 'geonameId': 3179996, 'toponymName': 'Casa Veragne', 'countryId': '3175395', 'fcl': 'P', 'population': 0, 'countryCode': 'IT', 'name': 'Casa Veragne', 'fclName': 'city, village,...', 'adminCodes1': {'ISO3166_2': '42'}, 'countryName': 'Italie', 'fcodeName': 'populated place', 'adminName1': 'Ligurie', 'lat': '43.91667', 'fcode': 'PPL'}]}
✓ ('Véragne', 'Véragne, Savoie, France') → Italie
{'totalResultsCount': 2, 'geonames': [{'adminCode1': '95', 'lng': '-5.36777', 'geonameId': 2289912, 'toponymName': 'Dioulas Babokon', 'countryId': '2287781', 'fcl': 'P', 'population': 0, 'countryCode': 'CI', 'name': 'Dioulas Babokon', 'fclName': 'city, village,...', 'adminCodes1': {'ISO3166_2': 'GD'}, 'countryName': "Côte d'Ivoire", 'fcodeName': 'populated place', 'adminName1': 'District du Gôh-Djiboua', 'lat': '5.58147', 'fcode': 'PPL'}]}
✓ ('Dioulas', 'Dioulas, Brest, France') → Côte d'Ivoire
{'totalResultsCount': 8, 'geonames': [{'lng': '-4.83398', 'geonameId': 7729885, 'name': "Afrique de l'Ouest", 'fclName': 'parks,area, ...', 'toponymName': 'Western Africa', 'fcodeName': 'region', 'adminName1': '', 'lat': '18.31281', 'fcl': 'L', 'fcode': 'RGN', 'population': 340000000}]}
✓ ("l'Afrique", 'Afrique, null, null') →
{'totalResultsCount': 0, 'geonames': []}
✗ ('rue de la Juiverie', 'rue de la Juiverie, Paris, France') → non trouvé
{'totalResultsCount': 0, 'geonames': []}
✗ ("hôpital Saint-Jean d'Arras", "hôpital Saint-Jean d'Arras, Arras, France") → non trouvé
{'totalResultsCount': 0, 'geonames': []}
✗ ('Rochefort ~ Oléron', "Rochefort-sur-Mer / Île d'Oléron, Charente-Maritime, France") → non trouvé
{'totalResultsCount': 7, 'geonames': [{'adminCode1': '11', 'lng': '2.55', 'geonameId': 6269554, 'toponymName': 'Paris Charles de Gaulle Airport', 'countryId': '3017382', 'fcl': 'S', 'population': 0, 'countryCode': 'FR', 'name': 'Aéroport Paris–Charles de Gaulle', 'fclName': 'spot, building, farm', 'adminCodes1': {'ISO3166_2': 'IDF'}, 'countryName': 'France', 'fcodeName': 'airport', 'adminName1': 'Île-de-France', 'lat': '49.01278', 'fcode': 'AIRP'}]}
✓ ('aéroport de Roissy', 'Aéroport Charles-de-Gaulle, Roissy-en-France, France') → France
{'totalResultsCount': 0, 'geonames': []}
✗ ('Boussoufa', 'Boussoufa, Médenine, Tunisie') → non trouvé
{'totalResultsCount': 6, 'geonames': [{'adminCode1': '05', 'lng': '32.8512', 'geonameId': 146016, 'toponymName': 'Troodos Mountains', 'countryId': '146669', 'fcl': 'T', 'population': 0, 'countryCode': 'CY', 'name': 'Troodos Mountains', 'fclName': 'mountain,hill,rock,... ', 'adminCodes1': {'ISO3166_2': '02'}, 'countryName': 'Chypre', 'fcodeName': 'mountains', 'adminName1': 'Limassol', 'lat': '34.92334', 'fcode': 'MTS'}]}
✓ ('Troodos', 'Massif du Troodos, Limassol, Chypre') → Chypre
{'totalResultsCount': 35445, 'geonames': [{'adminCode1': '00', 'lng': '147', 'geonameId': 2088628, 'toponymName': 'Independent State of Papua New Guinea', 'countryId': '2088628', 'fcl': 'A', 'population': 8606316, 'countryCode': 'PG', 'name': 'Papouasie-Nouvelle-Guinée', 'fclName': 'country, state, region,...', 'countryName': 'Papouasie-Nouvelle-Guinée', 'fcodeName': 'independent political entity', 'adminName1': '', 'lat': '-6', 'fcode': 'PCLI'}]}
✓ ('Papouasie-Nouvelle-Guinée', 'Papouasie-Nouvelle-Guinée, Port Moresby, Papouasie-Nouvelle-Guinée') → Papouasie-Nouvelle-Guinée
{'totalResultsCount': 0, 'geonames': []}
✗ ('gare de Cluj', 'Gare de Cluj, Cluj-Napoca, Roumanie') → non trouvé
{'totalResultsCount': 0, 'geonames': []}
✗ ('Berkendael', 'Berkendael, Saint-Gilles, Belgique') → non trouvé
{'totalResultsCount': 17142, 'geonames': [{'adminCode1': '01', 'lng': '-5.36837', 'geonameId': 2528910, 'toponymName': 'Tétouan', 'countryId': '2542007', 'fcl': 'P', 'population': 415810, 'countryCode': 'MA', 'name': 'Tétouan', 'fclName': 'city, village,...', 'adminCodes1': {'ISO3166_2': '01'}, 'countryName': 'Maroc', 'fcodeName': 'seat of a second-order administrative division', 'adminName1': 'Tanger-Tetouan-Al Hoceima', 'lat': '35.57845', 'fcode': 'PPLA2'}]}
✓ ('TETOUAN', 'Tétouan, Tétouan-Al Hoceïma-Taza, Maroc') → Maroc
{'totalResultsCount': 0, 'geonames': []}
✗ ('baie de Ficajola', 'baie de Ficajola, Piana, France') → non trouvé
{'totalResultsCount': 367, 'geonames': [{'adminCode1': '01', 'lng': '44.4421', 'geonameId': 922000, 'toponymName': 'Anjouan', 'countryId': '921929', 'fcl': 'T', 'population': 0, 'countryCode': 'KM', 'name': 'Anjouan', 'fclName': 'mountain,hill,rock,... ', 'adminCodes1': {'ISO3166_2': 'A'}, 'countryName': 'Comores', 'fcodeName': 'island', 'adminName1': "Île Autonome d'Anjouan", 'lat': '-12.21999', 'fcode': 'ISL'}]}
✓ ("île d'Anjouan", "île d'Anjouan, Mutsamudu, Comores") → Comores
{'totalResultsCount': 1, 'geonames': [{'adminCode1': '93', 'lng': '5.89218', 'geonameId': 2999682, 'toponymName': 'Les Sablettes', 'countryId': '3017382', 'fcl': 'P', 'population': 0, 'countryCode': 'FR', 'name': 'Les Sablettes', 'fclName': 'city, village,...', 'adminCodes1': {'ISO3166_2': 'PAC'}, 'countryName': 'France', 'fcodeName': 'populated place', 'adminName1': "Provence-Alpes-Côte d'Azur", 'lat': '43.08236', 'fcode': 'PPL'}]}
✓ ('Sablette', 'La Sablette, La Seyne-sur-Mer, France') → France
{'totalResultsCount': 2, 'geonames': [{'adminCode1': '75', 'lng': '-0.05116', 'geonameId': 12322689, 'toponymName': 'La Coursaudière', 'countryId': '3017382', 'fcl': 'P', 'population': 0, 'countryCode': 'FR', 'name': 'La Coursaudière', 'fclName': 'city, village,...', 'adminCodes1': {'ISO3166_2': 'NAQ'}, 'countryName': 'France', 'fcodeName': 'populated place', 'adminName1': 'Nouvelle-Aquitaine', 'lat': '46.6074', 'fcode': 'PPL'}]}
✓ ('Coursaudière', 'Coursaudière, null, France') → France
{'totalResultsCount': 1584, 'geonames': [{'adminCode1': '93', 'lng': '6.28969', 'geonameId': 3013738, 'toponymName': 'Hautes-Alpes', 'countryId': '3017382', 'fcl': 'A', 'population': 141677, 'countryCode': 'FR', 'name': 'Hautes-Alpes', 'fclName': 'country, state, region,...', 'adminCodes1': {'ISO3166_2': 'PAC'}, 'countryName': 'France', 'fcodeName': 'second-order administrative division', 'adminName1': "Provence-Alpes-Côte d'Azur", 'lat': '44.68055', 'fcode': 'ADM2'}]}
✓ ('Hautes-Alpes', 'Hautes-Alpes, null, France') → France
{'totalResultsCount': 0, 'geonames': []}
✗ ('Promenades boulevard de la Chalotais', 'Boulevard de la Chalotais, Rennes, France') → non trouvé
{'totalResultsCount': 2, 'geonames': [{'adminCode1': '75', 'lng': '1.06673', 'geonameId': 2977893, 'toponymName': 'Saint-Nicolas-Courbefy', 'countryId': '3017382', 'fcl': 'P', 'population': 0, 'countryCode': 'FR', 'name': 'Saint-Nicolas-Courbefy', 'fclName': 'city, village,...', 'adminCodes1': {'ISO3166_2': 'NAQ'}, 'countryName': 'France', 'fcodeName': 'populated place', 'adminName1': 'Nouvelle-Aquitaine', 'lat': '45.5864', 'fcode': 'PPL'}]}
✓ ('Courbefy', 'Courbefy, Cheissoux, France') → France
{'totalResultsCount': 19, 'geonames': [{'adminCode1': '15', 'lng': '32.56278', 'geonameId': 347712, 'toponymName': 'Suez Canal', 'countryId': '357994', 'fcl': 'H', 'population': 0, 'countryCode': 'EG', 'name': 'Suez Canal', 'fclName': 'stream, lake, ...', 'adminCodes1': {'ISO3166_2': 'SUZ'}, 'countryName': 'Égypte', 'fcodeName': 'canal', 'adminName1': 'Suez', 'lat': '29.93139', 'fcode': 'CNL'}]}
✓ ('Canal de Suez', 'Canal de Suez, null, Égypte') → Égypte
{'totalResultsCount': 0, 'geonames': []}
✗ ('boulevard de Châtenay', 'Boulevard de Châtenay, Paris, France') → non trouvé
{'totalResultsCount': 51907, 'geonames': [{'adminCode1': '00', 'lng': '17.83333', 'geonameId': 3277605, 'toponymName': 'Bosnia and Herzegovina', 'countryId': '3277605', 'fcl': 'A', 'population': 3323929, 'countryCode': 'BA', 'name': 'Bosnie-et-Herzégovine', 'fclName': 'country, state, region,...', 'countryName': 'Bosnie-Herzégovine', 'fcodeName': 'independent political entity', 'adminName1': '', 'lat': '44.25', 'fcode': 'PCLI'}]}
✓ ('Bosnie-Herzégovine', 'Bosnie-Herzégovine, Balkans, Europe') → Bosnie-Herzégovine
{'totalResultsCount': 0, 'geonames': []}
✗ ('outre-Manche', 'Outre-Manche, Royaume-Uni, Royaume-Uni') → non trouvé
{'totalResultsCount': 0, 'geonames': []}
✗ ("Musée d'art moderne de New York", "Musée d'art moderne de New York, New York, États-Unis") → non trouvé
{'totalResultsCount': 0, 'geonames': []}
✗ ('mont Vinson', 'Mont Vinson, Antarctique') → non trouvé
{'totalResultsCount': 26962, 'geonames': [{'adminCode1': '00', 'lng': '32.5', 'geonameId': 226074, 'toponymName': 'Republic of Uganda', 'countryId': '226074', 'fcl': 'A', 'population': 42723139, 'countryCode': 'UG', 'name': 'Ouganda', 'fclName': 'country, state, region,...', 'countryName': 'Ouganda', 'fcodeName': 'independent political entity', 'adminName1': '', 'lat': '1.25', 'fcode': 'PCLI'}]}
✓ ('Ouganda', 'Ouganda, Kampala, Ouganda') → Ouganda
{'totalResultsCount': 144762, 'geonames': [{'adminCode1': '00', 'lng': '127.75', 'geonameId': 1835841, 'toponymName': 'Republic of Korea', 'countryId': '1835841', 'fcl': 'A', 'population': 51635256, 'countryCode': 'KR', 'name': 'Corée du Sud', 'fclName': 'country, state, region,...', 'countryName': 'Corée du Sud', 'fcodeName': 'independent political entity', 'adminName1': '', 'lat': '36.5', 'fcode': 'PCLI'}]}
✓ ('Corée-du-Sud', 'Corée du Sud, Séoul, Corée du Sud') → Corée du Sud
{'totalResultsCount': 179061, 'geonames': [{'adminCode1': '00', 'lng': '30', 'geonameId': 7909807, 'toponymName': 'South Sudan', 'countryId': '7909807', 'fcl': 'A', 'population': 8260490, 'countryCode': 'SS', 'name': 'Soudan du Sud', 'fclName': 'country, state, region,...', 'countryName': 'Soudan du Sud', 'fcodeName': 'independent political entity', 'adminName1': '', 'lat': '7.5', 'fcode': 'PCLI'}]}
✓ ('Soudan du Sud', 'Soudan du Sud, Djouba, Soudan du Sud') → Soudan du Sud
{'totalResultsCount': 0, 'geonames': []}
✗ ('Pic Saint-Louis-Gangeois', 'Pic Saint-Louis, Ganges, France') → non trouvé
{'totalResultsCount': 5, 'geonames': [{'adminCode1': '07', 'lng': '4.89136', 'geonameId': 6951693, 'toponymName': 'Paleis op de Dam', 'countryId': '2750405', 'fcl': 'S', 'population': 0, 'countryCode': 'NL', 'name': 'Palais royal dAmsterdam', 'fclName': 'spot, building, farm', 'adminCodes1': {'ISO3166_2': 'NH'}, 'countryName': 'Pays-Bas', 'fcodeName': 'palace', 'adminName1': 'Hollande-Septentrionale', 'lat': '52.37314', 'fcode': 'PAL'}]}
✓ ('Koninklijk Paleis', 'Palais Royal, Amsterdam, Pays-Bas') → Pays-Bas
{'totalResultsCount': 1077, 'geonames': [{'adminCode1': '27', 'lng': '42.04624', 'geonameId': 569154, 'toponymName': 'Cherkessk', 'countryId': '2017370', 'fcl': 'P', 'population': 122395, 'countryCode': 'RU', 'name': 'Cherkessk', 'fclName': 'city, village,...', 'adminCodes1': {'ISO3166_2': 'KC'}, 'countryName': 'Russie', 'fcodeName': 'seat of a first-order administrative division', 'adminName1': 'Province de Karatchaïévo-Tcherkessie', 'lat': '44.22375', 'fcode': 'PPLA'}]}
✓ ('Karatchaïevo-Tcherkessie', 'Karatchaïevo-Tcherkessie, Karatchaïevo-Tcherkessie, Russie') → Russie
{'totalResultsCount': 1318, 'geonames': [{'adminCode1': '00', 'lng': '171.236', 'geonameId': 2080185, 'toponymName': 'Republic of the Marshall Islands', 'countryId': '2080185', 'fcl': 'A', 'population': 58413, 'countryCode': 'MH', 'name': 'Îles Marshall', 'fclName': 'country, state, region,...', 'countryName': 'Îles Marshall', 'fcodeName': 'freely associated state', 'adminName1': '', 'lat': '7.113', 'fcode': 'PCLF'}]}
✓ ('Iles Marshall-', 'Îles Marshall, Majuro, Îles Marshall') → Îles Marshall
{'totalResultsCount': 0, 'geonames': []}
✗ ('place Saint-Jean Lyon 9E Brocante Organisée par la', 'Place Saint-Jean, Lyon 9e, France') → non trouvé
{'totalResultsCount': 7713, 'geonames': [{'adminCode1': '00', 'lng': '35.20329', 'geonameId': 6254930, 'toponymName': 'Palestine', 'countryId': '6254930', 'fcl': 'A', 'population': 4569087, 'countryCode': 'PS', 'name': 'Palestine', 'fclName': 'country, state, region,...', 'countryName': 'Palestine', 'fcodeName': 'semi-independent political entity', 'adminName1': '', 'lat': '31.92157', 'fcode': 'PCLS'}]}
✓ ('Palestine', 'Palestine, Moyen-Orient') → Palestine
{'totalResultsCount': 0, 'geonames': []}
✗ ('chapelle Notre-Dame du Vincin', 'chapelle Notre-Dame du Vincin, Arradon, France') → non trouvé
{'totalResultsCount': 0, 'geonames': []}
✗ ('Boulevard Lucien-Arnault', 'Boulevard Lucien-Arnault, Vincennes, France') → non trouvé
{'totalResultsCount': 62, 'geonames': [{'adminCode1': '00', 'lng': '69.87339', 'geonameId': 1547120, 'toponymName': 'Lac Bleu', 'countryId': '1546748', 'fcl': 'H', 'population': 0, 'countryCode': 'TF', 'name': 'Lac Bleu', 'fclName': 'stream, lake, ...', 'countryName': 'Terres australes françaises', 'fcodeName': 'lake', 'adminName1': '', 'lat': '-49.61556', 'fcode': 'LK'}]}
✓ ('Lac Bleu', 'Lac Bleu, null, null') → Terres australes françaises
{'totalResultsCount': 144762, 'geonames': [{'adminCode1': '00', 'lng': '127.75', 'geonameId': 1835841, 'toponymName': 'Republic of Korea', 'countryId': '1835841', 'fcl': 'A', 'population': 51635256, 'countryCode': 'KR', 'name': 'Corée du Sud', 'fclName': 'country, state, region,...', 'countryName': 'Corée du Sud', 'fcodeName': 'independent political entity', 'adminName1': '', 'lat': '36.5', 'fcode': 'PCLI'}]}
✓ ('Corée du sud', 'null, null, Corée du Sud') → Corée du Sud
{'totalResultsCount': 199, 'geonames': [{'adminCode1': '27', 'lng': '6.88843', 'geonameId': 3033789, 'toponymName': 'Territoire de Belfort', 'countryId': '3017382', 'fcl': 'A', 'population': 140082, 'countryCode': 'FR', 'name': 'Territoire de Belfort', 'fclName': 'country, state, region,...', 'adminCodes1': {'ISO3166_2': 'BFC'}, 'countryName': 'France', 'fcodeName': 'second-order administrative division', 'adminName1': 'Bourgogne', 'lat': '47.63578', 'fcode': 'ADM2'}]}
✓ ('place Belfort', 'Place de Belfort, null, France') → France
{'totalResultsCount': 483, 'geonames': [{'adminCode1': '11', 'lng': '2.35387', 'geonameId': 2980916, 'toponymName': 'Saint-Denis', 'countryId': '3017382', 'fcl': 'P', 'population': 96128, 'countryCode': 'FR', 'name': 'Saint-Denis', 'fclName': 'city, village,...', 'adminCodes1': {'ISO3166_2': 'IDF'}, 'countryName': 'France', 'fcodeName': 'seat of a third-order administrative division', 'adminName1': 'Île-de-France', 'lat': '48.93564', 'fcode': 'PPLA3'}]}
✓ ('Seine-Saint-Denis', 'Seine-Saint-Denis, null, France') → France
{'totalResultsCount': 96685, 'geonames': [{'adminCode1': '15', 'lng': '15.2066', 'geonameId': 2686657, 'toponymName': 'Örebro', 'countryId': '2661886', 'fcl': 'P', 'population': 155989, 'countryCode': 'SE', 'name': 'Örebro', 'fclName': 'city, village,...', 'adminCodes1': {'ISO3166_2': 'T'}, 'countryName': 'Suède', 'fcodeName': 'seat of a first-order administrative division', 'adminName1': 'Örebro', 'lat': '59.27412', 'fcode': 'PPLA'}]}
✓ ('de Suède', 'null, null, Suède') → Suède
{'totalResultsCount': 1, 'geonames': [{'adminCode1': '00', 'lng': '-68', 'geonameId': 3841798, 'toponymName': 'Patagonia', 'countryId': '3865483', 'fcl': 'L', 'population': 0, 'countryCode': 'AR', 'name': 'Patagonie', 'fclName': 'parks,area, ...', 'countryName': 'Argentine', 'fcodeName': 'region', 'adminName1': '', 'lat': '-44', 'fcode': 'RGN'}]}
✓ ('Patagonie', 'Patagonie, null, Argentine/Chili') → Argentine
{'totalResultsCount': 387859, 'geonames': [{'adminCode1': '00', 'lng': '4.5', 'geonameId': 2802361, 'toponymName': 'Kingdom of Belgium', 'countryId': '2802361', 'fcl': 'A', 'population': 11422068, 'countryCode': 'BE', 'name': 'Belgique', 'fclName': 'country, state, region,...', 'countryName': 'Belgique', 'fcodeName': 'independent political entity', 'adminName1': '', 'lat': '50.75', 'fcode': 'PCLI'}]}
✓ ('Belgique', 'Belgique, null, Belgique') → Belgique
{'totalResultsCount': 11354, 'geonames': [{'adminCode1': '00', 'lng': '19.5', 'geonameId': 3057568, 'toponymName': 'Slovak Republic', 'countryId': '3057568', 'fcl': 'A', 'population': 5447011, 'countryCode': 'SK', 'name': 'Slovaquie', 'fclName': 'country, state, region,...', 'countryName': 'Slovaquie', 'fcodeName': 'independent political entity', 'adminName1': '', 'lat': '48.66667', 'fcode': 'PCLI'}]}
✓ ('Slovaquie', 'Slovaquie, null, Slovaquie') → Slovaquie
{'totalResultsCount': 0, 'geonames': []}
✗ ('gare de Przemysl', 'Gare de Przemyśl, Przemyśl, Pologne') → non trouvé
{'totalResultsCount': 5, 'geonames': [{'adminCode1': '16', 'lng': '126.38556', 'geonameId': 1988923, 'toponymName': 'Dokdo', 'countryId': '1835841', 'fcl': 'T', 'population': 0, 'countryCode': 'KR', 'name': 'Dokdo', 'fclName': 'mountain,hill,rock,... ', 'adminCodes1': {'ISO3166_2': '46'}, 'countryName': 'Corée du Sud', 'fcodeName': 'island', 'adminName1': 'Jeollanam-do', 'lat': '34.69889', 'fcode': 'ISL'}]}
✓ ('Dokdo', 'Dokdo, Mer du Japon, Corée du Sud') → Corée du Sud
{'totalResultsCount': 108, 'geonames': [{'adminCode1': '72', 'lng': '13.98354', 'geonameId': 2218840, 'toponymName': 'Bani Walid', 'countryId': '2215636', 'fcl': 'P', 'population': 45734, 'countryCode': 'LY', 'name': 'Beni Ulid', 'fclName': 'city, village,...', 'adminCodes1': {'ISO3166_2': 'MI'}, 'countryName': 'Libye', 'fcodeName': 'populated place', 'adminName1': 'Mişrātah', 'lat': '31.74554', 'fcode': 'PPL'}]}
✓ ('Bani Walid', 'Bani Walid, Misrata, Libye') → Libye
{'totalResultsCount': 0, 'geonames': []}
✗ ('théâtre de La Manicle', 'Théâtre de La Manicle, Besançon, France') → non trouvé

In [100]:
for lieu in non_trouves:
    for tentative in range(3):
        try:
            res = geocode(lieu)
            if res:
                resultats.append(res)
                print(f"✓ {lieu} → {res['pays']}")
            else:
                print(f"✗ {lieu} → non trouvé")
            break
        except requests.exceptions.ConnectionError:
            print(f"⚠ Réseau KO, attente 30s (tentative {tentative+1}/3)...")
            time.sleep(30)
    
    time.sleep(1.1)

✗ ('Bordeaux Rive Gauche', 'Bordeaux Rive Gauche, Bordeaux, France') → non trouvé
✗ ('rue Bruat', 'rue Bruat, ville inconnue, France') → non trouvé
✗ ('Ekallatum', 'Ekallatum, site antique, Irak') → non trouvé
✗ ('esplanade Francois Mitterand', 'Esplanade François Mitterrand, Paris, France') → non trouvé
✗ ('Saut de la Mounine', 'Saut de la Mounine, Lot, France') → non trouvé
✗ ('rue de la Juiverie', 'rue de la Juiverie, Paris, France') → non trouvé
✗ ("hôpital Saint-Jean d'Arras", "hôpital Saint-Jean d'Arras, Arras, France") → non trouvé
✗ ('Rochefort ~ Oléron', "Rochefort-sur-Mer / Île d'Oléron, Charente-Maritime, France") → non trouvé
✗ ('Boussoufa', 'Boussoufa, Médenine, Tunisie') → non trouvé
✗ ('gare de Cluj', 'Gare de Cluj, Cluj-Napoca, Roumanie') → non trouvé
✗ ('Berkendael', 'Berkendael, Saint-Gilles, Belgique') → non trouvé
✗ ('baie de Ficajola', 'baie de Ficajola, Piana, France') → non trouvé
✗ ('Promenades boulevard de la Chalotais', 'Boulevard de la Chalotais, Rennes, France') → non trouvé
✗ ('boulevard de Châtenay', 'Boulevard de Châtenay, Paris, France') → non trouvé
✗ ('outre-Manche', 'Outre-Manche, Royaume-Uni, Royaume-Uni') → non trouvé
✗ ("Musée d'art moderne de New York", "Musée d'art moderne de New York, New York, États-Unis") → non trouvé
✗ ('mont Vinson', 'Mont Vinson, Antarctique') → non trouvé
✗ ('Pic Saint-Louis-Gangeois', 'Pic Saint-Louis, Ganges, France') → non trouvé
✗ ('place Saint-Jean Lyon 9E Brocante Organisée par la', 'Place Saint-Jean, Lyon 9e, France') → non trouvé
✗ ('chapelle Notre-Dame du Vincin', 'chapelle Notre-Dame du Vincin, Arradon, France') → non trouvé
✗ ('Boulevard Lucien-Arnault', 'Boulevard Lucien-Arnault, Vincennes, France') → non trouvé
✗ ('gare de Przemysl', 'Gare de Przemyśl, Przemyśl, Pologne') → non trouvé
✗ ('théâtre de La Manicle', 'Théâtre de La Manicle, Besançon, France') → non trouvé
✗ ('Casino Barrière de Deauville', 'Casino Barrière, Deauville, France') → non trouvé
✗ ('rue de Savenay', 'rue de Savenay, Paris, France') → non trouvé
✗ ('RDCongo)', 'République Démocratique du Congo, null, République Démocratique du Congo') → non trouvé
✗ ('Alpes suisses', 'Alpes suisses, Suisse') → non trouvé
✗ ('Cartoucherie de Vincennes', 'Cartoucherie de Vincennes, Vincennes, France') → non trouvé
✗ ('Haute Cour de Justice de Londres', 'Haute Cour de Justice, Londres, Royaume-Uni') → non trouvé
✗ ('Tchéco-slovaquie', 'Tchécoslovaquie, null, Tchécoslovaquie') → non trouvé
✗ ("rue Chabot-d'Allier", "rue Chabot-d'Allier, Vichy, France") → non trouvé
✗ ('vallée du Flon', 'Vallée du Flon, Lausanne, Suisse') → non trouvé
✗ ('émirats du Golfe', 'Émirats du Golfe, Péninsule arabique, Moyen-Orient') → non trouvé
✗ ('diocèse de Toulouse', 'diocèse de Toulouse, Toulouse, France') → non trouvé
✗ ('Rif marocain', 'Rif, Nord du Maroc, Maroc') → non trouvé
✗ ('Erythrée', 'Érythrée, Érythrée, Érythrée') → non trouvé
✗ ('parc Delessert', 'Parc Delessert, Paris, France') → non trouvé
✗ ('Boulogne- Levallois', 'Boulogne-Billancourt / Levallois-Perret, Île-de-France, France') → non trouvé
✗ ('Territoires palestiniens', 'Territoires palestiniens, null, Palestine') → non trouvé
✗ ('rue Basse-Porte', 'rue Basse-Porte, null, null') → non trouvé
✗ ('théâtre des Jacobins', 'Théâtre des Jacobins, Toulouse, France') → non trouvé
✗ ('forêt de Posada', 'Forêt de Posada, Posada, Italie') → non trouvé
✗ ('Théâtre de Babylone', 'Théâtre de Babylone, Paris, France') → non trouvé
✗ ('lycée Saint-Yves', 'lycée Saint-Yves, Rennes, France') → non trouvé
✗ ('plateau du Golan', 'plateau du Golan, Golan, Syrie/Israël') → non trouvé
✗ ('boulevard du Grand-Cerf', 'Boulevard du Grand-Cerf, Paris, France') → non trouvé
✗ ('Kierling A Vienne', 'Kierling, Vienne, Autriche') → non trouvé
✗ ('Sûreté urbaine de Lille', 'Sûreté urbaine, Lille, France') → non trouvé
✗ ('Milan ROME', 'Milan/Rome, null, Italie') → non trouvé
✗ ('désert mauritanien', 'Désert, Mauritanie, Mauritanie') → non trouvé
✗ ("mer d'Aden", "Mer d'Aden, null, null") → non trouvé
✗ ('Extrême-Orient russe', 'Extrême-Orient russe, Russie') → non trouvé
✗ ('Océan de la Tranquillité', 'Mer de la Tranquillité, Lune') → non trouvé
✗ ('Château Lamontagne', 'Château Lamontagne, Saint-Yrieix-sur-Charente, France') → non trouvé
✗ ('forêt de Galfingue', 'Forêt de Galfingue, Galfingue, France') → non trouvé
✗ ('Musée des beaux-arts du Locle', 'Musée des beaux-arts du Locle, Le Locle, Suisse') → non trouvé
✗ ('Gois  Basse mer', 'Passage du Gois, Noirmoutier, France') → non trouvé
✗ ('université de Versailles Saint-Quentin', 'Université de Versailles Saint-Quentin-en-Yvelines, Versailles, France') → non trouvé
✗ ('Fallouja', 'Fallouja, Fallouja, Irak') → non trouvé
✗ ('République populaire de Louhansk', 'République populaire de Louhansk, Louhansk, Ukraine') → non trouvé
✗ ('Bahia Golf Beach', 'Bahia Golf Beach, Agadir, Maroc') → non trouvé
✗ ('quartier de Sonagachi', 'Sonagachi, Kolkata, Inde') → non trouvé
✗ ('Radwanli', 'Radwanli, Radwanli, Syrie') → non trouvé
✗ ('rue Travot', 'Rue Travot, Paris, France') → non trouvé
✗ ('Bourse de Bangkok', 'Bourse de Bangkok, Bangkok, Thaïlande') → non trouvé
✗ ('Chambre des communes', 'Chambre des communes, Londres, Royaume-Uni') → non trouvé
✗ ('avenue de la Canebière', 'avenue de la Canebière, Marseille, France') → non trouvé
✗ ('Elbrouz', 'Mont Elbrouz, Kabardino-Balkarie, Russie') → non trouvé
✗ ('Jardin royal des plantes médicinales', 'Jardin royal des plantes médicinales, Londres, Royaume-Uni') → non trouvé
✗ ("REVOLTES DE L'ÎLE DU DIABLE", 'Île du Diable, Île du Diable, Guyane française') → non trouvé
✗ ('Province du Brabant flamand - n.a.v', 'Province du Brabant flamand, Louvain, Belgique') → non trouvé
✗ ('Petaux', 'Petaux, Orne, France') → non trouvé
✗ ("Cour d'appel de Lisbonne", "Cour d'appel de Lisbonne, Lisbonne, Portugal") → non trouvé
✗ ('Cascades du Hérisson', 'Cascades du Hérisson, Clairvaux-les-Lacs, France') → non trouvé
✗ ('Suisse alémanique', 'Suisse alémanique, Suisse') → non trouvé
✗ ('Promenade nantaise', 'Promenade nantaise, Nantes, France') → non trouvé
✗ ('Dausque', 'Dusque, Andalousie, Espagne') → non trouvé
✗ ('mont Pirin', 'Mont Pirin, Blagoevgrad, Bulgarie') → non trouvé
✗ ("jardin Jeanne d'Arc", "Jardin Jeanne d'Arc, Paris, France") → non trouvé
✗ ('Loire  Nord Littoral', 'Loire Nord Littoral, France') → non trouvé
✗ ('Indochine française', 'Indochine française, Asie du Sud-Est, France (ancienne colonie)') → non trouvé
✗ ('Gironde Libournais Blayais', 'Libournais Blayais, Gironde, France') → non trouvé
✗ ("Saint-Georges d'argent", "Saint-Georges-d'Argent, Auvergne-Rhône-Alpes, France") → non trouvé
✗ ('5e circonscription des Alpes-Maritimes', '5e circonscription des Alpes-Maritimes, Alpes-Maritimes, France') → non trouvé
✗ ("Cirque d'hiver Bouglione", "Cirque d'Hiver Bouglione, Paris, France") → non trouvé
✗ ('Uotsurijima', 'Uotsurijima, Îles Senkaku, Japon') → non trouvé
✗ ('bâtiment Baltard', 'Bâtiment Baltard, Paris, France') → non trouvé
✗ ('Centre Pompidou)à Tokyo', 'Centre Pompidou, Tokyo, Japon') → non trouvé
✗ ("États d'Asie centrale", 'Asie centrale, null, null') → non trouvé
✗ ('Amérique Latine', 'Amérique Latine, null, null') → non trouvé
✗ ('rue Fernand-Chapsal', 'rue Fernand-Chapsal, null, France') → non trouvé
✗ ('rue Laurier', 'rue Laurier, null, null') → non trouvé
✗ ('cathédrale de Trondheim', 'cathédrale de Nidaros, Trondheim, Norvège') → non trouvé
✗ ('Tranié', 'Tranié, Tranié, France') → non trouvé
✗ ('royaume des Deux-Siciles', 'Royaume des Deux-Siciles, Naples, Italie') → non trouvé
✗ ('Extrême-Orient', "Extrême-Orient, Asie de l'Est, Asie") → non trouvé
✗ ('Etat de Rio de Janeiro', 'État de Rio de Janeiro, Rio de Janeiro, Brésil') → non trouvé
✗ ('lac du bois de Boulogne', 'Lac du Bois de Boulogne, Paris, France') → non trouvé
✗ ('rue Charlevoix-de-Villers', 'rue Charlevoix-de-Villers, Paris, France') → non trouvé
✗ ('Palais des colonies', 'Palais des colonies, Bruxelles, Belgique') → non trouvé
✗ ('centrale nucléaire de Marcoule', 'Centrale nucléaire de Marcoule, Marcoule, France') → non trouvé
✗ ('Couvent rouge de Reval', 'Couvent rouge, Tallinn, Estonie') → non trouvé
✗ ('Baionarena', 'Baionarena, Bilbao, Espagne') → non trouvé
✗ ('château du Glandier', 'Château du Glandier, Corrèze, France') → non trouvé
✗ ('TRANSMIS CôteIvoire', "Côte d'Ivoire, null, Côte d'Ivoire") → non trouvé
✗ ('Cimetière-Musée San Pedro', 'Cimetière-Musée San Pedro, Medellín, Colombie') → non trouvé
✗ ('Slantchev briag', 'Slantchev Bryag, Burgas, Bulgarie') → non trouvé
✗ ('hôtel de police de Montbéliard', 'Hôtel de police, Montbéliard, France') → non trouvé
✗ ('porte de Heusy', 'Porte de Heusy, Verviers, Belgique') → non trouvé
✗ ('chambre des Communes', 'Chambre des communes, Londres, Royaume-Uni') → non trouvé
✗ ('Montalier', 'Montalier, Ain, France') → non trouvé
✗ ('Porto Santo/ Dakar VOLLEY-BALL', 'Porto Santo, Dakar, Sénégal') → non trouvé
✗ ('quartier Madeleine-Champ-de- Mars', 'Quartier Madeleine-Champ-de-Mars, Paris, France') → non trouvé
✗ ('Pré-Gauchet', 'Pré-Gauchet, Genève, Suisse') → non trouvé
✗ ('Afrique subsaharienne', 'Afrique subsaharienne, Afrique subsaharienne, Afrique') → non trouvé
✗ ('Qc J1S', 'J1S, Saint-Hyacinthe, Canada') → non trouvé
✗ ('Centre Mémorial des Victimes du Terrorisme de Vitoria', 'Centre Mémorial des Victimes du Terrorisme, Vitoria-Gasteiz, Espagne') → non trouvé
✗ ("Cantons de l'Est", "Cantons de l'Est, Liège, Belgique") → non trouvé
✗ ('Nollywood', 'Nollywood, Lagos, Nigeria') → non trouvé
✗ ('fédération des Emirats arabes unis', 'Émirats arabes unis, Émirats arabes unis, Émirats arabes unis') → non trouvé
✗ ('Théâtre du Trident', 'Théâtre du Trident, Québec, Canada') → non trouvé
✗ ('église Sainte-Marie-des-Anges de Wellington', 'Église Sainte-Marie-des-Anges, Wellington, Nouvelle-Zélande') → non trouvé
✗ ('Charleroi-Central', 'Gare de Charleroi-Central, Charleroi, Belgique') → non trouvé
✗ ("pays d'Égypte", 'Égypte, null, Égypte') → non trouvé
✗ ('Mosellan', 'Moselle, null, France') → non trouvé
✗ ('Clermont-Limagne', 'Clermont-Limagne, Clermont-Limagne, France') → non trouvé
✗ ('Transmusicales de Rennes', 'Transmusicales de Rennes, Rennes, France') → non trouvé
✗ ('îles Senkaku', 'îles Senkaku, îles Senkaku, Mer de Chine orientale') → non trouvé
✗ ('Théâtre du Soleil', 'Théâtre du Soleil, Vincennes, France') → non trouvé
✗ ('Elbow River Healing Lodge', 'Elbow River Healing Lodge, Calgary, Canada') → non trouvé
✗ ("MJC de l'Harteloire", "MJC de l'Harteloire, Brest, France") → non trouvé
✗ ('ZAC Paris-Rive gauche', 'ZAC Paris-Rive Gauche, Paris, France') → non trouvé
✗ ('Oulamara', 'Oulamara, Algérie') → non trouvé
✗ ('Orchestre de Picardie', 'Picardie, null, France') → non trouvé
✗ ('Khouzestan', 'Khouzestan, Khouzestan, Iran') → non trouvé
✗ ('Mandchou', 'Mandchourie, , Chine') → non trouvé
✗ ('Corées', 'Corée, Asie') → non trouvé
✗ ('Mokhran', 'Mokhran, Baloutchistan, Iran') → non trouvé
✗ ('Plourin-Ploudalmézeau', 'Plourin-Ploudalmézeau, Brest, France') → non trouvé
✗ ('église évangélique de Froges(Isère', 'Église évangélique de Froges, Froges, France') → non trouvé
✗ ('mer de Tasmanie', 'mer de Tasmanie, Océan Pacifique Sud') → non trouvé
✗ ('Albanieà', 'null, null, Albanie') → non trouvé
✗ ('Ostie', 'Ostie, Rome, Italie') → non trouvé
✗ ('grand barrage de Sivens TOULOUSE', 'Sivens, Toulouse, France') → non trouvé
✗ ('université de  Lille III', 'Université de Lille III, Lille, France') → non trouvé
✗ ('Vaurien', 'Vaurien, Cergy, France') → non trouvé
✗ ('Suburre', 'Subure, Rome, Italie') → non trouvé
✗ ('Sahel - de 2 500 hectares', "Sahel, Afrique de l'Ouest, Afrique") → non trouvé
✗ ('Tosa-Klause', 'Tosa-Klause, Ötztal, Autriche') → non trouvé
✗ ('Strasberg', 'Strasberg, Bas-Rhin, France') → non trouvé
✗ ('Prillaz', 'Prillaz, Grolley, Suisse') → non trouvé
✗ ('Théâtre Claude Volter', 'Théâtre Claude Volter, Ixelles, Belgique') → non trouvé
✗ ('Mont-sur-Marchiennes', 'Mont-sur-Marchiennes, Douai, France') → non trouvé
✗ ('rue Rodo', 'Rue Rodo, null, null') → non trouvé
✗ ('hôpital Louis-H. Lafontaine', 'Hôpital Louis-H. Lafontaine, Montréal, Canada') → non trouvé
✗ ('Noirceuil', 'Noirceuil, Noirceuil, Belgique') → non trouvé
✗ ('Nouvelle République du Centre-Ouest  ', 'Nouvelle République du Centre-Ouest, Tours, France') → non trouvé
✗ ('avenue Joffre', 'Avenue Joffre, null, null') → non trouvé
✗ ('Bouquy', 'Bouquy, Beautiran, France') → non trouvé
✗ ('rue des  Verreries', 'Rue des Verreries, Montpellier, France') → non trouvé
✗ ('autoroute E40', 'Autoroute E40, Europe') → non trouvé
✗ ('Thiers- Ambert', 'Thiers-Ambert, Thiers, France') → non trouvé
✗ ("l'Afrique noire", 'Afrique subsaharienne, Afrique') → non trouvé
✗ ('Afrique noire', 'Afrique subsaharienne, null, Afrique') → non trouvé
✗ ('Riviera vaudoise', 'Riviera vaudoise, Vaud, Suisse') → non trouvé
✗ ('Olympic Center Ventspils', 'Olympic Center Ventspils, Ventspils, Lettonie') → non trouvé
✗ ('Sainte-Pélagie', 'Sainte-Pélagie, Paris, France') → non trouvé
✗ ('fleuve Xingu', 'fleuve Xingu, null, Brésil') → non trouvé
✗ ('rue Bias', 'Rue Bias, Paris, France') → non trouvé
✗ ('États allemands', 'États allemands, Allemagne') → non trouvé
✗ ('États centrasiatiques', 'Asie centrale, null, null') → non trouvé
✗ ('rue du Commandant-Drogou', 'rue du Commandant-Drogou, null, France') → non trouvé
✗ ('Plateau iranien', 'Plateau iranien, null, Iran') → non trouvé
✗ ('rue des Carmélites', 'rue des Carmélites, null, France') → non trouvé
✗ ('TC Bruxelles', 'Tribunal de Commerce, Bruxelles, Belgique') → non trouvé
✗ ("Cour d'assises de l'Ain", "Cour d'assises de l'Ain, Bourg-en-Bresse, France") → non trouvé
✗ ('passage Colbert', 'Passage Colbert, Paris, France') → non trouvé
✗ ('Luisanciers', 'Luisanciers, Jura, France') → non trouvé
✗ ('rue Lesueur', 'rue Lesueur, Paris, France') → non trouvé
✗ ('Nouvelle République du Centre-Ouest', 'Nouvelle République du Centre-Ouest, Tours, France') → non trouvé
✗ ('avenue Xavier-Rineau', 'Avenue Xavier-Rineau, Bouguenais, France') → non trouvé
✗ ('Est de la République démocratique du Congo', 'Est de la République démocratique du Congo, null, République démocratique du Congo') → non trouvé
✗ ('rue des Vignolles', 'Rue des Vignolles, Paris, France') → non trouvé
✗ ('Alpes françaises', 'Alpes françaises, null, France') → non trouvé
✗ ('Cité des Doges', 'Cité des Doges, Venise, Italie') → non trouvé
✗ ('rue Ermengaud', 'Rue Ermengaud, Nîmes, France') → non trouvé

In [124]:
def geocode_nominatim_structure(lieu_str):
    """lieu_str = 'Ville, Région, Pays' ou 'Ville, Pays'"""
    parts = [p.strip() for p in lieu_str.split(",")]
    
    url = "https://nominatim.openstreetmap.org/search"
    headers = {"User-Agent": "corpus-research/1.0", "Accept-Language": "fr"}
    params = {
        #"city": parts[1] if len(parts) > 1 else parts[0],
        "country": parts[2] if len(parts) > 2 else parts[-1],
        "format": "json", "limit": 1, "addressdetails": 1
    }
    try:
        r = requests.get(url, params=params, headers=headers, timeout=10)
        data = r.json()
        if data:
            d = data[0]
            return {
                "nom": lieu_str,
                "lat": float(d["lat"]), "lon": float(d["lon"]),
                "pays": d["address"].get("country", ""),
                "code_pays": d["address"].get("country_code", "").upper(),
                "nom_complet": d["display_name"],
                "source": "nominatim_struct"
            }
    except requests.exceptions.ConnectionError:
        time.sleep(30)
    return None

In [125]:
for lieu in non_trouves:
    for tentative in range(3):
        try:
            res = geocode_nominatim_structure(lieu[1])
            if res:
                resultats.append(res)
                print(f"✓ {lieu} → {res['pays']}")
            else:
                print(f"✗ {lieu} → non trouvé")
            break
        except requests.exceptions.ConnectionError:
            print(f"⚠ Réseau KO, attente 30s (tentative {tentative+1}/3)...")
            time.sleep(30)
    
    time.sleep(1.1)

✓ ('rue Bruat', 'rue Bruat, ville inconnue, France') → France
✓ ('Ekallatum', 'Ekallatum, site antique, Irak') → Irak
✓ ('Saut de la Mounine', 'Saut de la Mounine, Lot, France') → France
✓ ('Rochefort ~ Oléron', "Rochefort-sur-Mer / Île d'Oléron, Charente-Maritime, France") → France
✓ ('outre-Manche', 'Outre-Manche, Royaume-Uni, Royaume-Uni') → Royaume-Uni
✗ ('mont Vinson', 'Mont Vinson, Antarctique') → non trouvé
✓ ('RDCongo)', 'République Démocratique du Congo, null, République Démocratique du Congo') → République démocratique du Congo
✓ ('Alpes suisses', 'Alpes suisses, Suisse') → Suisse
✗ ('Tchéco-slovaquie', 'Tchécoslovaquie, null, Tchécoslovaquie') → non trouvé
✗ ('émirats du Golfe', 'Émirats du Golfe, Péninsule arabique, Moyen-Orient') → non trouvé
✓ ('Rif marocain', 'Rif, Nord du Maroc, Maroc') → Maroc
✓ ('Erythrée', 'Érythrée, Érythrée, Érythrée') → Érythrée
✓ ('Boulogne- Levallois', 'Boulogne-Billancourt / Levallois-Perret, Île-de-France, France') → France
✗ ('Territoires palestiniens', 'Territoires palestiniens, null, Palestine') → non trouvé
✗ ('rue Basse-Porte', 'rue Basse-Porte, null, null') → non trouvé
✗ ('plateau du Golan', 'plateau du Golan, Golan, Syrie/Israël') → non trouvé
✓ ('Milan ROME', 'Milan/Rome, null, Italie') → Italie
✗ ("mer d'Aden", "Mer d'Aden, null, null") → non trouvé
✓ ('Extrême-Orient russe', 'Extrême-Orient russe, Russie') → Russie
✗ ('Océan de la Tranquillité', 'Mer de la Tranquillité, Lune') → non trouvé
✓ ('Radwanli', 'Radwanli, Radwanli, Syrie') → Syrie
✓ ('Elbrouz', 'Mont Elbrouz, Kabardino-Balkarie, Russie') → Russie
✗ ("REVOLTES DE L'ÎLE DU DIABLE", 'Île du Diable, Île du Diable, Guyane française') → non trouvé
✓ ('Petaux', 'Petaux, Orne, France') → France
✓ ('Suisse alémanique', 'Suisse alémanique, Suisse') → Suisse
✓ ('Dausque', 'Dusque, Andalousie, Espagne') → Espagne
✓ ('Loire  Nord Littoral', 'Loire Nord Littoral, France') → France
✗ ('Indochine française', 'Indochine française, Asie du Sud-Est, France (ancienne colonie)') → non trouvé
✓ ('Gironde Libournais Blayais', 'Libournais Blayais, Gironde, France') → France
✓ ("Saint-Georges d'argent", "Saint-Georges-d'Argent, Auvergne-Rhône-Alpes, France") → France
✓ ('5e circonscription des Alpes-Maritimes', '5e circonscription des Alpes-Maritimes, Alpes-Maritimes, France') → France
✓ ('Uotsurijima', 'Uotsurijima, Îles Senkaku, Japon') → Japon
✗ ('Amérique Latine', 'Amérique Latine, null, null') → non trouvé
✗ ('rue Laurier', 'rue Laurier, null, null') → non trouvé
✓ ('Tranié', 'Tranié, Tranié, France') → France
✗ ('Extrême-Orient', "Extrême-Orient, Asie de l'Est, Asie") → non trouvé
✓ ('TRANSMIS CôteIvoire', "Côte d'Ivoire, null, Côte d'Ivoire") → Côte d’Ivoire
✗ ('Afrique subsaharienne', 'Afrique subsaharienne, Afrique subsaharienne, Afrique') → non trouvé
✓ ('fédération des Emirats arabes unis', 'Émirats arabes unis, Émirats arabes unis, Émirats arabes unis') → Émirats arabes unis
✓ ('Clermont-Limagne', 'Clermont-Limagne, Clermont-Limagne, France') → France
✗ ('îles Senkaku', 'îles Senkaku, îles Senkaku, Mer de Chine orientale') → non trouvé
✓ ('Oulamara', 'Oulamara, Algérie') → Algérie
✓ ('Khouzestan', 'Khouzestan, Khouzestan, Iran') → Iran
✗ ('Corées', 'Corée, Asie') → non trouvé
✓ ('Mokhran', 'Mokhran, Baloutchistan, Iran') → Iran
✗ ('mer de Tasmanie', 'mer de Tasmanie, Océan Pacifique Sud') → non trouvé
✓ ('Albanieà', 'null, null, Albanie') → Albanie
✗ ('Sahel - de 2 500 hectares', "Sahel, Afrique de l'Ouest, Afrique") → non trouvé
✓ ('Tosa-Klause', 'Tosa-Klause, Ötztal, Autriche') → Autriche
✓ ('Strasberg', 'Strasberg, Bas-Rhin, France') → France
✗ ('rue Rodo', 'Rue Rodo, null, null') → non trouvé
✓ ('Noirceuil', 'Noirceuil, Noirceuil, Belgique') → Belgique
✗ ('avenue Joffre', 'Avenue Joffre, null, null') → non trouvé
✗ ('autoroute E40', 'Autoroute E40, Europe') → non trouvé
✗ ("l'Afrique noire", 'Afrique subsaharienne, Afrique') → non trouvé
✗ ('Afrique noire', 'Afrique subsaharienne, null, Afrique') → non trouvé
✓ ('Riviera vaudoise', 'Riviera vaudoise, Vaud, Suisse') → Suisse
✓ ('fleuve Xingu', 'fleuve Xingu, null, Brésil') → Brésil
✓ ('États allemands', 'États allemands, Allemagne') → Allemagne
✓ ('Plateau iranien', 'Plateau iranien, null, Iran') → Iran
✓ ('Luisanciers', 'Luisanciers, Jura, France') → France
✓ ('Est de la République démocratique du Congo', 'Est de la République démocratique du Congo, null, République démocratique du Congo') → République démocratique du Congo

In [126]:
for result in resultats:
    if len(result["nom"]) != 2:
        for pays in liste_pays:
            if pays[1] == result["nom"]:
                result["nom"] = pays

In [117]:
liste_pays

[('Saint-Étienne-du-Rouvray',
  'Saint-Étienne-du-Rouvray, Saint-Étienne-du-Rouvray, France'),
 ('Abou Kémal', 'Abu Kamal, Deir ez-Zor, Syrie'),
 ('Perros-Guirec', 'Perros-Guirec, Perros-Guirec, France'),
 ('Saint-Gaudens', 'Saint-Gaudens, Saint-Gaudens, France'),
 ('Carmel', 'Carmel, Californie, États-Unis'),
 ('Philippines', 'Philippines, Philippines, Philippines'),
 ('Lower Mainland', 'Lower Mainland, Vancouver, Canada'),
 ('Chalon', 'Chalon-sur-Saône, Chalon-sur-Saône, France'),
 ('New York underground', 'New York, New York, États-Unis'),
 ('bibliothèque de Fontevraud',
  "Fontevraud-l'Abbaye, Fontevraud-l'Abbaye, France"),
 ('Bordeaux Rive Gauche', 'Bordeaux Rive Gauche, Bordeaux, France'),
 ('MONTLUCON', 'Montluçon, Montluçon, France'),
 ("Europe de l'Est", "Europe de l'Est"),
 ('Kamogawa', 'Kamogawa, Kamogawa, Japon'),
 ('Lens', 'Lens, Lens, France'),
 ('Calcuta', 'Kolkata, Kolkata, Inde'),
 ('rue Saint-Martin', 'Rue Saint-Martin, Paris, France'),
 ("green d'Augusta", 'Augusta National Golf Club, Augusta, États-Unis'),
 ("L'Espagne", 'Espagne, Espagne, Espagne'),
 ('Bruxelles', 'Bruxelles, Bruxelles, Belgique'),
 ('Broadway', 'Broadway, New York, États-Unis'),
 ('Valserine', 'Valserine, Ain, France'),
 ('Odéon', 'Odéon, Paris, France'),
 ('Louvigné-du-Désert', 'Louvigné-du-Désert, Fougères, France'),
 ("Côte d'Ivoire", "Côte d'Ivoire, Afrique de l'Ouest"),
 ('Finistère', 'Finistère, Quimper, France'),
 ('LISBONNE', 'Lisbonne, Lisbonne, Portugal'),
 ('Basilique Saint-Pierre', 'Basilique Saint-Pierre, Vatican, Vatican'),
 ('Khabarovsk', 'Khabarovsk, Khabarovsk, Russie'),
 ('Le Havre', 'Le Havre, Le Havre, France'),
 ('Théâtre de Gennevilliers',
  'Théâtre de Gennevilliers, Gennevilliers, France'),
 ('Montmartre', 'Montmartre, Paris, France'),
 ('Gonesse', 'Gonesse, Gonesse, France'),
 ('Orlando', 'Orlando, Orlando, États-Unis'),
 ('rue Bruat', 'rue Bruat, ville inconnue, France'),
 ('Centrafrique', 'Centrafrique, Bangui, République centrafricaine'),
 ('Woodlands', 'Woodlands, Singapour, Singapour'),
 ('Gagnoa', "Gagnoa, Gagnoa, Côte d'Ivoire"),
 ('la Bolivie', 'Bolivie, Sucre, Bolivie'),
 ('Ekallatum', 'Ekallatum, site antique, Irak'),
 ("Val de l'Aurence", "Val de l'Aurence, Limoges, France"),
 ('Brésil', 'Brésil, Brasília, Brésil'),
 ("L'Elysée", "Palais de l'Élysée, Paris, France"),
 ('lycée Thiers', 'Lycée Thiers, Marseille, France'),
 ('Mangin île Beaulieu', 'Île Beaulieu, Nantes, France'),
 ('Strasbourg', 'Strasbourg, Strasbourg, France'),
 ('Turque', 'Turquie'),
 ("canal de l'Ourcq", "Canal de l'Ourcq, Paris, France"),
 ('Métro Saint-Laurent', 'Station Saint-Laurent, Montréal, Canada'),
 ("université d'Orléans", "Université d'Orléans, Orléans, France"),
 ('RD du Congo', 'République Démocratique du Congo'),
 ('Victor-Lagrange', 'Victor-Lagrange, Lyon, France'),
 ('Oregon City', 'Oregon City, Oregon, États-Unis'),
 ('Tala', 'Tala, Pune, Inde'),
 ('Arras', 'Arras, Arras, France'),
 ('Elvas', 'Elvas, Elvas, Portugal'),
 ('Coudekerque-Branche', 'Coudekerque-Branche, Coudekerque-Branche, France'),
 ('Lusaka', 'Lusaka, Lusaka, Zambie'),
 ('Île Guérandaise', 'Île Guérandaise, Guérande, France'),
 ('Ain', 'Ain, Bourg-en-Bresse, France'),
 ('Donbass', 'Donbass, Donbass, Ukraine'),
 ('Auvergne-Rhône-Alpes', 'Auvergne-Rhône-Alpes, Lyon, France'),
 ('argentine', 'Argentine, Buenos Aires, Argentine'),
 ('Welfare Island', 'Roosevelt Island, New York, États-Unis'),
 ('Sarthe', 'Sarthe, Pays de la Loire, France'),
 ('RAMALLAH', 'Ramallah, Ramallah, Palestine'),
 ('Saint-Lambert-la-Potherie',
  'Saint-Lambert-la-Potherie, Maine-et-Loire, France'),
 ('Windsor', 'Windsor, Berkshire, Royaume-Uni'),
 ('-Etats-Unis', 'États-Unis'),
 ('Cap Vert', 'Cap-Vert, Cap-Vert'),
 ('Saint-Valentin', 'Saint-Valentin, Indre, France'),
 ('Bonneville', 'Bonneville, Haute-Savoie, France'),
 ('KANO', 'Kano, Kano, Nigeria'),
 ('Loire- Atlantique', 'Loire-Atlantique, Pays de la Loire, France'),
 ('rue Oehlenschlægersgade', 'Oehlenschlægersgade, Copenhague, Danemark'),
 ("porte d'Anvers", "Porte d'Anvers, Bruxelles, Belgique"),
 ('Saguenay', 'Saguenay, Saguenay, Canada'),
 ('Nouméa', 'Nouméa, Nouméa, Nouvelle-Calédonie'),
 ('Estuaire', 'Estuaire, Libreville, Gabon'),
 ('Portugal de Salazar', 'Portugal, Lisbonne, Portugal'),
 ('Neuchâtel', 'Neuchâtel, Neuchâtel, Suisse'),
 ('Crouy-sur-Ourcq', 'Crouy-sur-Ourcq, Meaux, France'),
 ('Mayenne', 'Mayenne, Mayenne, France'),
 ('Catalogne', 'Catalogne, Barcelone, Espagne'),
 ('Ohio', 'Ohio, Columbus, États-Unis'),
 ('Maine', 'Maine, Augusta, États-Unis'),
 ('Madrilènes', 'Madrid, Madrid, Espagne'),
 ('Las Palmas', 'Las Palmas, Las Palmas de Gran Canaria, Espagne'),
 ('Saint-Cannat', 'Saint-Cannat, Aix-en-Provence, France'),
 ('précieuse Marbella', 'Marbella, Marbella, Espagne'),
 ('Viré', 'Viré, Saône-et-Loire, France'),
 ('Herat', 'Herat, Herat, Afghanistan'),
 ('esplanade Francois Mitterand',
  'Esplanade François Mitterrand, Paris, France'),
 ('ABEBA', 'Addis-Abeba, Addis-Abeba, Éthiopie'),
 ('La Baule', 'La Baule-Escoublac, Loire-Atlantique, France'),
 ('canton de Neuchâtel', 'Neuchâtel, Canton de Neuchâtel, Suisse'),
 ('Pyrénées', 'Pyrénées, , France/Espagne'),
 ('Lac-Etchemin', 'Lac-Etchemin, Chaudière-Appalaches, Canada'),
 ('Saint-Mesmes', 'Saint-Mesmes, Seine-et-Marne, France'),
 ('Miribel  ', 'Miribel, Ain, France'),
 ('Vilnius', 'Vilnius, Vilnius, Lituanie'),
 ("Marins d'Iroise", "Mer d'Iroise, Finistère, France"),
 ('commissariat de Roanne', 'Roanne, Loire, France'),
 ('Bic', 'Bic, Bas-Saint-Laurent, Canada'),
 ('SAINTES', 'Saintes, Nouvelle-Aquitaine, France'),
 ('Abuja', 'Abuja, Abuja, Nigeria'),
 ('Bade', 'Bade, Bade-Wurtemberg, Allemagne'),
 ('Saut de la Mounine', 'Saut de la Mounine, Lot, France'),
 ('Perrache', 'Perrache, Lyon, France'),
 ('Ambert', 'Ambert, Auvergne-Rhône-Alpes, France'),
 ('Bar-le-Duc', 'Bar-le-Duc, Grand Est, France'),
 ("Penmarc'h.", "Penmarc'h, Bretagne, France"),
 ('Italie', 'Italie'),
 ('Granma', 'Granma, Granma, Cuba'),
 ('Bristol', 'Bristol, Angleterre, Royaume-Uni'),
 ('St-Arnaud', 'Saint-Arnaud, Nouvelle-Galles du Sud, Australie'),
 ('Véragne', 'Véragne, Savoie, France'),
 ('Chalamont', 'Chalamont, Ain, France'),
 ('Binic', "Binic, Côtes-d'Armor, France"),
 ('parvis de Notre-Dame', 'Parvis de Notre-Dame, Paris, France'),
 ('Créteil Rouzerol-Douglas', 'Créteil, Val-de-Marne, France'),
 ('Beaudry', 'Beaudry, Montréal, Canada'),
 ('Ferney-Voltaire', 'Ferney-Voltaire, Ain, France'),
 ('théâtre du Pont-Tournant', 'Théâtre du Pont-Tournant, Bordeaux, France'),
 ('boulevard Dugommier', 'Boulevard Dugommier, Marseille, France'),
 ('Dioulas', 'Dioulas, Brest, France'),
 ("l'Afrique du Sud", 'Afrique du Sud'),
 ('Océanie', 'Océanie'),
 ("l'Afrique", 'Afrique, null, null'),
 ('Tajikistan', 'Tadjikistan'),
 ('Littoral', 'Littoral, Cameroun'),
 ('Le Pays basque', 'Pays basque, Espagne/France'),
 ('Souk Ahras', 'Souk Ahras, Souk Ahras, Algérie'),
 ('Laurentides', 'Laurentides, Québec, Canada'),
 ('Santander', 'Santander, Cantabrie, Espagne'),
 ('Comédie de Lille', 'Lille, Hauts-de-France, France'),
 ('Gijón', 'Gijón, Asturies, Espagne'),
 ('Tour-Eiffel', 'Tour Eiffel, Paris, France'),
 ('Riedisheim', 'Riedisheim, Haut-Rhin, France'),
 ('Trabzon', 'Trabzon, Trabzon, Turquie'),
 ('Afrique du sud', 'Afrique du Sud'),
 ('Kentucky', 'Kentucky, États-Unis'),
 ('Drôme', 'Drôme, Valence, France'),
 ('Laon', 'Laon, Laon, France'),
 ('Woodstock', 'Woodstock, Woodstock, États-Unis'),
 ('Ekaterinburg', 'Ekaterinburg, Ekaterinburg, Russie'),
 ('boulevard Montmartre', 'Boulevard Montmartre, Paris, France'),
 ('Haasdonk', 'Haasdonk, Beveren, Belgique'),
 ('Baumettes', 'Baumettes, Marseille, France'),
 ("Conservatoire d'Avignon", "Conservatoire d'Avignon, Avignon, France"),
 ('Bazar de la Charité', 'Bazar de la Charité, Paris, France'),
 ('rue de la Juiverie', 'rue de la Juiverie, Paris, France'),
 ("hôpital Saint-Jean d'Arras", "hôpital Saint-Jean d'Arras, Arras, France"),
 ('Rochefort ~ Oléron',
  "Rochefort-sur-Mer / Île d'Oléron, Charente-Maritime, France"),
 ('Rome', 'Rome, Rome, Italie'),
 ('Troie', 'Troie, Çanakkale, Turquie'),
 ('aéroport de Roissy',
  'Aéroport Charles-de-Gaulle, Roissy-en-France, France'),
 ('Finlande', 'Finlande, Finlande, Finlande'),
 ('Anticosti', "Île d'Anticosti, Québec, Canada"),
 ('Boussoufa', 'Boussoufa, Médenine, Tunisie'),
 ('Troodos', 'Massif du Troodos, Limassol, Chypre'),
 ("Val- d'Oise", "Val-d'Oise, Île-de-France, France"),
 ('rue de Tocqueville', 'rue de Tocqueville, Paris, France'),
 ("aéroport d'Orly", "Aéroport d'Orly, Orly, France"),
 ('Meuse', 'Meuse, Grand Est, France'),
 ('Cévennes', 'Cévennes, Occitanie, France'),
 ("Cap d'Agde", "Cap d'Agde, Agde, France"),
 ('Papouasie-Nouvelle-Guinée',
  'Papouasie-Nouvelle-Guinée, Port Moresby, Papouasie-Nouvelle-Guinée'),
 ('Saint-Galmier', 'Saint-Galmier, Loire, France'),
 ('Rueil-Malmaison', 'Rueil-Malmaison, Hauts-de-Seine, France'),
 ('Stains', 'Stains, Seine-Saint-Denis, France'),
 ('Montataire', 'Montataire, Oise, France'),
 ('gare de Cluj', 'Gare de Cluj, Cluj-Napoca, Roumanie'),
 ('Ouchy', 'Ouchy, Lausanne, Suisse'),
 ("Noirmoutier-en-l'Île Rendez", "Noirmoutier-en-l'Île, Vendée, France"),
 ('Ville de Laval', 'Laval, Mayenne, France'),
 ('Saint-Yrieix-la-Perche', 'Saint-Yrieix-la-Perche, Haute-Vienne, France'),
 ('Bissau', 'Bissau, Bissau, Guinée-Bissau'),
 ('Hong-Kong', 'Hong Kong, Hong Kong, Chine'),
 ("Goutte-d'Or", "Goutte-d'Or, Paris, France"),
 ('Monza', 'Monza, Monza, Italie'),
 ('Terres-de-Borde', 'Terres-de-Borde, Gironde, France'),
 ('Clairefontaine', 'Clairefontaine-en-Yvelines, Yvelines, France'),
 ('Moncalieri', 'Moncalieri, Turin, Italie'),
 ('musée Grévin', 'Musée Grévin, Paris, France'),
 ('Griffintown', 'Griffintown, Montréal, Canada'),
 ('Bergeracois', 'Bergerac, Dordogne, France'),
 ('Berkendael', 'Berkendael, Saint-Gilles, Belgique'),
 ('Fort Montbarey', 'Fort Montbarey, Brest, France'),
 ('Sagy', "Sagy, Val-d'Oise, France"),
 ('Bangkok', 'Bangkok, Bangkok, Thaïlande'),
 ('Aire-sur-la-Lys', 'Aire-sur-la-Lys, Pas-de-Calais, France'),
 ('Alberta', 'Alberta, Alberta, Canada'),
 ('Mulhouse', 'Mulhouse, Haut-Rhin, France'),
 ('Boulogne  Paris', 'Boulogne-Billancourt, Île-de-France, France'),
 ('Hochelaga-  Maisonneuve', 'Hochelaga-Maisonneuve, Montréal, Canada'),
 ('Hauts-Cantons', 'Hauts-Cantons, Estrie, Canada'),
 ('Montérégie', 'Montérégie, Québec, Canada'),
 ('TETOUAN', 'Tétouan, Tétouan-Al Hoceïma-Taza, Maroc'),
 ('Hubei', 'Hubei, Hubei, Chine'),
 ('Pyongyang', 'Pyongyang, Pyongyang, Corée du Nord'),
 ("l'Elysée", "Palais de l'Élysée, Paris, France"),
 ('Khao San Road', 'Khao San Road, Bangkok, Thaïlande'),
 ('Ndolo', 'Ndolo, Kinshasa, République démocratique du Congo'),
 ('Dar es-', 'Dar es-Salaam, Dar es-Salaam, Tanzanie'),
 ('Genève', 'Genève, Genève, Suisse'),
 ('Reims', 'Reims, Reims, France'),
 ('Vitry', 'Vitry-sur-Seine, Vitry-sur-Seine, France'),
 ('Talence', 'Talence, Bordeaux, France'),
 ('Bénin', 'Bénin, Bénin, Bénin'),
 ('Gomery', 'Gomery, Virton, Belgique'),
 ('Ambérieu', 'Ambérieu-en-Bugey, Ambérieu-en-Bugey, France'),
 ('Polynésie française', 'Polynésie française, Papeete, France'),
 ('baie de Ficajola', 'baie de Ficajola, Piana, France'),
 ('Orvault', 'Orvault, Nantes, France'),
 ('Bangalore', 'Bangalore, Bangalore, Inde'),
 ("île d'Anjouan", "île d'Anjouan, Mutsamudu, Comores"),
 ('Fruit(Canada', 'Canada, Canada, Canada'),
 ('Alpes-Maritimes', 'Alpes-Maritimes, France'),
 ('cathédrale Saint-Étienne', 'Cathédrale Saint-Étienne, Metz, France'),
 ('Var', 'Var, France'),
 ('Sousse', 'Sousse, Sousse, Tunisie'),
 ('Niort', 'Niort, Deux-Sèvres, France'),
 ('Bretagne', 'Bretagne, France'),
 ('Coquelle', 'Coquelles, Pas-de-Calais, France'),
 ('Sablette', 'La Sablette, La Seyne-sur-Mer, France'),
 ('Porto Rotondo', 'Porto Rotondo, Sardaigne, Italie'),
 ('musées du Louvre', 'Musée du Louvre, Paris, France'),
 ('Saint-Chamond', 'Saint-Chamond, Loire, France'),
 ('Taiwan', 'Taïwan, Taïwan'),
 ('mer du Nord', 'Mer du Nord, Europe'),
 ('bayonne', 'Bayonne, Bayonne, France'),
 ('Parthenay', 'Parthenay, Parthenay, France'),
 ('Coursaudière', 'Coursaudière, null, France'),
 ('Sos', 'Sos, Sos, France'),
 ('Hautes-Alpes', 'Hautes-Alpes, null, France'),
 ('Promenades boulevard de la Chalotais',
  'Boulevard de la Chalotais, Rennes, France'),
 ('Courbefy', 'Courbefy, Cheissoux, France'),
 ('Lompret', 'Lompret, Lompret, France'),
 ('musée Gustave-Moreau', 'Musée Gustave-Moreau, Paris, France'),
 ('LIMOGES', 'Limoges, Limoges, France'),
 ('rue Coat-ar-Guéven', 'Rue Coat-ar-Guéven, Brest, France'),
 ('Le Coq', 'Le Coq, De Haan, Belgique'),
 ('Canal de Suez', 'Canal de Suez, null, Égypte'),
 ('Auriol', 'Auriol, Bouches-du-Rhône, France'),
 ('boulevard de Châtenay', 'Boulevard de Châtenay, Paris, France'),
 ('Belcier', 'Belcier, Bordeaux, France'),
 ('Boos', 'Boos, Seine-Maritime, France'),
 ('Strasbourg-Saint-Denis', 'Strasbourg-Saint-Denis, Paris, France'),
 ('lac de Genève', 'Lac de Genève, Genève, Suisse'),
 ('Riviera', "Riviera, Côte d'Azur, France"),
 ('boulevard des Capucines', 'Boulevard des Capucines, Paris, France'),
 ('Le Puy-en-Velay Grande', 'Le Puy-en-Velay, Haute-Loire, France'),
 ('Aude', 'Aude, Occitanie, France'),
 ('Bosnie-Herzégovine', 'Bosnie-Herzégovine, Balkans, Europe'),
 ('Savenay', 'Savenay, Savenay, France'),
 ('centre-Bretagne', 'Centre-Bretagne, Bretagne, France'),
 ('Villa Tugendhat', 'Villa Tugendhat, Brno, République tchèque'),
 ('Iraq', 'Irak, Irak, Irak'),
 ('outre-Manche', 'Outre-Manche, Royaume-Uni, Royaume-Uni'),
 ('Neufchâtel', 'Neufchâtel, Neufchâtel-en-Bray, France'),
 ('Emmaüs Gratte-Ciel', 'Emmaüs Gratte-Ciel, Villeurbanne, France'),
 ("Villeneuve-d'Ascq", "Villeneuve-d'Ascq, Villeneuve-d'Ascq, France"),
 ('château de Vincennes', 'Château de Vincennes, Vincennes, France'),
 ('université Paris-VIII', 'Université Paris-VIII, Saint-Denis, France'),
 ('Shaolin', 'Shaolin, Dengfeng, Chine'),
 ('Lexington', 'Lexington, Lexington, États-Unis'),
 ('île Monsin', 'Île Monsin, Liège, Belgique'),
 ("Musée d'art moderne de New York",
  "Musée d'art moderne de New York, New York, États-Unis"),
 ('Égypte', 'Égypte'),
 ('Tigre', 'Tigre, Buenos Aires, Argentine'),
 ("L'Italie", 'Italie'),
 ('Pont-Tournant de Bordeaux', 'Pont-Tournant, Bordeaux, France'),
 ('du Flon', 'Flon, Lausanne, Suisse'),
 ('Mourmansk', 'Mourmansk, Mourmansk, Russie'),
 ('Palerme Palerme DE NOTRE', 'Palerme, Palerme, Italie'),
 ('Tonara', 'Tonara, Nuoro, Italie'),
 ('Grands Boulevards', 'Grands Boulevards, Paris, France'),
 ('mont Vinson', 'Mont Vinson, Antarctique'),
 ('Mondeville', 'Mondeville, Caen, France'),
 ('Porte de Versailles', 'Porte de Versailles, Paris, France'),
 ('Valenciennes', 'Valenciennes, Valenciennes, France'),
 ('Nantua', 'Nantua, Nantua, France'),
 ('rue Doudeauville', 'rue Doudeauville, Paris, France'),
 ('Galfingue', 'Galfingue, Mulhouse, France'),
 ('Tibet', 'Tibet, Tibet, Chine'),
 ('221B Baker Street', '221B Baker Street, Londres, Royaume-Uni'),
 ('Bree', 'Bree, Bree, Belgique'),
 ('Cambodge', 'Cambodge, Phnom Penh, Cambodge'),
 ('Pattani', 'Pattani, Pattani, Thaïlande'),
 ('Ouganda', 'Ouganda, Kampala, Ouganda'),
 ('Berkeley', 'Berkeley, Berkeley, États-Unis'),
 ('Mons', 'Mons, Mons, Belgique'),
 ('Cantal', 'Cantal, Aurillac, France'),
 ('Altstetten', 'Altstetten, Zurich, Suisse'),
 ('Clermont-Ferrand', 'Clermont-Ferrand, Clermont-Ferrand, France'),
 ('IIIe arrondissement de Marseille', '3e arrondissement, Marseille, France'),
 ('Damiette', 'Damiette, Damiette, Égypte'),
 ('Kenya', 'Kenya, Kenya, Kenya'),
 ('Gironde', 'Gironde, Bordeaux, France'),
 ('République de Chypre', 'Chypre, Nicosie, Chypre'),
 ('Reggio de Calabre', 'Reggio de Calabre, Reggio de Calabre, Italie'),
 ('Hongkong', 'Hong Kong, Hong Kong, Chine'),
 ('Corée-du-Sud', 'Corée du Sud, Séoul, Corée du Sud'),
 ('Bellechasse', 'Bellechasse, Québec, Canada'),
 ('Auschwitz-Monowitz', 'Auschwitz-Monowitz, Oświęcim, Pologne'),
 ('Soudan du Sud', 'Soudan du Sud, Djouba, Soudan du Sud'),
 ('Misrata', 'Misrata, Misrata, Libye'),
 ("Saint-Médard-d'Eyrans", "Saint-Médard-d'Eyrans, Bordeaux, France"),
 ('Séminaire Saint- Joseph de Trois-Rivières',
  'Séminaire Saint-Joseph de Trois-Rivières, Trois-Rivières, Canada'),
 ('Élysée', "Palais de l'Élysée, Paris, France"),
 ('Pic Saint-Louis-Gangeois', 'Pic Saint-Louis, Ganges, France'),
 ('Rize', 'Rize, Rize, Turquie'),
 ('Downtown Eastside', 'Downtown Eastside, Vancouver, Canada'),
 ('Cuba - ils', 'Cuba'),
 ('Fribourg', 'Fribourg, Fribourg, Suisse'),
 ('Grand Nancy', 'Nancy, Nancy, France'),
 ('Wuhan', 'Wuhan, Wuhan, Chine'),
 ('Cluj', 'Cluj-Napoca, Cluj-Napoca, Roumanie'),
 ('Béarn  ', 'Béarn, Pau, France'),
 ('Barbizon', 'Barbizon, Barbizon, France'),
 ('rue des Petits-Carreaux', 'Rue des Petits-Carreaux, Paris, France'),
 ('Saint-Genis-Laval Foire', 'Saint-Genis-Laval, Saint-Genis-Laval, France'),
 ('Rapides de Bourgogne', 'Rapides de Bourgogne, Bourgogne, France'),
 ('Gérone', 'Gérone, Gérone, Espagne'),
 ('Alco', 'Alco, Montpellier, France'),
 ('Vinalmont', 'Vinalmont, Huy, Belgique'),
 ('Mercoeur', 'Mercoeur, Corrèze, France'),
 ('île de la Cité', 'Île de la Cité, Paris, France'),
 ('Lavalloise', 'Laval, Québec, Canada'),
 ('Transylvanie', 'Transylvanie, Cluj-Napoca, Roumanie'),
 ('Dnipro', 'Dnipro, Dnipropetrovsk, Ukraine'),
 ('Gravelbourg', 'Gravelbourg, Saskatchewan, Canada'),
 ('Koninklijk Paleis', 'Palais Royal, Amsterdam, Pays-Bas'),
 ('Niger', 'Niger, Niamey, Niger'),
 ("Musée d'Art Mori", 'Mori Art Museum, Tokyo, Japon'),
 ('Lausannoise', 'Lausanne, Vaud, Suisse'),
 ('Pré Catelan', 'Pré Catelan, Paris, France'),
 ('Latrobe', 'Latrobe, Pennsylvanie, États-Unis'),
 ('Anglet', 'Anglet, Anglet, France'),
 ('Etats- Unis', 'États-Unis, États-Unis, États-Unis'),
 ('Saint-Molf', 'Saint-Molf, Saint-Molf, France'),
 ('Seattle', 'Seattle, Seattle, États-Unis'),
 ('Cap Corse', 'Cap Corse, Cap Corse, France'),
 ('gare Perrache', 'Gare de Lyon-Perrache, Lyon, France'),
 ('Marshalsea', 'Marshalsea, Londres, Royaume-Uni'),
 ('Huy', 'Huy, Huy, Belgique'),
 ('Jérusalem', 'Jérusalem, Jérusalem, Israël'),
 ('Porte Maillot', 'Porte Maillot, Paris, France'),
 ('Karatchaïevo-Tcherkessie',
  'Karatchaïevo-Tcherkessie, Karatchaïevo-Tcherkessie, Russie'),
 ('Iles Marshall-', 'Îles Marshall, Majuro, Îles Marshall'),
 ('Bobigny', 'Bobigny, Bobigny, France'),
 ('Valcourt', 'Valcourt, Québec, Canada'),
 ('St-Jérôme', 'Saint-Jérôme, Québec, Canada'),
 ('Rapée', 'Quai de la Rapée, Paris, France'),
 ('Besançon', 'Besançon, Bourgogne-Franche-Comté, France'),
 ('Port-Marly', 'Le Port-Marly, Île-de-France, France'),
 ('Grande bretagne', 'Grande-Bretagne, Royaume-Uni'),
 ('Beauzac Conférence', 'Beauzac, Auvergne-Rhône-Alpes, France'),
 ('Ath', 'Ath, Wallonie, Belgique'),
 ('Lavallois', 'Laval, Québec, Canada'),
 ('hôpital Saint- Pierre', 'Hôpital Saint-Pierre, Bruxelles, Belgique'),
 ('Battamgang', 'Battambang, Battambang, Cambodge'),
 ('Région de Brest Tristan', 'Brest, Bretagne, France'),
 ('République de Cuba', 'Cuba'),
 ('boulevard Général-Jacques', 'Boulevard Général-Jacques, Ixelles, Belgique'),
 ('Flandre', 'Flandre, Belgique'),
 ('Orne', 'Orne, Normandie, France'),
 ('Arles', "Arles, Provence-Alpes-Côte d'Azur, France"),
 ('Prudhomat', 'Prudhomat, Occitanie, France'),
 ('place Saint-Jean Lyon 9E Brocante Organisée par la',
  'Place Saint-Jean, Lyon 9e, France'),
 ('Palestine', 'Palestine, Moyen-Orient'),
 ('Narathiwat', 'Narathiwat, Narathiwat, Thaïlande'),
 ('le Perche', 'Le Perche, Normandie, France'),
 ('rue Sainte- Catherine', 'rue Sainte-Catherine, Bordeaux, France'),
 ('Gurs', 'Gurs, Pyrénées-Atlantiques, France'),
 ('FRA', 'France'),
 ('Rennaise', 'Rennes, Ille-et-Vilaine, France'),
 ('Val-de-Marne', 'Val-de-Marne, Île-de-France, France'),
 ('chapelle Notre-Dame du Vincin',
  'chapelle Notre-Dame du Vincin, Arradon, France'),
 ('Israël', 'Israël'),
 ('Miami', 'Miami, Floride, États-Unis'),
 ('Condé-en-Brie', 'Condé-en-Brie, Aisne, France'),

In [132]:
a_ajouter = [
    # Entités physiques / historiques
    {"nom": ('mont Vinson', 'Mont Vinson, Antarctique'),                               "lat": -78.5254, "lon": -85.6173, "pays": "Antarctique",          "code_pays": "AQ", "nom_complet": "Massif Vinson, Antarctique"},
    {"nom": ('plateau du Golan', 'plateau du Golan, Golan, Syrie/Israël'),             "lat": 33.039,   "lon": 35.733,   "pays": "Israël",               "code_pays": "IL", "nom_complet": "Plateau du Golan"},
    {"nom": ("mer d'Aden", "Mer d'Aden, null, null"),                                  "lat": 12.364,   "lon": 47.0,     "pays": "",                     "code_pays": "",   "nom_complet": "Golfe d'Aden"},
    {"nom": ('Océan de la Tranquillité', 'Mer de la Tranquillité, Lune'),              "lat": 8.5,      "lon": 31.4,     "pays": "Lune",                 "code_pays": "",   "nom_complet": "Mer de la Tranquillité, Lune"},
    {"nom": ("REVOLTES DE L'ÎLE DU DIABLE", 'Île du Diable, Île du Diable, Guyane française'), "lat": 5.288,    "lon": -52.587,  "pays": "France",               "code_pays": "FR", "nom_complet": "Île du Diable, Guyane française"},
    {"nom": ('Indochine française', 'Indochine française, Asie du Sud-Est, France (ancienne colonie)'),          "lat": 16.0,     "lon": 106.0,    "pays": "Asie du Sud-Est",      "code_pays": "",   "nom_complet": "Indochine française"},
    {"nom": ('Tchéco-slovaquie', 'Tchécoslovaquie, null, Tchécoslovaquie'),            "lat": 49.803,   "lon": 15.475,   "pays": "Europe centrale",      "code_pays": "CS", "nom_complet": "Tchécoslovaquie"},
    {"nom": ('Territoires palestiniens', 'Territoires palestiniens, null, Palestine'), "lat": 31.952,   "lon": 35.233,   "pays": "Palestine",            "code_pays": "PS", "nom_complet": "Territoires palestiniens"},
    {"nom": ('mer de Tasmanie', 'mer de Tasmanie, Océan Pacifique Sud'),               "lat": -42.0,    "lon": 161.0,    "pays": "",                     "code_pays": "",   "nom_complet": "Mer de Tasmanie"},
    {"nom": ('îles Senkaku', 'îles Senkaku, îles Senkaku, Mer de Chine orientale'),    "lat": 25.754,   "lon": 123.473,  "pays": "Mer de Chine orientale","code_pays": "JP","nom_complet": "Îles Senkaku"},
    # Centroïdes de zones macrorégionales
    {"nom": ('émirats du Golfe', 'Émirats du Golfe, Péninsule arabique, Moyen-Orient'), "lat": 26.0,     "lon": 51.0,     "pays": "Moyen-Orient",         "code_pays": "",   "nom_complet": "Golfe Persique (centroïde)"},
    {"nom": ('Amérique Latine', 'Amérique Latine, null, null'),                         "lat": -15.0,    "lon": -60.0,    "pays": "Amérique Latine",      "code_pays": "",   "nom_complet": "Amérique Latine (centroïde)"},
    {"nom": ('Afrique subsaharienne', 'Afrique subsaharienne, Afrique subsaharienne, Afrique'),        "lat": 5.0,      "lon": 20.0,     "pays": "Afrique",              "code_pays": "",   "nom_complet": "Afrique subsaharienne (centroïde)"},
    {"nom": ("l'Afrique noire", 'Afrique subsaharienne, Afrique'),                      "lat": 5.0,      "lon": 20.0,     "pays": "Afrique",              "code_pays": "",   "nom_complet": "Afrique subsaharienne (centroïde)"},
    {"nom": ('Afrique noire', 'Afrique subsaharienne, null, Afrique'),                  "lat": 5.0,      "lon": 20.0,     "pays": "Afrique",              "code_pays": "",   "nom_complet": "Afrique subsaharienne (centroïde)"},
    {"nom": ('Extrême-Orient', "Extrême-Orient, Asie de l'Est, Asie"),                  "lat": 35.0,     "lon": 115.0,    "pays": "Asie",                 "code_pays": "",   "nom_complet": "Extrême-Orient (centroïde)"},
    {"nom": ('Sahel - de 2 500 hectares', "Sahel, Afrique de l'Ouest, Afrique"),        "lat": 15.0,     "lon": 10.0,     "pays": "Afrique",              "code_pays": "",   "nom_complet": "Sahel (centroïde)"},
    {"nom": ('Corées', 'Corée, Asie'),                                                  "lat": 37.5,     "lon": 127.5,    "pays": "Asie",                 "code_pays": "",   "nom_complet": "Péninsule coréenne (centroïde)"},
]


resultats.extend(a_ajouter)
pd.DataFrame(resultats).to_csv("geocodes.csv", index=False)
pd.DataFrame(resultats).to_parquet("geocodes.parquet", index=False)
print(f"Total : {len(resultats)} lieux géocodés")

Total : 3969 lieux géocodés

In [130]:
non_trouves

[('mont Vinson', 'Mont Vinson, Antarctique'),
 ('Tchéco-slovaquie', 'Tchécoslovaquie, null, Tchécoslovaquie'),
 ('émirats du Golfe', 'Émirats du Golfe, Péninsule arabique, Moyen-Orient'),
 ('Territoires palestiniens', 'Territoires palestiniens, null, Palestine'),
 ('rue Basse-Porte', 'rue Basse-Porte, null, null'),
 ('plateau du Golan', 'plateau du Golan, Golan, Syrie/Israël'),
 ("mer d'Aden", "Mer d'Aden, null, null"),
 ('Océan de la Tranquillité', 'Mer de la Tranquillité, Lune'),
 ("REVOLTES DE L'ÎLE DU DIABLE",
  'Île du Diable, Île du Diable, Guyane française'),
 ('Indochine française',
  'Indochine française, Asie du Sud-Est, France (ancienne colonie)'),
 ('Amérique Latine', 'Amérique Latine, null, null'),
 ('rue Laurier', 'rue Laurier, null, null'),
 ('Extrême-Orient', "Extrême-Orient, Asie de l'Est, Asie"),
 ('Afrique subsaharienne',
  'Afrique subsaharienne, Afrique subsaharienne, Afrique'),
 ('îles Senkaku', 'îles Senkaku, îles Senkaku, Mer de Chine orientale'),
 ('Corées', 'Corée, Asie'),
 ('mer de Tasmanie', 'mer de Tasmanie, Océan Pacifique Sud'),
 ('Sahel - de 2 500 hectares', "Sahel, Afrique de l'Ouest, Afrique"),
 ('rue Rodo', 'Rue Rodo, null, null'),
 ('avenue Joffre', 'Avenue Joffre, null, null'),
 ('autoroute E40', 'Autoroute E40, Europe'),
 ("l'Afrique noire", 'Afrique subsaharienne, Afrique'),
 ('Afrique noire', 'Afrique subsaharienne, null, Afrique')]

# Stats

In [136]:
import polars as pl

In [158]:
df = pl.scan_parquet("corpus/corpus_complet.parquet").select(pl.col(["id", "entities_places", "pays", "journaux", "dates"])).collect()

In [143]:
df_geocode = pl.scan_parquet('corpus/geocodes.parquet').collect()

In [144]:
df_geocode

shape: (3_912, 7)
┌──────────────┬────────────┬─────────────┬──────────────┬───────────┬──────────────┬──────────────┐
│ nom          ┆ lat        ┆ lon         ┆ pays         ┆ code_pays ┆ nom_complet  ┆ source       │
│ ---          ┆ ---        ┆ ---         ┆ ---          ┆ ---       ┆ ---          ┆ ---          │
│ list[str]    ┆ f64        ┆ f64         ┆ str          ┆ str       ┆ str          ┆ str          │
╞══════════════╪════════════╪═════════════╪══════════════╪═══════════╪══════════════╪══════════════╡
│ ["Saint-Étie ┆ 49.377173  ┆ 1.1095372   ┆ France       ┆ FR        ┆ Saint-Étienn ┆ null         │
│ nne-du-Rouvr ┆            ┆             ┆              ┆           ┆ e-du-Rouvray ┆              │
│ ay", "…      ┆            ┆             ┆              ┆           ┆ , Rue …      ┆              │
│ ["Abou       ┆ 34.450552  ┆ 40.917064   ┆ Syrie        ┆ SY        ┆ Al-Bukamal,  ┆ null         │
│ Kémal", "Abu ┆            ┆             ┆              ┆           ┆ Sous-distric ┆              │
│ Kamal, Dei…  ┆            ┆             ┆              ┆           ┆ t d'Al…      ┆              │
│ ["Perros-Gui ┆ 48.805811  ┆ -3.474567   ┆ France       ┆ FR        ┆ Centre       ┆ null         │
│ rec", "Perro ┆            ┆             ┆              ┆           ┆ d'incendie   ┆              │
│ s-Guir…      ┆            ┆             ┆              ┆           ┆ et de        ┆              │
│              ┆            ┆             ┆              ┆           ┆ secour…      ┆              │
│ ["Saint-Gaud ┆ 43.107768  ┆ 0.7247218   ┆ France       ┆ FR        ┆ Saint-Gauden ┆ null         │
│ ens", "Saint ┆            ┆             ┆              ┆           ┆ s, Haute-Gar ┆              │
│ -Gaude…      ┆            ┆             ┆              ┆           ┆ onne, …      ┆              │
│ ["Carmel",   ┆ 36.555266  ┆ -121.923278 ┆ États-Unis   ┆ US        ┆ Carmel-by-th ┆ null         │
│ "Carmel,     ┆            ┆             ┆ d'Amérique   ┆           ┆ e-Sea,       ┆              │
│ Californie…  ┆            ┆             ┆              ┆           ┆ Monterey Co… ┆              │
│ …            ┆ …          ┆ …           ┆ …            ┆ …         ┆ …            ┆ …            │
│ ["avenue Xav ┆ 47.179301  ┆ -1.623369   ┆ France       ┆ FR        ┆ Bouguenais,  ┆ nominatim_st │
│ ier-Rineau", ┆            ┆             ┆              ┆           ┆ Nantes,      ┆ ruct         │
│ "Aven…       ┆            ┆             ┆              ┆           ┆ Loire-Atla…  ┆              │
│ ["rue des    ┆ 48.85889   ┆ 2.320041    ┆ France       ┆ FR        ┆ Paris, Île-d ┆ nominatim_st │
│ Vignolles",  ┆            ┆             ┆              ┆           ┆ e-France,    ┆ ruct         │
│ "Rue des…    ┆            ┆             ┆              ┆           ┆ France m…    ┆              │
│ ["Alpes      ┆ -16.844045 ┆ -151.369856 ┆ France       ┆ FR        ┆ Tirao, Opoa, ┆ nominatim_st │
│ françaises", ┆            ┆             ┆              ┆           ┆ Taputapuatea ┆ ruct         │
│ "Alpes fr…   ┆            ┆             ┆              ┆           ┆ , Île…       ┆              │
│ ["Cité des   ┆ 45.404617  ┆ 12.310523   ┆ Italie       ┆ IT        ┆ Venise,      ┆ nominatim_st │
│ Doges",      ┆            ┆             ┆              ┆           ┆ Vénétie,     ┆ ruct         │
│ "Cité des D… ┆            ┆             ┆              ┆           ┆ 30121-30176, ┆              │
│              ┆            ┆             ┆              ┆           ┆ …            ┆              │
│ ["rue        ┆ 43.837425  ┆ 4.3600687   ┆ France       ┆ FR        ┆ Nîmes, Gard, ┆ nominatim_st │
│ Ermengaud",  ┆            ┆             ┆              ┆           ┆ Occitanie,   ┆ ruct         │
│ "Rue         ┆            ┆             ┆              ┆           ┆ France…      ┆              │
│ Ermenga…     ┆            ┆             ┆              ┆           ┆              ┆              │
└──────────────┴────────────┴─────────────┴──────────────┴───────────┴──────────────┴──────────────┘

In [145]:
mapping = (
    df_geocode
    .with_columns(
        pl.col("nom").list.get(0).alias("entite")
    )
    .select(["entite", "pays", "code_pays"])
)

In [159]:
df_exploded = (
    df
    .with_row_index("__row_idx")          # garde la trace de la ligne d'origine
    .explode("entities_places")                    # adapte "entites" au vrai nom de la colonne
)

In [160]:
df_joined = df_exploded.join(mapping, left_on="entities_places", right_on="entite", how="left")

In [161]:
df_joined

shape: (2_168_293, 8)
┌───────────┬────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┐
│ __row_idx ┆ id         ┆ entities_p ┆ pays       ┆ journaux  ┆ dates     ┆ pays_righ ┆ code_pays │
│ ---       ┆ ---        ┆ laces      ┆ ---        ┆ ---       ┆ ---       ┆ t         ┆ ---       │
│ u32       ┆ str        ┆ ---        ┆ list[str]  ┆ list[str] ┆ list[str] ┆ ---       ┆ str       │
│           ┆            ┆ str        ┆            ┆           ┆           ┆ str       ┆           │
╞═══════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0         ┆ 583dcb9167 ┆ collège    ┆ ["France"] ┆ ["Le      ┆ ["4 mars  ┆ null      ┆ null      │
│           ┆ 3c661e179b ┆ Malfroy    ┆            ┆ Progrès - ┆ 2005"]    ┆           ┆           │
│           ┆ 5235c7998d ┆            ┆            ┆ Lyon"]    ┆           ┆           ┆           │
│           ┆ …          ┆            ┆            ┆           ┆           ┆           ┆           │
│ 0         ┆ 583dcb9167 ┆ collège    ┆ ["France"] ┆ ["Le      ┆ ["4 mars  ┆ null      ┆ null      │
│           ┆ 3c661e179b ┆ Malfroy    ┆            ┆ Progrès - ┆ 2005"]    ┆           ┆           │
│           ┆ 5235c7998d ┆            ┆            ┆ Lyon"]    ┆           ┆           ┆           │
│           ┆ …          ┆            ┆            ┆           ┆           ┆           ┆           │
│ 0         ┆ 583dcb9167 ┆ 87 E       ┆ ["France"] ┆ ["Le      ┆ ["4 mars  ┆ null      ┆ null      │
│           ┆ 3c661e179b ┆            ┆            ┆ Progrès - ┆ 2005"]    ┆           ┆           │
│           ┆ 5235c7998d ┆            ┆            ┆ Lyon"]    ┆           ┆           ┆           │
│           ┆ …          ┆            ┆            ┆           ┆           ┆           ┆           │
│ 0         ┆ 583dcb9167 ┆ l'Asie     ┆ ["France"] ┆ ["Le      ┆ ["4 mars  ┆           ┆           │
│           ┆ 3c661e179b ┆            ┆            ┆ Progrès - ┆ 2005"]    ┆           ┆           │
│           ┆ 5235c7998d ┆            ┆            ┆ Lyon"]    ┆           ┆           ┆           │
│           ┆ …          ┆            ┆            ┆           ┆           ┆           ┆           │
│ 1         ┆ a92817744d ┆ Rome       ┆ ["Belgique ┆ ["Le      ┆ ["20      ┆ Italie    ┆ IT        │
│           ┆ 9108efb889 ┆            ┆ "]         ┆ Soir"]    ┆ janvier   ┆           ┆           │
│           ┆ a74e4a0104 ┆            ┆            ┆           ┆ 2010"]    ┆           ┆           │
│           ┆ …          ┆            ┆            ┆           ┆           ┆           ┆           │
│ …         ┆ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         │
│ 172899    ┆ e785d06fbf ┆ Saint-Pete ┆ ["Canada"] ┆ ["Le Nouv ┆ ["27      ┆ null      ┆ null      │
│           ┆ cbbb184496 ┆ rsbourg    ┆            ┆ elliste   ┆ juillet   ┆           ┆           │
│           ┆ 147bbe987c ┆            ┆            ┆ (Trois-Ri ┆ 2002",    ┆           ┆           │
│           ┆ …          ┆            ┆            ┆ vièr…     ┆ "27       ┆           ┆           │
│           ┆            ┆            ┆            ┆           ┆ juille…   ┆           ┆           │
│ 172899    ┆ e785d06fbf ┆ Russie     ┆ ["Canada"] ┆ ["Le Nouv ┆ ["27      ┆ Russie    ┆ RU        │
│           ┆ cbbb184496 ┆            ┆            ┆ elliste   ┆ juillet   ┆           ┆           │
│           ┆ 147bbe987c ┆            ┆            ┆ (Trois-Ri ┆ 2002",    ┆           ┆           │
│           ┆ …          ┆            ┆            ┆ vièr…     ┆ "27       ┆           ┆           │
│           ┆            ┆            ┆            ┆           ┆ juille…   ┆           ┆           │
│ 172899    ┆ e785d06fbf ┆ Europe     ┆ ["Canada"] ┆ ["Le Nouv ┆ ["27      ┆           ┆           │
│           ┆ cbbb184496 ┆            ┆            ┆ elliste   ┆ juillet   ┆           ┆           │
│           ┆ 147bbe987c ┆            ┆            ┆ (Trois-Ri ┆ 2002",    ┆           ┆           │
│           ┆ …          ┆            ┆            ┆ vièr…     ┆ "27       ┆           ┆           │
│           ┆            ┆            ┆            ┆           ┆ juille…   ┆           ┆           │
│ 172899    ┆ e785d06fbf ┆ Illustrati ┆ ["Canada"] ┆ ["Le Nouv ┆ ["27      ┆ null      ┆ null      │
│           ┆ cbbb184496 ┆ on(s       ┆            ┆ elliste   ┆ juillet   ┆           ┆           │
│           ┆ 147bbe987c ┆            ┆            ┆ (Trois-Ri ┆ 2002",    ┆           ┆           │
│           ┆ …          ┆            ┆            ┆ vièr…     ┆ "27       ┆           ┆           │
│           ┆            ┆            ┆            ┆           ┆ juille…   ┆           ┆           │
│ 172899    ┆ e785d06fbf ┆ Toronto    ┆ ["Canada"] ┆ ["Le Nouv ┆ ["27      ┆ Canada    ┆ CA        │
│           ┆ cbbb184496 ┆            ┆            ┆ elliste   ┆ juillet   ┆           ┆           │
│           ┆ 147bbe987c ┆            ┆            ┆ (Trois-Ri ┆ 2002",    ┆           ┆           │
│           ┆ …          ┆            ┆            ┆ vièr…     ┆ "27       ┆           ┆           │
│           ┆            ┆            ┆            ┆           ┆ juille…   ┆           ┆           │
└───────────┴────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┘

In [164]:
df_result = (
    df_joined
    .with_columns(
        pl.struct(["pays_right", "code_pays"]).alias("pays_tuple")
    )
    .group_by("__row_idx")
    .agg([
        pl.all().exclude(["__row_idx", "pays_right", "code_pays", "pays_tuple", "entities_places"]).first(),
        pl.col("pays_tuple").alias("pays_entites")   # liste de structs {pays, code_pays}
    ])
    .sort("__row_idx")
    .drop("__row_idx")
)

In [165]:
df_result

shape: (172_900, 5)
┌────────────────────┬──────────────┬────────────────────┬────────────────────┬────────────────────┐
│ id                 ┆ pays         ┆ journaux           ┆ dates              ┆ pays_entites       │
│ ---                ┆ ---          ┆ ---                ┆ ---                ┆ ---                │
│ str                ┆ list[str]    ┆ list[str]          ┆ list[str]          ┆ list[struct[2]]    │
╞════════════════════╪══════════════╪════════════════════╪════════════════════╪════════════════════╡
│ 583dcb91673c661e17 ┆ ["France"]   ┆ ["Le Progrès -     ┆ ["4 mars 2005"]    ┆ [{null,null},      │
│ 9b5235c7998d…      ┆              ┆ Lyon"]             ┆                    ┆ {null,null}, … {…  │
│ a92817744d9108efb8 ┆ ["Belgique"] ┆ ["Le Soir"]        ┆ ["20 janvier       ┆ [{"Italie","IT"},  │
│ 89a74e4a0104…      ┆              ┆                    ┆ 2010"]             ┆ {"Belgique",…      │
│ e38611f965034aa72c ┆ ["France"]   ┆ ["Nord Éclair",    ┆ ["2 février 2021", ┆ [{null,null},      │
│ 0223810decbf…      ┆              ┆ "La Voix du No…    ┆ "2 février …       ┆ {"France","FR"}]   │
│ 6877eee607c788cfb4 ┆ ["France"]   ┆ ["La Dépêche du    ┆ ["4 avril 2018",   ┆ [{null,null},      │
│ 7fdf16a7992f…      ┆              ┆ Midi", "Libéra…    ┆ "3 avril 2018…     ┆ {null,null}]       │
│ dee3e67e182ba3209f ┆ ["France"]   ┆ ["La Tribune       ┆ ["29 décembre      ┆ [{null,null},      │
│ 24dfd10e3697…      ┆              ┆ dimanche (France)… ┆ 2024", "1 décemb…  ┆ {null,null}, {nu…  │
│ …                  ┆ …            ┆ …                  ┆ …                  ┆ …                  │
│ 9400e22e5b6658c46e ┆ ["Suisse",   ┆ ["24 Heures", "Le  ┆ ["28 juillet       ┆ [{"Suisse","CH"},  │
│ 189c9e7b47a5…      ┆ "Canada"]    ┆ Journal de M…      ┆ 2007", "4 juillet… ┆ {null,null},…      │
│ 8a785b90e423dd1cee ┆ ["Belgique"] ┆ ["Le Soir"]        ┆ ["5 novembre       ┆ [{null,null},      │
│ dc8c80b928d8…      ┆              ┆                    ┆ 2001"]             ┆ {"Belgique","BE"…  │
│ d8186f197fd7e7ac9c ┆ ["France"]   ┆ ["AFP - Infos      ┆ ["1 juin 2003"]    ┆ [{null,null},      │
│ 76ad27d5be55…      ┆              ┆ Françaises"]       ┆                    ┆ {"Russie","RU"},…  │
│ 205f2feb40b71498df ┆ ["Belgique", ┆ ["La Dernière      ┆ ["18 septembre     ┆ [{null,null}]      │
│ c401395aa2df…      ┆ "Suisse"]    ┆ Heure - Les Spor…  ┆ 2021", "30 sept…   ┆                    │
│ e785d06fbfcbbb1844 ┆ ["Canada"]   ┆ ["Le Nouvelliste   ┆ ["27 juillet       ┆ [{"Canada","CA"},  │
│ 96147bbe987c…      ┆              ┆ (Trois-Rivièr…     ┆ 2002", "27 juille… ┆ {null,null},…      │
└────────────────────┴──────────────┴────────────────────┴────────────────────┴────────────────────┘

In [167]:
def clean_pays_list(lst):
    if lst is None:
        return []
    result = []
    for d in lst:
        pays = d["pays_right"] if d["pays_right"] else None       # "" → None
        code = d["code_pays"] if d["code_pays"] else None
        # Cas mixte : un seul champ vide → on garde mais normalisé
        # Cas tout vide → on drop
        if pays is None and code is None:
            continue
        result.append({"pays": pays, "code_pays": code})
    return result

df_result = df_result.with_columns(
    pl.col("pays_entites")
    .map_elements(clean_pays_list, return_dtype=pl.List(pl.Struct({"pays": pl.String, "code_pays": pl.String})))
)

In [168]:
df_result

shape: (172_900, 5)
┌────────────────────┬──────────────┬────────────────────┬────────────────────┬────────────────────┐
│ id                 ┆ pays         ┆ journaux           ┆ dates              ┆ pays_entites       │
│ ---                ┆ ---          ┆ ---                ┆ ---                ┆ ---                │
│ str                ┆ list[str]    ┆ list[str]          ┆ list[str]          ┆ list[struct[2]]    │
╞════════════════════╪══════════════╪════════════════════╪════════════════════╪════════════════════╡
│ 583dcb91673c661e17 ┆ ["France"]   ┆ ["Le Progrès -     ┆ ["4 mars 2005"]    ┆ []                 │
│ 9b5235c7998d…      ┆              ┆ Lyon"]             ┆                    ┆                    │
│ a92817744d9108efb8 ┆ ["Belgique"] ┆ ["Le Soir"]        ┆ ["20 janvier       ┆ [{"Italie","IT"},  │
│ 89a74e4a0104…      ┆              ┆                    ┆ 2010"]             ┆ {"Belgique",…      │
│ e38611f965034aa72c ┆ ["France"]   ┆ ["Nord Éclair",    ┆ ["2 février 2021", ┆ [{"France","FR"}]  │
│ 0223810decbf…      ┆              ┆ "La Voix du No…    ┆ "2 février …       ┆                    │
│ 6877eee607c788cfb4 ┆ ["France"]   ┆ ["La Dépêche du    ┆ ["4 avril 2018",   ┆ []                 │
│ 7fdf16a7992f…      ┆              ┆ Midi", "Libéra…    ┆ "3 avril 2018…     ┆                    │
│ dee3e67e182ba3209f ┆ ["France"]   ┆ ["La Tribune       ┆ ["29 décembre      ┆ []                 │
│ 24dfd10e3697…      ┆              ┆ dimanche (France)… ┆ 2024", "1 décemb…  ┆                    │
│ …                  ┆ …            ┆ …                  ┆ …                  ┆ …                  │
│ 9400e22e5b6658c46e ┆ ["Suisse",   ┆ ["24 Heures", "Le  ┆ ["28 juillet       ┆ [{"Suisse","CH"},  │
│ 189c9e7b47a5…      ┆ "Canada"]    ┆ Journal de M…      ┆ 2007", "4 juillet… ┆ {"Suisse","C…      │
│ 8a785b90e423dd1cee ┆ ["Belgique"] ┆ ["Le Soir"]        ┆ ["5 novembre       ┆ [{"Belgique","BE"} │
│ dc8c80b928d8…      ┆              ┆                    ┆ 2001"]             ┆ , {"Belgique…      │
│ d8186f197fd7e7ac9c ┆ ["France"]   ┆ ["AFP - Infos      ┆ ["1 juin 2003"]    ┆ [{"Russie","RU"},  │
│ 76ad27d5be55…      ┆              ┆ Françaises"]       ┆                    ┆ {"Allemagne"…      │
│ 205f2feb40b71498df ┆ ["Belgique", ┆ ["La Dernière      ┆ ["18 septembre     ┆ []                 │
│ c401395aa2df…      ┆ "Suisse"]    ┆ Heure - Les Spor…  ┆ 2021", "30 sept…   ┆                    │
│ e785d06fbfcbbb1844 ┆ ["Canada"]   ┆ ["Le Nouvelliste   ┆ ["27 juillet       ┆ [{"Canada","CA"},  │
│ 96147bbe987c…      ┆              ┆ (Trois-Rivièr…     ┆ 2002", "27 juille… ┆ {"Guatemala"…      │
└────────────────────┴──────────────┴────────────────────┴────────────────────┴────────────────────┘

In [183]:
df_result.write_parquet("corpus/pays_cites.parquet")

In [184]:
# ── Mappings
REMPLACE_INCONNU = {'bimensuel', 'Presse', 'trimestriel'}
REMPLACE_AUTRE   = {
    'Burkina', 'Maroc', 'Côte', 'Liban', 'Tunisie', 'Sénégal',
    'Tchad', 'Burundi', 'Cameroun', 'Royaume-UniGrand', 'Turquie',
    'Guinée', 'Mauritanie', 'Togo', 'Mali'
}

# ── Explode : une ligne par (article × pays)
df_exp = (
    df_result
    .explode("pays")
    .with_columns(
        pl.when(pl.col("pays").is_null() | pl.col("pays").is_in(list(REMPLACE_INCONNU)))
          .then(pl.lit("Inconnu"))
          .when(pl.col("pays").is_in(list(REMPLACE_AUTRE)))
          .then(pl.lit("Autre"))
          .otherwise(pl.col("pays"))
          .alias("pays_norm")
    )
)

In [185]:
df_exp

shape: (182_285, 6)
┌──────────────────┬──────────┬──────────────────┬──────────────────┬──────────────────┬───────────┐
│ id               ┆ pays     ┆ journaux         ┆ dates            ┆ pays_entites     ┆ pays_norm │
│ ---              ┆ ---      ┆ ---              ┆ ---              ┆ ---              ┆ ---       │
│ str              ┆ str      ┆ list[str]        ┆ list[str]        ┆ list[struct[2]]  ┆ str       │
╞══════════════════╪══════════╪══════════════════╪══════════════════╪══════════════════╪═══════════╡
│ 583dcb91673c661e ┆ France   ┆ ["Le Progrès -   ┆ ["4 mars 2005"]  ┆ []               ┆ France    │
│ 179b5235c7998d…  ┆          ┆ Lyon"]           ┆                  ┆                  ┆           │
│ a92817744d9108ef ┆ Belgique ┆ ["Le Soir"]      ┆ ["20 janvier     ┆ [{"Italie","IT"} ┆ Belgique  │
│ b889a74e4a0104…  ┆          ┆                  ┆ 2010"]           ┆ , {"Belgique",…  ┆           │
│ e38611f965034aa7 ┆ France   ┆ ["Nord Éclair",  ┆ ["2 février      ┆ [{"France","FR"} ┆ France    │
│ 2c0223810decbf…  ┆          ┆ "La Voix du No…  ┆ 2021", "2        ┆ ]                ┆           │
│                  ┆          ┆                  ┆ février …        ┆                  ┆           │
│ 6877eee607c788cf ┆ France   ┆ ["La Dépêche du  ┆ ["4 avril 2018", ┆ []               ┆ France    │
│ b47fdf16a7992f…  ┆          ┆ Midi", "Libéra…  ┆ "3 avril 2018…   ┆                  ┆           │
│ dee3e67e182ba320 ┆ France   ┆ ["La Tribune     ┆ ["29 décembre    ┆ []               ┆ France    │
│ 9f24dfd10e3697…  ┆          ┆ dimanche         ┆ 2024", "1        ┆                  ┆           │
│                  ┆          ┆ (France)…        ┆ décemb…          ┆                  ┆           │
│ …                ┆ …        ┆ …                ┆ …                ┆ …                ┆ …         │
│ 8a785b90e423dd1c ┆ Belgique ┆ ["Le Soir"]      ┆ ["5 novembre     ┆ [{"Belgique","BE ┆ Belgique  │
│ eedc8c80b928d8…  ┆          ┆                  ┆ 2001"]           ┆ "}, {"Belgique…  ┆           │
│ d8186f197fd7e7ac ┆ France   ┆ ["AFP - Infos    ┆ ["1 juin 2003"]  ┆ [{"Russie","RU"} ┆ France    │
│ 9c76ad27d5be55…  ┆          ┆ Françaises"]     ┆                  ┆ , {"Allemagne"…  ┆           │
│ 205f2feb40b71498 ┆ Belgique ┆ ["La Dernière    ┆ ["18 septembre   ┆ []               ┆ Belgique  │
│ dfc401395aa2df…  ┆          ┆ Heure - Les      ┆ 2021", "30 sept… ┆                  ┆           │
│                  ┆          ┆ Spor…            ┆                  ┆                  ┆           │
│ 205f2feb40b71498 ┆ Suisse   ┆ ["La Dernière    ┆ ["18 septembre   ┆ []               ┆ Suisse    │
│ dfc401395aa2df…  ┆          ┆ Heure - Les      ┆ 2021", "30 sept… ┆                  ┆           │
│                  ┆          ┆ Spor…            ┆                  ┆                  ┆           │
│ e785d06fbfcbbb18 ┆ Canada   ┆ ["Le Nouvelliste ┆ ["27 juillet     ┆ [{"Canada","CA"} ┆ Canada    │
│ 4496147bbe987c…  ┆          ┆ (Trois-Rivièr…   ┆ 2002", "27       ┆ , {"Guatemala"…  ┆           │
│                  ┆          ┆                  ┆ juille…          ┆                  ┆           │
└──────────────────┴──────────┴──────────────────┴──────────────────┴──────────────────┴───────────┘

In [187]:
print(df_exp.select("pays_entites").dtypes)

[List(Struct({'pays': String, 'code_pays': String}))]

In [188]:
result = (
    df_exp
    .explode("pays_entites")                          # une ligne par entité
    .with_columns(
        pl.col("pays_entites").struct.field("pays").alias("pays_entite")  # extrait le nom du pays
    )
    .filter(pl.col("pays_entite").is_not_null())
    .group_by(["pays_norm", "pays_entite"])
    .agg(pl.len().alias("count"))
    .sort(["pays_norm", "count"], descending=[False, True])
)

print(result)

shape: (1_267, 3)
┌───────────┬───────────────────────┬───────┐
│ pays_norm ┆ pays_entite           ┆ count │
│ ---       ┆ ---                   ┆ ---   │
│ str       ┆ str                   ┆ u32   │
╞═══════════╪═══════════════════════╪═══════╡
│ Algérie   ┆ France                ┆ 3158  │
│ Algérie   ┆ Algérie               ┆ 3007  │
│ Algérie   ┆ Italie                ┆ 2594  │
│ Algérie   ┆ Suisse                ┆ 1975  │
│ Algérie   ┆ États-Unis d'Amérique ┆ 1036  │
│ …         ┆ …                     ┆ …     │
│ Suisse    ┆ Kirghizstan           ┆ 1     │
│ Suisse    ┆ Jersey                ┆ 1     │
│ Suisse    ┆ Palaos                ┆ 1     │
│ Suisse    ┆ Cap-Vert              ┆ 1     │
│ Suisse    ┆ Bermudes              ┆ 1     │
└───────────┴───────────────────────┴───────┘

In [192]:
top_n = 10

# Étape 1 : ajouter le pourcentage par pays_norm
result_pct = result.with_columns(
    (pl.col("count") / pl.col("count").sum().over("pays_norm") * 100)
    .round(1)
    .alias("pct")
)

# Étape 2 : top N par pays_norm
top = (
    result_pct
    .sort(["pays_norm", "pct"], descending=[False, True])
    .group_by("pays_norm")
    .agg(pl.all().head(top_n))
    .explode(["pays_entite", "count", "pct"])
)

# Étape 3 : label avec pourcentage
top = top.with_columns(
    pl.col("pct")
    .rank(method="ordinal", descending=True)
    .over("pays_norm")
    .cast(pl.Int32)
    .alias("rang")
).with_columns(
    (pl.col("pays_entite") + " (" + pl.col("pct").cast(pl.Utf8) + "%)")
    .alias("label")
)

# Étape 4 : pivot
pivot = (
    top
    .pivot(index="pays_norm", on="rang", values="label", aggregate_function="first")
    .rename({str(i): f"top_{i}" for i in range(1, top_n + 1)})
)

print(pivot)
pivot.write_csv("top_pays_entites_pct.csv")

shape: (8, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ pays_norm ┆ top_1     ┆ top_2     ┆ top_3     ┆ … ┆ top_7     ┆ top_8     ┆ top_9     ┆ top_10   │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Belgique  ┆ Belgique  ┆ France    ┆ Canada    ┆ … ┆ Allemagne ┆ Espagne   ┆ Pays-Bas  ┆ Russie   │
│           ┆ (34.6%)   ┆ (18.2%)   ┆ (6.1%)    ┆   ┆ (1.8%)    ┆ (1.3%)    ┆ (1.3%)    ┆ (1.3%)   │
│ Inconnu   ┆ France    ┆ Canada    ┆ Algérie   ┆ … ┆ Royaume-U ┆ Italie    ┆ Maroc     ┆ Chine    │
│           ┆ (25.4%)   ┆ (15.5%)   ┆ (8.2%)    ┆   ┆ ni (2.0%) ┆ (1.8%)    ┆ (1.7%)    ┆ (1.7%)   │
│ Chine     ┆ Chine     ┆ France    ┆ Canada    ┆ … ┆ Belgique  ┆ Cameroun  ┆ Italie    ┆ Nigéria  │
│           ┆ (15.0%)   ┆ (9.7%)    ┆ (5.0%)    ┆   ┆ (2.9%)    ┆ (2.5%)    ┆ (2.4%)    ┆ (2.3%)   │
│ Algérie   ┆ France    ┆ Algérie   ┆ Italie    ┆ … ┆ Royaume-U ┆ Maroc     ┆ Chine     ┆ Allemagn │
│           ┆ (15.7%)   ┆ (14.9%)   ┆ (12.9%)   ┆   ┆ ni (2.3%) ┆ (2.2%)    ┆ (2.2%)    ┆ e (2.0%) │
│ Suisse    ┆ Suisse    ┆ France    ┆ Italie    ┆ … ┆ Royaume-U ┆ Chine     ┆ Russie    ┆ Belgique │
│           ┆ (21.3%)   ┆ (15.2%)   ┆ (13.2%)   ┆   ┆ ni (2.6%) ┆ (2.3%)    ┆ (2.1%)    ┆ (2.1%)   │
│ France    ┆ France    ┆ États-Uni ┆ Italie    ┆ … ┆ Chine     ┆ Allemagne ┆ Espagne   ┆ Russie   │
│           ┆ (49.8%)   ┆ s d'Améri ┆ (3.9%)    ┆   ┆ (2.1%)    ┆ (2.0%)    ┆ (1.6%)    ┆ (1.4%)   │
│           ┆           ┆ que       ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ (6.0%)    ┆           ┆   ┆           ┆           ┆           ┆          │
│ Canada    ┆ Canada    ┆ France    ┆ États-Uni ┆ … ┆ Chine     ┆ Mexique   ┆ Allemagne ┆ Russie   │
│           ┆ (51.6%)   ┆ (10.2%)   ┆ s d'Améri ┆   ┆ (1.3%)    ┆ (1.2%)    ┆ (1.1%)    ┆ (0.9%)   │
│           ┆           ┆           ┆ que       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ (8.5%)    ┆   ┆           ┆           ┆           ┆          │
│ Autre     ┆ France    ┆ Liban     ┆ Canada    ┆ … ┆ Angola    ┆ Burundi   ┆ Italie    ┆ Algérie  │
│           ┆ (22.4%)   ┆ (7.6%)    ┆ (5.2%)    ┆   ┆ (3.0%)    ┆ (2.9%)    ┆ (2.5%)    ┆ (2.4%)   │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# Faire la carte

In [1]:
import polars as pl
import json

In [4]:
df = pl.scan_parquet("corpus/corpus_complet.parquet").select(pl.col(["id", "entities_places", "pays", "journaux", "dates"])).collect()

In [2]:
df_geocode = pl.scan_parquet('corpus/geocodes.parquet').collect()

In [5]:
# 1. Préparer df_geocode : extraire l'entité clé (élément 0 de "nom")
geocode_flat = df_geocode.with_columns(
    pl.col("nom").list.get(0).alias("entite")
).select(["entite", "lat", "lon", "pays", "code_pays", "nom_complet"])

# 2. Exploser df sur la colonne d'entités → 1 ligne par entité
df_exploded = df.explode("entities_places")   # adapte au vrai nom de ta colonne

# 3. Jointure avec les géocodes
df_geo = df_exploded.join(
    geocode_flat,
    left_on="entities_places",
    right_on="entite",
    how="left"
)

In [6]:
# Garder seulement les entités géocodées
df_geo_matched = df_geo.filter(pl.col("lat").is_not_null())

In [11]:
df_geo_matched

shape: (1_133_789, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ entities_ ┆ pays      ┆ journaux  ┆ … ┆ lon       ┆ pays_righ ┆ code_pays ┆ nom_comp │
│ ---       ┆ places    ┆ ---       ┆ ---       ┆   ┆ ---       ┆ t         ┆ ---       ┆ let      │
│ str       ┆ ---       ┆ list[str] ┆ list[str] ┆   ┆ f64       ┆ ---       ┆ str       ┆ ---      │
│           ┆ str       ┆           ┆           ┆   ┆           ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 583dcb916 ┆ l'Asie    ┆ ["France" ┆ ["Le      ┆ … ┆ 114.60938 ┆           ┆           ┆ Eastern  │
│ 73c661e17 ┆           ┆ ]         ┆ Progrès - ┆   ┆           ┆           ┆           ┆ Asia     │
│ 9b5235c79 ┆           ┆           ┆ Lyon"]    ┆   ┆           ┆           ┆           ┆          │
│ 98d…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ a92817744 ┆ Rome      ┆ ["Belgiqu ┆ ["Le      ┆ … ┆ 12.482932 ┆ Italie    ┆ IT        ┆ Rome,    │
│ d9108efb8 ┆           ┆ e"]       ┆ Soir"]    ┆   ┆           ┆           ┆           ┆ Roma Cap │
│ 89a74e4a0 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ itale,   │
│ 104…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Latium,  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ I…       │
│ a92817744 ┆ Celles    ┆ ["Belgiqu ┆ ["Le      ┆ … ┆ 3.4571664 ┆ Belgique  ┆ BE        ┆ Celles,  │
│ d9108efb8 ┆           ┆ e"]       ┆ Soir"]    ┆   ┆           ┆           ┆           ┆ Tournai- │
│ 89a74e4a0 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Mouscron │
│ 104…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ , Hain…  │
│ a92817744 ┆ Chicago   ┆ ["Belgiqu ┆ ["Le      ┆ … ┆ -87.63569 ┆ États-Uni ┆ US        ┆ Chicago, │
│ d9108efb8 ┆           ┆ e"]       ┆ Soir"]    ┆   ┆ 4         ┆ s d'Améri ┆           ┆ 300,     │
│ 89a74e4a0 ┆           ┆           ┆           ┆   ┆           ┆ que       ┆           ┆ West     │
│ 104…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Chicago  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Ave…     │
│ a92817744 ┆ USA       ┆ ["Belgiqu ┆ ["Le      ┆ … ┆ -57.65625 ┆           ┆           ┆ South    │
│ d9108efb8 ┆           ┆ e"]       ┆ Soir"]    ┆   ┆           ┆           ┆           ┆ America  │
│ 89a74e4a0 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 104…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ e785d06fb ┆ Europe    ┆ ["Canada" ┆ ["Le Nouv ┆ … ┆ 10.0      ┆           ┆           ┆ Europe   │
│ fcbbb1844 ┆           ┆ ]         ┆ elliste   ┆   ┆           ┆           ┆           ┆          │
│ 96147bbe9 ┆           ┆           ┆ (Trois-Ri ┆   ┆           ┆           ┆           ┆          │
│ 87c…      ┆           ┆           ┆ vièr…     ┆   ┆           ┆           ┆           ┆          │
│ e785d06fb ┆ Madagasca ┆ ["Canada" ┆ ["Le Nouv ┆ … ┆ 13.58768  ┆ Cameroun  ┆ CM        ┆ MADAGASC │
│ fcbbb1844 ┆ r         ┆ ]         ┆ elliste   ┆   ┆           ┆           ┆           ┆ AR       │
│ 96147bbe9 ┆           ┆           ┆ (Trois-Ri ┆   ┆           ┆           ┆           ┆ (École   │
│ 87c…      ┆           ┆           ┆ vièr…     ┆   ┆           ┆           ┆           ┆ 1), Rue  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ de l…    │
│ e785d06fb ┆ Russie    ┆ ["Canada" ┆ ["Le Nouv ┆ … ┆ 100.0     ┆ Russie    ┆ RU        ┆ Russian  │
│ fcbbb1844 ┆           ┆ ]         ┆ elliste   ┆   ┆           ┆           ┆           ┆ Federati │
│ 96147bbe9 ┆           ┆           ┆ (Trois-Ri ┆   ┆           ┆           ┆           ┆ on       │
│ 87c…      ┆           ┆           ┆ vièr…     ┆   ┆           ┆           ┆           ┆          │
│ e785d06fb ┆ Europe    ┆ ["Canada" ┆ ["Le Nouv ┆ … ┆ 10.0      ┆           ┆           ┆ Europe   │
│ fcbbb1844 ┆           ┆ ]         ┆ elliste   ┆   ┆           ┆           ┆           ┆          │
│ 96147bbe9 ┆           ┆           ┆ (Trois-Ri ┆   ┆           ┆           ┆           ┆          │
│ 87c…      ┆           ┆           ┆ vièr…     ┆   ┆           ┆           ┆           ┆          │
│ e785d06fb ┆ Toronto   ┆ ["Canada" ┆ ["Le Nouv ┆ … ┆ -79.62880 ┆ Canada    ┆ CA        ┆ Aéroport │
│ fcbbb1844 ┆           ┆ ]         ┆ elliste   ┆   ┆ 5         ┆           ┆           ┆ internat │
│ 96147bbe9 ┆           ┆           ┆ (Trois-Ri ┆   ┆           ┆           ┆           ┆ ional    │
│ 87c…      ┆           ┆           ┆ vièr…     ┆   ┆           ┆           ┆           ┆ Pearson… │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:


# Exploser les listes dates/journaux si besoin
df_exploded = df_geo_matched.explode("dates").explode("journaux")

# Extraire l'année depuis la date (adapter selon ton format)
df_exploded = df_exploded.with_columns(
    pl.col("dates").str.extract(r"(\d{4})", 1).cast(pl.Int32).alias("annee")
)

df_agg = df_exploded.group_by([
    "lat", "lon", "entities_places", "pays_right", "code_pays", "nom_complet"
]).agg([
    pl.col("journaux").unique().alias("journaux"),
    pl.col("pays").unique().alias("pays_source"),
    pl.col("annee").unique().sort().alias("annees"),
    pl.col("dates").unique().alias("dates"),
    pl.col("pays").mode().first().alias("pays_dominant"),

    # ✅ Nombre d'articles uniques (pas de mentions)
    pl.col("id").n_unique().alias("nb_articles"),

    # ❌ À éviter : pl.len() compte les lignes, pas les articles
])

print(f"Lignes avant : {len(df)} → après : {len(df_agg)}")

Lignes avant : 172900 → après : 3905

In [12]:
df_agg

shape: (3_905, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ lat       ┆ lon       ┆ entities_ ┆ pays_righ ┆ … ┆ pays_sour ┆ annees    ┆ dates     ┆ nb_menti │
│ ---       ┆ ---       ┆ places    ┆ t         ┆   ┆ ce        ┆ ---       ┆ ---       ┆ ons      │
│ f64       ┆ f64       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ list[i32] ┆ list[str] ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆ list[list ┆           ┆           ┆ u32      │
│           ┆           ┆           ┆           ┆   ┆ [str]]    ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 43.447925 ┆ 3.422525  ┆ Pézenas   ┆ France    ┆ … ┆ [["France ┆ [2002,    ┆ ["28 juin ┆ 262      │
│           ┆           ┆           ┆           ┆   ┆ "], ["Bel ┆ 2004, …   ┆ 2011",    ┆          │
│           ┆           ┆           ┆           ┆   ┆ gique",   ┆ 2024]     ┆ "21 juin  ┆          │
│           ┆           ┆           ┆           ┆   ┆ "Fra…     ┆           ┆ 2011…     ┆          │
│ 34.012385 ┆ 71.578746 ┆ Peshawar  ┆ Pakistan  ┆ … ┆ [["France ┆ [2001,    ┆ ["6 mars  ┆ 424      │
│           ┆           ┆           ┆           ┆   ┆ "], ["Can ┆ 2002, …   ┆ 2001",    ┆          │
│           ┆           ┆           ┆           ┆   ┆ ada"], …  ┆ 2022]     ┆ "29 mars  ┆          │
│           ┆           ┆           ┆           ┆   ┆ ["F…      ┆           ┆ 2018"…    ┆          │
│ 49.020726 ┆ 6.5380352 ┆ le        ┆ France    ┆ … ┆ [["France ┆ [2023]    ┆ ["9       ┆ 1        │
│           ┆           ┆ Mosellan  ┆           ┆   ┆ "]]       ┆           ┆ octobre   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 2023"]    ┆          │
│ 45.766911 ┆ 4.8352154 ┆ rue Pizay ┆ France    ┆ … ┆ [["France ┆ [2015,    ┆ ["24      ┆ 18       │
│           ┆           ┆           ┆           ┆   ┆ "], ["Fra ┆ 2017,     ┆ novembre  ┆          │
│           ┆           ┆           ┆           ┆   ┆ nce",     ┆ 2018]     ┆ 2018",    ┆          │
│           ┆           ┆           ┆           ┆   ┆ "Belgi…   ┆           ┆ "31       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ décem…    ┆          │
│ 48.874031 ┆ 2.3460886 ┆ rue       ┆ France    ┆ … ┆ [["France ┆ [2007,    ┆ ["15      ┆ 17       │
│           ┆           ┆ Richer    ┆           ┆   ┆ "]]       ┆ 2013, …   ┆ janvier   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 2024]     ┆ 2013", "7 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ janvier…  ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 41.730188 ┆ 20.351695 ┆ Diber     ┆ Albanie   ┆ … ┆ [["France ┆ [2002]    ┆ ["16 juin ┆ 9        │
│           ┆           ┆           ┆           ┆   ┆ ", "Canad ┆           ┆ 2002",    ┆          │
│           ┆           ┆           ┆           ┆   ┆ a"]]      ┆           ┆ "17 juin  ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 2002…     ┆          │
│ 48.86459  ┆ 2.3695854 ┆ rue de    ┆ France    ┆ … ┆ [["France ┆ [2008,    ┆ ["2       ┆ 143      │
│           ┆           ┆ Crussol   ┆           ┆   ┆ "]]       ┆ 2009, …   ┆ janvier   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 2011]     ┆ 2009",    ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ "28       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ décembr…  ┆          │
│ 44.841225 ┆ -0.580036 ┆ Bordeaux  ┆ France    ┆ … ┆ [["France ┆ [1822,    ┆ ["16      ┆ 28586    │
│           ┆           ┆           ┆           ┆   ┆ "], ["Bel ┆ 1946, …   ┆ novembre  ┆          │
│           ┆           ┆           ┆           ┆   ┆ gique"],  ┆ 2025]     ┆ 2005", "8 ┆          │
│           ┆           ┆           ┆           ┆   ┆ … […      ┆           ┆ août 2…   ┆          │
│ 9.9984272 ┆ -84.11712 ┆ Heredia   ┆ Costa     ┆ … ┆ [["France ┆ [2007,    ┆ ["8 août  ┆ 2        │
│           ┆ 1         ┆           ┆ Rica      ┆   ┆ "], ["Sui ┆ 2012]     ┆ 2012",    ┆          │
│           ┆           ┆           ┆           ┆   ┆ sse"]]    ┆           ┆ "28       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ juillet   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 20…       ┆          │
│ 47.125168 ┆ 0.9981375 ┆ Cité      ┆ France    ┆ … ┆ [["France ┆ [2016]    ┆ ["9 juin  ┆ 1        │
│           ┆           ┆ Royale    ┆           ┆   ┆ "]]       ┆           ┆ 2016"]    ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
features = []
for row in df_agg.to_dicts():
    features.append({
        "type": "Feature",
        "geometry": {
            "type": "Point",
            "coordinates": [row["lon"], row["lat"]]  # GeoJSON : lon AVANT lat
        },
        "properties": {
            "lieu": row["entities_places"],
            "pays_right": row["pays_right"] or "",
            "code_pays": row["code_pays"] or "",
            "pays_source": row["pays_source"],
            "journaux": row["journaux"],
            "annees": row["annees"],
            "dates": row["dates"],
            "nb_mentions": row["nb_mentions"]
        }
    })

geojson = {"type": "FeatureCollection", "features": features}

with open("carte/data.geojson", "w", encoding="utf-8") as f:
    json.dump(geojson, f, ensure_ascii=False)

import os
print(f"Taille : {os.path.getsize('carte/data.geojson') / 1e6:.1f} Mo")